### ISSUE TITLE
Strange crash on training start

### ISSUE THREAD

**Issue by netrosec** [ultralytics/ultralytics#1135]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I'm launching a training job on gcp vm but it crashed every time as it starts the first epoch.  Here's the error:

`/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:97: operator(): block: [16,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
      1/150     0.298G      1.254      4.639      1.698          5        640:   0%|          | 2/118792 [00:00<10:51:20,  3.04it/s]
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/cfg/__init__.py", line 304, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/engine/model.py", line 297, in train
    self.trainer.train()
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/engine/trainer.py", line 189, in train
    self._do_train(RANK, world_size)
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/engine/trainer.py", line 310, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/v8/detect/train.py", line 77, in criterion
    return self.compute_loss(preds, batch)
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/v8/detect/train.py", line 188, in __call__
    anchor_points * stride_tensor, gt_labels, gt_bboxes, mask_gt)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/utils/tal.py", line 105, in forward
    mask_gt)
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/utils/tal.py", line 128, in get_pos_mask
    topk_mask=mask_gt.repeat([1, 1, self.topk]).bool())
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/utils/tal.py", line 171, in select_topk_candidates
    topk_idxs[~topk_mask] = 0
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.`

### Environment

- YOLO: Ultralyytics YOLOv8.021 
-OS: Ubuntu 20.04
-Python 3.7

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@netrosec you should try to train with a default dataset, and if that works then it's possible your custom dataset has issues. 

Also I'd recommend training in our Docker image for the best environment compatibility. https://hub.docker.com/r/ultralytics/ultralytics

**Comment by netrosec** [comment]
Yep, it was a dataset issue. Thanks Glenn.

**Comment by pderrenger** [comment]
@netrosec you're welcome! Glad to hear the issue was resolved. If you have any more questions or run into any other issues, feel free to ask. Good luck with your training!
