### ISSUE TITLE
Cannot Train on Google Colaboratory with Custom Dataset

### ISSUE THREAD

**Issue by Yuma-Kanematsu** [ultralytics/ultralytics#13467]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Hello, I'm trying to train YOLOv9c and YOLOv8n with custom dataset(CT images which resized to 640x640 pixels). 
I had tried to train in local environment(VSCode, Rye environment, M3 pro macbook pro), but somehow I cannot use 'MPS' so I used 'CPU' and it worked well(I will show the result below).

 I also created YAML file for my custom dataset. 
```
names:
- Open type
- Fat strangulation type
- Muscle strangulation type
nc: 3
path: /Users/yuma/Yuma-Kanematsu/orbital_fracture_pj/src/src/yolov9_train_test
train: /Users/yuma/Yuma-Kanematsu/orbital_fracture_pj/src/src/yolov9_train_test/images/train
val: /Users/yuma/Yuma-Kanematsu/orbital_fracture_pj/src/src/yolov9_train_test/images/val

```
result:
<img width="1425" alt="スクリーンショット 2024-06-08 16 57 53" src="https://github.com/ultralytics/ultralytics/assets/162325827/e9a01f5d-3f84-4959-9f83-19985a618160">

However, it takes too long to train in local environment so I tried to train in Google Colaboratory. I uploaded 'yolov9_train_test' dataset(which contains yaml file above) to Google Drive and I installed ultralytics and start training.

Code: 
```
from google.colab import drive
drive.mount('/content/drive')
from ultralytics import YOLO

model = YOLO('yolov8n.pt')  # load a pretrained YOLOv8n detection model
model.info()
model.train(data='/content/drive/MyDrive/Orbital_Fracture/yolov9_train_test/dataset_drive.yaml', epochs=10, device = 'gpu')  # train the model
```

When I started it, YOLO starts working, but somehow box_loss and dfl_loss are 0 and precision, recall, mAP@50 are also 0 because of that. 

Result:
```
Model summary: 225 layers, 3011433 parameters, 3011417 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/detect/train3', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
AMP: checks passed ✅
train: Scanning /content/drive/MyDrive/Orbital_Fracture/yolov9_train_test/train/labels.cache... 2719 images, 22 backgrounds, 0 corrupt: 100%|██████████| 2719/2719 [00:00<?, ?it/s]
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
val: Scanning /content/drive/MyDrive/Orbital_Fracture/yolov9_train_test/val/labels.cache... 680 images, 4 backgrounds, 0 corrupt: 100%|██████████| 680/680 [00:00<?, ?it/s]
Plotting labels to runs/detect/train3/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train3
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10       2.2G          0      93.42          0          0        640: 100%|██████████| 170/170 [01:04<00:00,  2.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/22 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:43<00:00,  2.00s/it]                   all        680        850          0          0          0          0


      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/10      2.19G          0      49.23          0          0        640: 100%|██████████| 170/170 [00:22<00:00,  7.72it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:04<00:00,  5.44it/s]                   all        680        850          0          0          0          0


      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/10      2.19G          0      17.71          0          0        640: 100%|██████████| 170/170 [00:21<00:00,  7.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:02<00:00,  7.43it/s]                   all        680        850          0          0          0          0


      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/10      2.17G          0      4.435          0          0        640: 100%|██████████| 170/170 [00:21<00:00,  7.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:02<00:00,  7.56it/s]                   all        680        850          0          0          0          0


      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/10      2.18G          0      1.118          0          0        640: 100%|██████████| 170/170 [00:21<00:00,  7.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:02<00:00,  7.62it/s]                   all        680        850          0          0          0          0


      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/10      2.17G          0     0.2824          0          0        640: 100%|██████████| 170/170 [00:21<00:00,  7.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:02<00:00,  7.59it/s]                   all        680        850          0          0          0          0


      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/10      2.18G          0    0.06099          0          0        640: 100%|██████████| 170/170 [00:21<00:00,  7.97it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:02<00:00,  7.57it/s]                   all        680        850          0          0          0          0


      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/10      2.17G          0    0.01223          0          0        640: 100%|██████████| 170/170 [00:21<00:00,  8.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:02<00:00,  7.76it/s]                   all        680        850          0          0          0          0


      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/10      2.18G          0   0.009157          0          0        640: 100%|██████████| 170/170 [00:21<00:00,  8.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:02<00:00,  7.50it/s]                   all        680        850          0          0          0          0


      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/10      2.17G          0   0.009148          0          0        640: 100%|██████████| 170/170 [00:21<00:00,  8.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:02<00:00,  7.50it/s]                   all        680        850          0          0          0          0


10 epochs completed in 0.103 hours.
Optimizer stripped from runs/detect/train3/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train3/weights/best.pt, 6.2MB

Validating runs/detect/train3/weights/best.pt...
Ultralytics YOLOv8.2.28 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:gpu (Tesla T4, 15102MiB)
Model summary (fused): 168 layers, 3006233 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 22/22 [00:03<00:00,  6.30it/s]                   all        680        850          0          0          0          0

Speed: 0.2ms preprocess, 1.9ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to runs/detect/train3
```

I also get errors below
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

4 frames
/usr/local/lib/python3.10/dist-packages/ultralytics/utils/__init__.py in __getattr__(self, attr)
    160         """Custom attribute access error message with helpful information."""
    161         name = self.__class__.__name__
--> 162         raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
    163 
    164 

AttributeError: 'DetMetrics' object has no attribute 'curves_results'. See valid attributes below.
```

In summary, I cannot able to train YOLOv8n in Google Colaboratory and I don't know why this is happening since I was able to train on local environment. I thought there are problems on datasets, but there are no mistakes when I checked images and labels. 

### Environment

Ultralytics YOLOv8.2.28 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=coco8.yaml, epochs=3, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train6, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train6

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @Yuma-Kanematsu,

Thank you for providing detailed information about the issue you're facing with training YOLOv8n on Google Colaboratory. Let's work through this together to identify and resolve the problem.

### Steps to Troubleshoot:

1. **Verify Package Versions**:
   Ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using the following commands:
   ```python
   !pip install --upgrade torch
   !pip install --upgrade ultralytics
   ```

2. **Check Dataset Path and YAML Configuration**:
   Ensure that the paths specified in your YAML file are correct and accessible in Google Colaboratory. It might help to print the paths and verify their existence:
   ```python
   import os
   print(os.listdir('/content/drive/MyDrive/Orbital_Fracture/yolov9_train_test/images/train'))
   print(os.listdir('/content/drive/MyDrive/Orbital_Fracture/yolov9_train_test/images/val'))
   ```

3. **Minimal Reproducible Example**:
   To help us better understand and reproduce the issue, could you please provide a minimal reproducible example? This should include the code snippet you are using to train the model and any relevant dataset samples. You can refer to our guide on creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

4. **Training on GPU**:
   Ensure that the GPU is being utilized correctly. You can check if PyTorch recognizes the GPU with:
   ```python
   import torch
   print(torch.cuda.is_available())  # Should return True
   print(torch.cuda.get_device_name(0))  # Should return the name of your GPU
   ```

5. **Training Code**:
   Here is a refined version of your training code for Google Colaboratory:
   ```python
   from google.colab import drive
   drive.mount('/content/drive')
   from ultralytics import YOLO

   model = YOLO('yolov8n.pt')  # Load a pretrained YOLOv8n detection model
   model.info()

   # Ensure the dataset path is correct
   data_path = '/content/drive/MyDrive/Orbital_Fracture/yolov9_train_test/dataset_drive.yaml'
   assert os.path.exists(data_path), "Dataset path does not exist!"

   # Train the model
   model.train(data=data_path, epochs=10, device='cuda')  # Use 'cuda' for GPU
   ```

6. **Error Handling**:
   The error message related to `DetMetrics` suggests there might be an issue with the metrics calculation. Ensure that your dataset annotations are correct and that there are no missing or corrupt files.

### Additional Resources:
For more detailed troubleshooting steps, you can refer to our [YOLO Common Issues Guide](https://docs.ultralytics.com/guides/yolo-common-issues/).

Please try these steps and let us know if the issue persists. If you encounter any specific errors, feel free to share them here, and we'll assist you further.

**Comment by Yuma-Kanematsu** [comment]
Hello @glenn-jocher ,
Thank you for answering and detailed advices.

Actually, I had created a dataset(yolov9_train_test) with the same name, but separated it by the dataset that did and did not transform the bounding box coordinates after resizing to 640 pixels. I was uploading the dataset without conversion to the Google Drive. I noticed the problem when I loaded and displayed some of the photos and the label txt file together.

When I ran it on the dataset with the correct coordinate transformations, the training worked fine.

**Comment by glenn-jocher** [comment]
Hello @Yuma-Kanematsu,

Thank you for the update and for sharing the details about your dataset. It's great to hear that you identified the issue with the bounding box coordinates and resolved it by using the correctly transformed dataset. 🎉

For future reference and to help others who might encounter similar issues, here are a few best practices:

1. **Verify Dataset Integrity**:
   Always ensure that your dataset, including images and label files, is correctly formatted and that bounding box coordinates are accurate, especially after any transformations or resizing.

2. **Use Visualization Tools**:
   Visualizing a few samples from your dataset can quickly help identify any discrepancies between the images and their corresponding labels. Here’s a quick example of how you can visualize your dataset using OpenCV:
   ```python
   import cv2
   import os

   def visualize_dataset(image_path, label_path):
       image = cv2.imread(image_path)
       with open(label_path, 'r') as f:
           labels = f.readlines()
       for label in labels:
           class_id, x_center, y_center, width, height = map(float, label.strip().split())
           x_center, y_center, width, height = int(x_center * image.shape[1]), int(y_center * image.shape[0]), int(width * image.shape[1]), int(height * image.shape[0])
           x1, y1, x2, y2 = x_center - width // 2, y_center - height // 2, x_center + width // 2, y_center + height // 2
           cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)
       cv2.imshow('Image with Bounding Boxes', image)
       cv2.waitKey(0)
       cv2.destroyAllWindows()

   # Example usage
   visualize_dataset('/path/to/image.jpg', '/path/to/label.txt')
   ```

3. **Regularly Update Packages**:
   Ensure you are using the latest versions of `torch` and `ultralytics` to benefit from the latest features and bug fixes. You can upgrade them using:
   ```bash
   !pip install --upgrade torch
   !pip install --upgrade ultralytics
   ```

4. **Minimum Reproducible Example**:
   If you encounter any issues in the future, providing a minimal reproducible example will help us diagnose and resolve the problem more efficiently. You can refer to our guide on creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

If you have any more questions or run into any other issues, feel free to reach out. We're here to help! 😊
