### ISSUE TITLE
problem with multiGPU

### ISSUE THREAD

**Issue by LPZliu** [ultralytics/ultralytics#13589]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

DDP: debug command d:\ProgramData\miniconda3\envs\test1\python.exe -m torch.distributed.run --nproc_per_node 2 --master_port 57243 C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_lgibl1s83282325877680.py
W0614 18:15:29.477000 13952 torch\distributed\elastic\multiprocessing\redirects.py:27] NOTE: Redirects are currently not supported in Windows or MacOs.
[E socket.cpp:957] [c10d] The client socket has timed out after 900s while trying to connect to (127.0.0.1, 57243).
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\run.py", line 883, in <module>
    main()
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\run.py", line 879, in main
    run(args)
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\run.py", line 870, in run
    elastic_launch(
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\launcher\api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\launcher\api.py", line 254, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 733, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 870, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 705, in _initialize_workers
    self._rendezvous(worker_group)
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 548, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.distributed.DistNetworkError: The client socket has timed out after 900s while trying to connect to (127.0.0.1, 57243).
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\ProgramData\miniconda3\envs\test1\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\ultralytics\cfg\__init__.py", line 591, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\ultralytics\engine\model.py", line 674, in train
    self.trainer.train()
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\ultralytics\engine\trainer.py", line 194, in train
    raise e
  File "d:\ProgramData\miniconda3\envs\test1\Lib\site-packages\ultralytics\engine\trainer.py", line 192, in train
    subprocess.run(cmd, check=True)
  File "d:\ProgramData\miniconda3\envs\test1\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['d:\\ProgramData\\miniconda3\\envs\\test1\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '57243', 'C:\\Users\\Administrator\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_lgibl1s83282325877680.py']' returned non-zero exit status 1.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by maxgameone** [comment]
I also encountered this mistake with the latest version,old version worked fine

**Comment by glenn-jocher** [comment]
@maxgameone hi there,

Thank you for reporting this issue. It seems like you're encountering a timeout error when trying to run YOLOv8 with multiple GPUs on Windows. Let's address this step-by-step:

1. **Ensure Latest Versions**: First, please make sure you are using the latest versions of both `torch` and `ultralytics`. You can update them using the following commands:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Minimum Reproducible Example**: To help us investigate further, could you provide a minimal reproducible example of your code? This will allow us to replicate the issue on our end. You can find guidelines on creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

3. **Windows and DDP**: Distributed Data Parallel (DDP) can sometimes be tricky on Windows. Ensure that your environment is correctly set up for multi-GPU training. You might want to try setting the `MASTER_ADDR` and `MASTER_PORT` environment variables manually before running your script:
    ```python
    import os
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29500'
    ```

4. **Alternative Approach**: If the issue persists, consider using `torchrun` instead of `torch.distributed.run` for launching your multi-GPU training. This can sometimes resolve connectivity issues:
    ```bash
    torchrun --nproc_per_node=2 --master_port=29500 your_script.py
    ```

Please try these steps and let us know if the issue persists. Your feedback is invaluable in helping us improve the software. 😊

**Comment by vsarkhel** [comment]
Check which backend your using for torch distributed, It may be fixable by setting some NCCL environment variables. It may not be recognizing some interface correctly and the only way to fix that is via those [NCCL environment variables ](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html). I had to do that when I altered Ultralytics slightly to get Multi-Node training working with torchrun. (on Ubuntu Linux, not Windows)

**Comment by glenn-jocher** [comment]
Hi @vsarkhel,

Thank you for your insightful suggestion! Setting NCCL environment variables can indeed help resolve some backend issues with `torch.distributed`. For Windows users, however, NCCL is not supported, and we typically rely on Gloo as the backend.

To ensure you're using the correct backend and to set the necessary environment variables, you can try the following:

1. **Set Backend to Gloo**:
    ```python
    import os
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29500'
    os.environ['TORCH_DISTRIBUTED_DEBUG'] = 'DETAIL'
    os.environ['NCCL_DEBUG'] = 'INFO'
    ```

2. **Specify Backend in Your Script**:
    ```python
    import torch.distributed as dist

    dist.init_process_group(backend='gloo')
    ```

3. **Check for Latest Versions**: Ensure you are using the latest versions of `torch` and `ultralytics`:
    ```bash
    pip install --upgrade torch ultralytics
    ```

4. **Minimal Reproducible Example**: If the issue persists, providing a minimal reproducible example would be very helpful. You can find guidelines on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Please try these steps and let us know if it helps resolve the issue. Your feedback is greatly appreciated! 😊

**Comment by mmarei1** [comment]
Despite numerous tests to attempt workarounds to the training process with multi-GPU on Windows, I've finally worked out how to get this to work but my solution is not very elegant.

Firstly, I'm using Windows with a dual NVIDIA RTX A4500 setup. 
My CUDA version is 12.6. PyTorch is v '2.4.1_cu121; Ultralytics is 8.3.34 with Python 3.11.0. 

Single-GPU acceleration has worked relatively well for me but when it came to testing out larger models with bigger batch sizes, I came to realise that multi-GPU acceleration would be essential. I read multiple guides on the torch.distributed library to try and figure out how to override the libuv dependency (which is the core problem faced by my multi-GPU training scripts). After successfully training on a single GPU without issues, when it came to using both GPUs in the training script, I got the following error:
``
YOLO11m-obb summary: 434 layers, 20,904,927 parameters, 20,904,911 gradients, 71.9 GFLOPs

Transferred 685/691 items from pretrained weights
DDP: debug command C:\Users\marei_m\AppData\Local\anaconda3\envs\dlws_py11\python.exe -m torch.distributed.run --nproc_per_node 2 --master_port 63826 C:\Users\marei_m\AppData\Roaming\Ultralytics\DDP\_temp_68ew6drn1624968684112.py
W1120 14:38:01.992000 28192 torch\distributed\elastic\multiprocessing\redirects.py:28] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\run.py", line 905, in <module>
    main()
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\run.py", line 901, in main
    run(args)
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\run.py", line 892, in run
    elastic_launch(
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\launcher\api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\launcher\api.py", line 255, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\elastic\agent\server\api.py", line 681, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\elastic\agent\server\api.py", line 830, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\elastic\agent\server\api.py", line 653, in _initialize_workers
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\elastic\agent\server\api.py", line 490, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marei_m\AppData\Roaming\Python\Python311\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 68, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: use_libuv was requested but PyTorch was build without libuv support
Traceback (most recent call last):
  File "M:\Documents\LANDOne_data\alg_dataset\main\algv2\notebooks\yolo11_mve_multi_gpu.py", line 77, in <module>
    results = model.train(data='M:/Documents/LANDOne_data/alg_dataset/main/algv2/datasets/algv10_ipad_and_headsets/data.yaml',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marei_m\AppData\Local\anaconda3\envs\dlws_py11\Lib\site-packages\ultralytics\engine\model.py", line 802, in train
    self.trainer.train()
  File "C:\Users\marei_m\AppData\Local\anaconda3\envs\dlws_py11\Lib\site-packages\ultralytics\engine\trainer.py", line 209, in train
    raise e
  File "C:\Users\marei_m\AppData\Local\anaconda3\envs\dlws_py11\Lib\site-packages\ultralytics\engine\trainer.py", line 207, in train
    subprocess.run(cmd, check=True)
  File "C:\Users\marei_m\AppData\Local\anaconda3\envs\dlws_py11\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\marei_m\\AppData\\Local\\anaconda3\\envs\\dlws_py11\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '63826', 'C:\\Users\\marei_m\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_68ew6drn1624968684112.py']' returned non-zero exit status 1.
``
The main error was due to libuv support being expcted in the Pytorch build, which is not correctly executed when pytorch is installed after Ultralytics (unless Pytorch has been built from source, which is another can of worms entirely).

Having failed to build Pytorch from source with libuv support, I tried every suggestion for overriding the libuv dependency at the Ultralytics library level, none of which managed to resolve my issue. I finally decided to override libuv dependency at the TCPStore  declaration in the pytorch static_tcp_rendezvous.py, by explicitly passing the use_libuv=false flag to the TCPStore initialisation, i.e. (lines 64:76)
`
     def next_rendezvous(self) -> RendezvousInfo:
            logger.info("Creating TCPStore as the c10d::Store implementation")
            is_master = self.rank == 0
            if not self._store:
                self._store = TCPStore(  # type: ignore[call-arg]
                    self.master_addr,
                    self.master_port,
                    self.world_size,
                    is_master,
                    self.timeout,
                    multi_tenant=True,
                    use_libuv=False
                )
            store = PrefixStore(self.run_id, self._store)
`
I followed the [Distributed TCP Store guidance ](https://pytorch.org/tutorials/intermediate/TCPStore_libuv_backend.html) in the Pytorch official documentation. The main limitation I've faced is that the GPU workload is only displayed for the first GPU in the training verbose log.

I get that libuv support is essential for a material performance boost for accelerated training, but this temporary fix has resolved my problem and I can now train my models on both GPUs simultaneously (which can be verified by running the nvidia-smi command in a terminal during training and you can loop the update in a given interval).

If anyone else has better ideas for how this can be resolved, I'm very interested to see your workarounds.

**Comment by glenn-jocher** [comment]
Thank you for sharing your detailed workaround for the multi-GPU training issue on Windows. It’s great to hear that you’ve managed to find a solution that works for you, even if it’s not ideal. Your approach to modifying the `TCPStore` initialization is insightful, and it could be helpful for others facing similar challenges. For those looking for more robust solutions, exploring Docker containers with NVIDIA support on Linux might offer better multi-GPU performance due to more mature support for distributed training. If anyone else has alternative solutions or improvements, feel free to share them here. Your contributions are invaluable to the community!

**Comment by mmarei1** [comment]
> Thank you for sharing your detailed workaround for the multi-GPU training issue on Windows. It’s great to hear that you’ve managed to find a solution that works for you, even if it’s not ideal. Your approach to modifying the `TCPStore` initialization is insightful, and it could be helpful for others facing similar challenges. For those looking for more robust solutions, exploring Docker containers with NVIDIA support on Linux might offer better multi-GPU performance due to more mature support for distributed training. If anyone else has alternative solutions or improvements, feel free to share them here. Your contributions are invaluable to the community!

This was actually a workaround after experiencing the same libuv dependency runtime error on the Ultralytics Docker image. I was racking my head trying to figure out the solution because the multi-GPU issue wasn't working with either native Windows conda package, WSL2, or Docker.

**Comment by glenn-jocher** [comment]
@mmarei1 thank you for sharing your experience and insights on the multi-GPU issue. If the problem persists across different environments, it might be worth checking for any updates or patches from PyTorch related to libuv support. Additionally, exploring community forums or reaching out to PyTorch's GitHub repository might provide further insights or solutions. Your contributions are invaluable, and any additional findings would be beneficial to the community.
