### ISSUE TITLE
cuda memory error in ultralytics 8.0.52

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#1367]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Multi-GPU

### Bug

After upgrading to the latest version (ultralytics 8.0.52), I am getting cuda memory error. I could run it successfully by moving back to ultralytics 8.0.40. I did not check the versions in between to figure out the exact version that this error starts.

```
      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size

    0%|          | 0/333 [00:00<?, ?it/s]
    0%|          | 0/333 [00:01<?, ?it/s]
  Traceback (most recent call last):
    File "/home/ubuntu/.config/Ultralytics/DDP/_temp_f0b1fslr140113406604240.py", line 6, in <module>
      trainer.train()
    File "/shared/data/personal_data/experiments/ultralytics/ultralytics/yolo/engine/trainer.py", line 186, in train
      self._do_train(RANK, world_size)
    File "/shared/data/personal_data/experiments/ultralytics/ultralytics/yolo/engine/trainer.py", line 312, in _do_train
      self.loss, self.loss_items = self.criterion(preds, batch)
    File "/shared/data/personal_data/experiments/ultralytics/ultralytics/yolo/v8/segment/train.py", line 40, in criterion
      return self.compute_loss(preds, batch)
    File "/shared/data/personal_data/experiments/ultralytics/ultralytics/yolo/v8/segment/train.py", line 125, in __call__
      loss[1] += self.single_mask_loss(gt_mask, pred_masks[i][fg_mask[i]], proto[i], mxyxy,
    File "/shared/data/personal_data/experiments/ultralytics/ultralytics/yolo/v8/segment/train.py", line 143, in single_mask_loss
      loss = F.binary_cross_entropy_with_logits(pred_mask, gt_mask, reduction='none')
    File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/nn/functional.py", line 3162, in binary_cross_entropy_with_logits
      return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
  torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 22.20 GiB total capacity; 9.97 GiB already allocated; 23.06 MiB free; 10.15 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7945 closing signal SIGTERM
  WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7946 closing signal SIGTERM
  WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7947 closing signal SIGTERM
  WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7948 closing signal SIGTERM
  WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7949 closing signal SIGTERM
  WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7950 closing signal SIGTERM
  WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 7951 closing signal SIGTERM
  ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 7944) of binary: /home/ubuntu/mambaforge/bin/python3.10
  Traceback (most recent call last):
    File "/home/ubuntu/mambaforge/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/ubuntu/mambaforge/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/run.py", line 766, in <module>
      main()
    File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
      return f(*args, **kwargs)
    File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
      run(args)
    File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
      elastic_launch(
    File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
      return launch_agent(self._config, self._entrypoint, list(args))
    File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
      raise ChildFailedError(
  torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
  =
```
### Environment

Ultralytics YOLOv8.0.52 🚀 Python-3.10.6 torch-1.13.0 CUDA:0 (NVIDIA A10G, 22732MiB)
                                                      CUDA:1 (NVIDIA A10G, 22732MiB)
                                                      CUDA:2 (NVIDIA A10G, 22732MiB)
                                                      CUDA:3 (NVIDIA A10G, 22732MiB)
                                                      CUDA:4 (NVIDIA A10G, 22732MiB)
                                                      CUDA:5 (NVIDIA A10G, 22732MiB)
                                                      CUDA:6 (NVIDIA A10G, 22732MiB)
                                                      CUDA:7 (NVIDIA A10G, 22732MiB)

### Minimal Reproducible Example

yolo task=segment mode=train model=yolov8x-seg.pt data=./data/full_data.yaml epochs=150 imgsz=1152 batch=32 cache=False workers=20 mask_ratio=1 patience=100 close_mosaic=10 degrees=45.0 project=./runs name='ex22 ' device=\'0,1,2,3,4,5,6,7\'  

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@glenn-jocher this seems urgent!

**Comment by glenn-jocher** [comment]
@mehran66 I just trained a DDP model in our Docker Image using 8.0.52 with no issues. I'm not able to reproduce any CUDA errors, so it's likely that your model, imgsz or batch size is simply too large for your training. I would try reducing `batch` or `imgsz` for reduced CUDA memory requirements.

**Comment by mehran66** [comment]
@glenn-jocher I used the exact same model, imgsz and batch size before and after upgrading ultralytics. After upgrading, I even tested with batch size 2 and after 10 epochs it ended with cuda memory error. Also, I tested training using two different approaches; command line and python script.  command line gave me the cuda memory error, but the pyhton code gave me an error like "error in the config file" (I did not save that error). Eventually, I did checkout to version 8.0.4 and things got back to normal.

**Comment by Laughing-q** [comment]
@mehran66 could you please try your training again with 8.0.51? 
Not sure if it's related, but we introduced a upgraded tal assigner in 8.0.52. But it should reduce the cuda memory usage and it did use less cuda memory in our tests.

**Comment by mehran66** [comment]
@Laughing-q  sure...my resources are busy now. I'll run a test on 8.0.51 as soon as possible.

**Comment by mehran66** [comment]
@Laughing-q The cuda error I described above starts on ultralytics 8.0.50. I can starts training without any issues on version 8.0.49.

The above-mentioned issue is occurring when I run training through command line. I also have another issue when training using python script. I get the following error and this error get resolved if I get back to version ultralytics 8.0.45.

  train.py: error: unrecognized arguments: task=segment mode=train model=yolov8x-seg.pt data=/shared/data/personal_data/experiments/yolo/yolo_training/data/full_data.yaml epochs=150 patience=50 batch=32 imgsz=1152 save=True save_period=-1 cache=False device=0,1,2,3,4,5,6,7 workers=16 project=/shared/data/personal_data/experiments/yolo/yolo_training/runs name=ex22 exist_ok=False pretrained=False optimizer=SGD verbose=True seed=0 deterministic=True single_cls=False image_weights=False rect=False cos_lr=False close_mosaic=10 resume=False min_memory=False overlap_mask=True mask_ratio=4 dropout=0.0 val=True split=val save_json=False save_hybrid=False conf=None iou=0.7 max_det=300 half=False dnn=False plots=True source=None show=False save_txt=False save_conf=False save_crop=False hide_labels=False hide_conf=False vid_stride=1 line_thickness=3 visualize=False augment=False agnostic_nms=False classes=None retina_masks=False boxes=True format=torchscript keras=False optimize=False int8=False dynamic=False simplify=False opset=None workspace=4 nms=False lr0=0.01 lrf=0.01 momentum=0.937 weight_decay=0.0005 warmup_epochs=3.0 warmup_momentum=0.8 warmup_bias_lr=0.1 box=7.5 cls=0.5 dfl=1.5 fl_gamma=0.0 label_smoothing=0.0 nbs=64 hsv_h=0.015 hsv_s=0.7 hsv_v=0.4 degrees=0.0 translate=0.1 scale=0.5 shear=0.0 perspective=0.0 flipud=0.0 fliplr=0.5 mosaic=1.0 mixup=0.0 copy_paste=0.0 cfg=None v5loader=False tracker=botsort.yaml

**Comment by glenn-jocher** [comment]
@Laughing-q @mehran66 ok I think I'm able to reproduce something. 

In 8.0.50 (before AMP checks were implemented) DDP correctly uses 2 processes if I use a 2-GPU command:
<img width="565" alt="Screenshot 2023-03-12 at 01 00 08" src="https://user-images.githubusercontent.com/26833433/224516942-bba6d1d8-4a4d-44d6-bfcc-4ca97cb4913a.png">

But starting in 8.0.51 the first GPU uses two processes:
<img width="576" alt="Screenshot 2023-03-12 at 00 59 59" src="https://user-images.githubusercontent.com/26833433/224516944-acdd7373-3b79-4c32-977d-5396ad71277e.png">

I'm guessing it may be related to the AMP checks.

**Comment by glenn-jocher** [comment]
@Laughing-q @mehran66 ok I've found a bug in AMP checks for DDP. I've fixed this in https://github.com/ultralytics/ultralytics/pull/1362 for 8.0.53 now by running checks only on RANK 0 and then broadcasting to all other RANKs. I've verified this works with DDP and Single GPU.

<img width="1079" alt="Screenshot 2023-03-12 at 01 46 47" src="https://user-images.githubusercontent.com/26833433/224518187-d77b8b13-892b-4426-8643-1f08767ec8bf.png">
