### ISSUE TITLE
Error Code 2: Internal Error (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed. )

### ISSUE THREAD

**Issue by wanghuajia** [ultralytics/ultralytics#13820]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

[06/20/2024-02:35:00] [TRT] [E] 2: [ltWrapper.cpp::setupHeuristic::349] Error Code 2: Internal Error (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed. )
TensorRT: export failure ❌ 510.4s: __enter__
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    model.export(
  File "/home/huajia/code/ultralytics/ultralytics/engine/model.py", line 602, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/huajia/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/huajia/code/ultralytics/ultralytics/engine/exporter.py", line 300, in __call__
    f[1], _ = self.export_engine()
  File "/home/huajia/code/ultralytics/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/home/huajia/code/ultralytics/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/huajia/code/ultralytics/ultralytics/engine/exporter.py", line 798, in export_engine
    with build(network, config) as engine, open(f, "wb") as t:
AttributeError: __enter__

### Environment

[enc](env: cuda10.2, tensorrt8.4.3.4)

### Minimal Reproducible Example
The solution is as follows
A workaround is adding some code after
`/home/huajia/code/ultralytics/ultralytics/engine/exporter.py
config = builder.create_builder_config()
`
config.set_tactic_sources(1<<int(trt.TacticSource.CUBLAS))

reference the link [https://github.com/open-mmlab/mmdeploy/issues/261](url)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @wanghuajia,

Thank you for bringing this issue to our attention. The error you're encountering seems to be related to TensorRT and cuBLAS during the export process.

To assist you better, could you please provide a minimal reproducible code example? This will help us replicate the issue on our end and investigate a solution. You can find guidelines on creating a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can update your packages using the following commands:
```bash
pip install --upgrade torch ultralytics
```

Your suggested workaround involving the `set_tactic_sources` method is interesting. If you have already tested this and it resolves the issue, feel free to share the modified code snippet. However, we still need to reproduce the issue to ensure a comprehensive fix.

Looking forward to your response!

**Comment by wanghuajia** [comment]
> Hello @wanghuajia,
> 
> Thank you for bringing this issue to our attention. The error you're encountering seems to be related to TensorRT and cuBLAS during the export process.
> 
> To assist you better, could you please provide a minimal reproducible code example? This will help us replicate the issue on our end and investigate a solution. You can find guidelines on creating a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can update your packages using the following commands:
> 
> ```shell
> pip install --upgrade torch ultralytics
> ```
> 
> Your suggested workaround involving the `set_tactic_sources` method is interesting. If you have already tested this and it resolves the issue, feel free to share the modified code snippet. However, we still need to reproduce the issue to ensure a comprehensive fix.
> 
> Looking forward to your response!

I have solved the problem. The problem is mainly caused by cuda10.2.
The solution is as follows
A workaround is adding some code after
`/home/huajia/code/ultralytics/ultralytics/engine/exporter.py
config = builder.create_builder_config() 
config.set_tactic_sources(1<<int(trt.TacticSource.CUBLAS)) # add the code
`
reference the link[https://github.com/open-mmlab/mmdeploy/issues/261](url)

**Comment by glenn-jocher** [comment]
Hello @wanghuajia,

Thank you for the update and for sharing your solution! It's great to hear that you were able to resolve the issue by adjusting the TensorRT configuration.

For others who might encounter a similar problem, your workaround of adding `config.set_tactic_sources(1<<int(trt.TacticSource.CUBLAS))` after `config = builder.create_builder_config()` in the `exporter.py` file is valuable. This adjustment helps ensure that the cuBLAS tactic source is correctly set, which can address compatibility issues with CUDA 10.2.

If you have any further questions or run into other issues, feel free to reach out. We're here to help! 😊
