### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by SMSajadi99** [ultralytics/ultralytics#14236]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

```python
!yolo task=detect mode=train model=yolov8n.pt data=/content/Custom-Data-YOLOv8-Iranian-license-plates/Plate_Detection/custom.yaml epochs=25 imgsz=640
```

```bash
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
```

------------------------

change code to:

```python
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
```

or

```bash
!export CUDA_LAUNCH_BLOCKING=1
```

```bash
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Environment

Ultralytics YOLOv8.2.50 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 34.5/78.2 GB disk)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SMSajadi99** [comment]
I am working in colab and torch, cuda and gpu are active and in T4 mode.

**Comment by SMSajadi99** [comment]
```python
!pip install --upgrade torch ultralytics
```
i try this code, but There is still an error

**Comment by SMSajadi99** [comment]
Thank you very much, my problem is solved ❤️

**Comment by glenn-jocher** [comment]
@SMSajadi99 you're welcome! I'm glad to hear that your issue is resolved ❤️. If you have any more questions or run into any other issues, feel free to ask. The YOLO community and the Ultralytics team are always here to help. Happy coding! 🚀

**Comment by deKeijzer** [comment]
How did you manage to solve this @SMSajadi99 ? Am having the same issue on a 3090 with the latest stable pytorch and ultralytics version.

**Comment by SMSajadi99** [comment]
> How did you manage to solve this @SMSajadi99 ? Am having the same issue on a 3090 with the latest stable pytorch and ultralytics version.

I use colab, my problem has been the classification of text files.

**Comment by glenn-jocher** [comment]
Hi @SMSajadi99,

It sounds like you're encountering a similar issue with a CUDA error. Here are a few steps you can take to troubleshoot and potentially resolve the problem:

1. **Verify Dataset and Labels**: Ensure that your dataset and labels are correctly formatted and that there are no issues with the annotations. Misformatted labels can often cause CUDA errors during training.

2. **Check for Class Mismatches**: Make sure that the number of classes in your dataset matches the number of classes specified in your model configuration. Mismatches here can lead to device-side assertions.

3. **Update Packages**: Ensure you are using the latest versions of PyTorch and Ultralytics. You can update them using:
   ```bash
   pip install --upgrade torch ultralytics
   ```

4. **Enable CUDA Launch Blocking**: This can help provide more detailed error messages:
   ```python
   import os
   os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
   ```

5. **Run with Debugging Flags**: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. This can provide more insight into where the error is occurring.

6. **Check for GPU Compatibility**: Ensure that your GPU drivers and CUDA toolkit are compatible with the versions of PyTorch and Ultralytics you are using.

If the issue persists, providing a minimal reproducible example can greatly help in diagnosing the problem. You can find more information on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to share more details or code snippets if you need further assistance. The community and the Ultralytics team are here to help! 😊

**Comment by furycurry** [comment]
> > How did you manage to solve this @SMSajadi99 ? Am having the same issue on a 3090 with the latest stable pytorch and ultralytics version.
> 
> I use colab, my problem has been the classification of text files.

@SMSajadi99 can you kindly tell in what way you arranged the content of text file? I have converted a coco type dataset to yolo format and then this error showed up after running the converted dataset in yolo model (v8).

**Comment by SMSajadi99** [comment]
@furycurry hi 👋,  I put this file and folder in one of my repos, you can take a look...
https://github.com/SMSajadi99/Custom-Data-YOLOv8-Person-Detection
