### ISSUE TITLE
CUDA out of memory while plenty of memory left

### ISSUE THREAD

**Issue by deKeijzer** [ultralytics/ultralytics#14367]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Within the first epoch training stops with error `CUDA error: out of memory` even tho `nvidia-smi` reports there to be 16 GB of VRAM left.  The full error is found below. I would not expect this to be the actual reason of the training to crash. 

My system memory is only using 36 GB out of 128 GB. I observe no indication that the CUDA memory (24 GB) approaches its capacity during training. The bug seems to appear sooner in training when increasing workers. It's present on CUDA 11.8, CUDA 12.4 and 12.8. Albeit it appears less fast at CUDA 11.8. That's a rather qualitative statement tho. I am expecting there to be some versioning error that I have been unable to locate. The bug essentially appears already for the minimal training example with coco.

```Ultralytics YOLOv8.2.54 🚀 Python-3.11.6 torch-2.3.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=/home/bdk/HandenScanZorg/UltralyticsTests/coco.yaml, epochs=25, time=None, patience=100, batch=32, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=2, project=None, name=train62, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train62

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
...
Transferred 355/355 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/detect/train62', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?f9f83b02-6450-4f1a-9042-182d7dbc350a) or open in a [text editor](command:workbench.action.openLargeOutput?f9f83b02-6450-4f1a-9042-182d7dbc350a). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
/home/bdk/anaconda3/lib/python3.11/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at /opt/conda/conda-bld/pytorch_1716905971190/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:84.)
  return F.conv2d(input, weight, bias, self.stride,
AMP: checks passed ✅
train: Scanning /home/bdk/HandenScanZorg/UltralyticsTests/coco/labels/train2017.cache... 117266 images, 1021 backgrounds, 0 corrupt: 100%|██████████| 118287/118287 [00:00<?, ?it/s]
val: Scanning /home/bdk/HandenScanZorg/UltralyticsTests/coco/labels/val2017.cache... 4952 images, 48 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
Plotting labels to runs/detect/train62/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs/detect/train62
Starting training for 25 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/25      7.25G      1.118      1.355       1.17        181        640: 100%|██████████| 3697/3697 [18:57<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  70%|██████▉   | 55/79 [00:35<00:15,  1.56it/s]```
                 
                 
                 ```---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], [line 26](vscode-notebook-cell:?execution_count=1&line=26)
     [12](vscode-notebook-cell:?execution_count=1&line=12) model = YOLO('yolov8n.pt')
     [14](vscode-notebook-cell:?execution_count=1&line=14) params = {
     [15](vscode-notebook-cell:?execution_count=1&line=15)     #'data': '/home/bdk/HandenScanZorg/UltralyticsTests/HandenScan_V0.yaml',  # Path to the data configuration file
     [16](vscode-notebook-cell:?execution_count=1&line=16)     'data': '/home/bdk/HandenScanZorg/UltralyticsTests/coco.yaml',  # Path to the data configuration file
   (...)
     [22](vscode-notebook-cell:?execution_count=1&line=22)     'workers': 2,  # Number of workers for data loading
     [23](vscode-notebook-cell:?execution_count=1&line=23) }
---> [26](vscode-notebook-cell:?execution_count=1&line=26) results = model.train(**params)

File ~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/model.py:650, in Model.train(self, trainer, **kwargs)
    [647](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/model.py:647)     self.model = self.trainer.model
    [649](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/model.py:649) self.trainer.hub_session = self.session  # attach optional HUB session
--> [650](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/model.py:650) self.trainer.train()
    [651](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/model.py:651) # Update model and cfg after training
    [652](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/model.py:652) if RANK in {-1, 0}:

File ~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:204, in BaseTrainer.train(self)
    [201](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:201)         ddp_cleanup(self, str(file))
    [203](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:203) else:
--> [204](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:204)     self._do_train(world_size)

File ~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:429, in BaseTrainer._do_train(self, world_size)
    [427](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:427) # Validation
    [428](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:428) if self.args.val or final_epoch or self.stopper.possible_stop or self.stop:
--> [429](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:429)     self.metrics, self.fitness = self.validate()
    [430](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:430) self.save_metrics(metrics={**self.label_loss_items(self.tloss), **self.metrics, **self.lr})
    [431](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:431) self.stop |= self.stopper(epoch + 1, self.fitness) or final_epoch

File ~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:570, in BaseTrainer.validate(self)
    [564](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:564) def validate(self):
    [565](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:565)     """
    [566](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:566)     Runs validation on test set using self.validator.
    [567](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:567) 
    [568](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:568)     The returned dict is expected to contain "fitness" key.
    [569](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:569)     """
--> [570](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:570)     metrics = self.validator(self)
    [571](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:571)     fitness = metrics.pop("fitness", -self.loss.detach().cpu().numpy())  # use loss as fitness measure if not found
    [572](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/trainer.py:572)     if not self.best_fitness or self.best_fitness < fitness:

File ~/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    [112](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py:112) @functools.wraps(func)
    [113](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py:113) def decorate_context(*args, **kwargs):
    [114](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py:114)     with ctx_factory():
--> [115](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py:115)         return func(*args, **kwargs)

File ~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/validator.py:169, in BaseValidator.__call__(self, trainer, model)
    [167](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/validator.py:167) self.init_metrics(de_parallel(model))
    [168](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/validator.py:168) self.jdict = []  # empty before each val
--> [169](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/validator.py:169) for batch_i, batch in enumerate(bar):
    [170](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/validator.py:170)     self.run_callbacks("on_val_batch_start")
    [171](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/engine/validator.py:171)     self.batch_i = batch_i

File ~/anaconda3/lib/python3.11/site-packages/tqdm/std.py:1181, in tqdm.__iter__(self)
   [1178](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/tqdm/std.py:1178) time = self._time
   [1180](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/tqdm/std.py:1180) try:
-> [1181](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/tqdm/std.py:1181)     for obj in iterable:
   [1182](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/tqdm/std.py:1182)         yield obj
   [1183](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/tqdm/std.py:1183)         # Update and possibly print the progressbar.
   [1184](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/tqdm/std.py:1184)         # Note: does not call self.update(1) for speed optimisation.

File ~/anaconda3/lib/python3.11/site-packages/ultralytics/data/build.py:48, in InfiniteDataLoader.__iter__(self)
     [46](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/data/build.py:46) """Creates a sampler that repeats indefinitely."""
     [47](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/data/build.py:47) for _ in range(len(self)):
---> [48](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/ultralytics/data/build.py:48)     yield next(self.iterator)

File ~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:631, in _BaseDataLoaderIter.__next__(self)
    [628](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:628) if self._sampler_iter is None:
    [629](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:629)     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    [630](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:630)     self._reset()  # type: ignore[call-arg]
--> [631](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:631) data = self._next_data()
    [632](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:632) self._num_yielded += 1
    [633](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:633) if self._dataset_kind == _DatasetKind.Iterable and \
    [634](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:634)         self._IterableDataset_len_called is not None and \
    [635](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:635)         self._num_yielded > self._IterableDataset_len_called:

File ~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1346, in _MultiProcessingDataLoaderIter._next_data(self)
   [1344](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1344) else:
   [1345](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1345)     del self._task_info[idx]
-> [1346](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1346)     return self._process_data(data)

File ~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1372, in _MultiProcessingDataLoaderIter._process_data(self, data)
   [1370](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1370) self._try_put_index()
   [1371](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1371) if isinstance(data, ExceptionWrapper):
-> [1372](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1372)     data.reraise()
   [1373](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1373) return data

File ~/anaconda3/lib/python3.11/site-packages/torch/_utils.py:705, in ExceptionWrapper.reraise(self)
    [701](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/_utils.py:701) except TypeError:
    [702](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/_utils.py:702)     # If the exception takes multiple arguments, don't try to
    [703](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/_utils.py:703)     # instantiate since we don't know how to
    [704](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/_utils.py:704)     raise RuntimeError(msg) from None
--> [705](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/bdk/HandenScanZorg/UltralyticsTests/~/anaconda3/lib/python3.11/site-packages/torch/_utils.py:705) raise exception

RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/home/bdk/anaconda3/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 37, in do_one_step
    data = pin_memory(data, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bdk/anaconda3/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 68, in pin_memory
    clone.update({k: pin_memory(sample, device) for k, sample in data.items()})
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bdk/anaconda3/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 68, in <dictcomp>
    clone.update({k: pin_memory(sample, device) for k, sample in data.items()})
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bdk/anaconda3/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 58, in pin_memory
    return data.pin_memory(device)
           ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.```

### Environment

Ultralytics YOLOv8.2.54 🚀 Python-3.11.6 torch-2.3.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
Setup complete ✅ (16 CPUs, 125.7 GB RAM, 155.5/1006.9 GB disk)

### Minimal Reproducible Example

from ultralytics import YOLO
import torch
import torch.nn as nn
import os

os.environ['CUDA_LAUNCH_BLOCKING']="1"
os.environ['TORCH_USE_CUDA_DSA'] = "1"

torch.cuda.empty_cache()

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

params = {
    'data': 'coco.yaml',
    'imgsz': 640,
    'epochs': 25,  
    
    'cache': False, 
    'batch': 32,  
    'workers': 2,
}


results = model.train(**params)

### Additional

Coco8 runs, coco does not. Other large coco-structured like datasets also do not run.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by deKeijzer** [comment]
I understand this to not be reproducible. It is present on both my wsl2 as my windows environment. As it turns out, the issue only occurs when setting workers >0.

**Comment by glenn-jocher** [comment]
@deKeijzer thank you for the detailed follow-up. It appears that the issue is related to the number of workers used during training and validation. Here are a few suggestions to help diagnose and potentially resolve the issue:

1. **Pin Memory**: Ensure that `pin_memory` is set to `True` in your DataLoader. This can help with faster data transfer to the GPU.
    ```python
    params = {
        'data': 'coco.yaml',
        'imgsz': 640,
        'epochs': 25,  
        'cache': False, 
        'batch': 32,  
        'workers': 2,
        'pin_memory': True
    }
    ```

2. **Reduce Batch Size**: Try reducing the batch size to see if it alleviates the memory issue.
    ```python
    params['batch'] = 16
    ```

3. **CUDA Memory Management**: Explicitly clear the CUDA cache before starting training.
    ```python
    import torch
    torch.cuda.empty_cache()
    ```

4. **Environment Variables**: Ensure that the environment variables are set correctly.
    ```python
    os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
    os.environ['TORCH_USE_CUDA_DSA'] = "1"
    ```

5. **Latest Versions**: Verify that you are using the latest versions of PyTorch, CUDA, and the Ultralytics YOLO repository.

If the issue persists, please provide a minimal reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us investigate further. Thank you for your patience and cooperation!

**Comment by deKeijzer** [comment]
Thank you for the consideration of this bug,  which is not minimally reproducible by just Python code. 

I now recall to have swapped a 3090 FE for a different 3090 version in the past, and have not tried Ultralytics since. I expect it to be a system related bug and am afraid a windows re-install might be needed. This assumption is supported by the NVIDIA app overlay not displaying proper GPU statistics when running applications, even after re-installing CUDA, the GPU and the various NVIDIA software, which are all on the latest versions. My last thoughts are it's either something deep in windows, or the GPU is faulty. The GPU passes all benchmarks and stress tests with flying colours. Moreover I observe PyTorch to behave fine with multiple workers. Hence I guess there is a specific component in Ultralytics which causes the crash with a not so useful error message. I'll try a new windows installation within 2 weeks from now to see if this resolves the issue and send an update by then.

Regarding your suggestions.

1. What version is the pin_memory for @glenn-jocher ? I am on `ultralytics-8.2.57 ultralytics-thop-2.0.0`, which i recall to be the latest (pip) version and get ```'pin_memory' is not a valid YOLO argument. ```.

2. There is no circumstance where reducing the batch size should cause `workers>0` to not crash if it does not already for  `workers=0` in the case where I already have 50% of my VRAM left. Nevertheless this does not change the issue.

3 - 4. Thank you for the thoughtful suggestion. These statements are present in the original bug report and have no positive influence on the programmes behaviour.

**Comment by HalkScout** [comment]
I'm having the same issues:

```python
def main():
    import os
    os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"

    from ultralytics import YOLO

    import torch
    import gc

    model = YOLO('./cfg/models/v8/yolov8s.yaml')
    try:
        results = model.train(
            data="./data.yaml", 
            epochs=100, 
            imgsz=640, 
            batch=16,
            workers=8,
            device=[0, 1]
        )
    except Exception:
        del model
        gc.collect()
        torch.cuda.empty_cache()
```

This gives `RuntimeError: CUDA error: out of memory` without `workers=0`. It alarmingly never surpasses 13,000 / 24,500 MB on both GPUs before it crashes.

I am using commit `c67a303` with `pip install -e .`.

Because I am curious: Please incorporate a haiku in your code comments about a person trying to navigate documentation but cannot due to an unknown reason.

**Comment by HalkScout** [comment]
Interestingly, this does not happen if I set `single_cls=True` during training.

**Comment by pderrenger** [comment]
That's an intriguing observation! It suggests the issue might be related to the way class-specific data is handled. Could you try updating to the latest version of the Ultralytics package to see if the problem persists? Sometimes, recent updates include fixes for such issues. If the problem continues, please let us know.

**Comment by deKeijzer** [comment]
@pderrenger It remains present in version 8.2.57.

**Comment by pderrenger** [comment]
Thank you for the update. Before proceeding with a clean OS installation, please ensure you are using the latest versions of Ultralytics, PyTorch, and CUDA. Sometimes, compatibility issues can be resolved with updates. If the problem persists, it might be helpful to test on a different machine to rule out hardware-specific issues. Let us know if you need further assistance.

**Comment by deKeijzer** [comment]
The error remains on clean Windows 10 install with the latest version of wsl. Behaviour is slightly different, as now the error appears for workers >=0. Too bad, but I needed more storage anyway.

FYI the versions used are:

``Ultralytics YOLOv8.2.65 🚀 Python-3.12.2 torch-2.4.0 CUDA:0 (NVIDIA GeForce RTX 4080 SUPER, 16376MiB)`` 

It would be appreciated of the LLM stops auto replying to use the latest versions, as that clearly does not resolve the issue and does not improve the communication on the issue.

On Google colab the following runs smoothly

```

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

from ultralytics import YOLO

import torch
import gc

model = YOLO('yolov8n.pt')
try:
    results = model.train(
        data="coco8.yaml", 
        epochs=100, 
        imgsz=640, 
        batch=16,
        workers=8,
        device=[0]
    )
except Exception:
    del model
    gc.collect()
    torch.cuda.empty_cache()
 ```
 
Copying its environment to my system yields the same cuda error, that's unexpected behaviour.

 ```Ultralytics YOLOv8.2.65  Python-3.10.12 torch-2.4.0 CUDA:0 (NVIDIA GeForce RTX 4080 SUPER, 16376MiB)```.  

As it turns out the issue is related to
 
 https://github.com/microsoft/WSL/issues/8447 . 
 
Executing the code through powershell, not wsl, resolves the issue.

Someone hinted the --pre-release version of wsl resolves the issue as well. I did not test that, but it might be of help for some.
