### ISSUE TITLE
yolo v8 training not starting with DDP

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#15683]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

Training starts correctly with 1 GPU. With 2 to 10 GPU's (DDP) training appears to stall after Freezing layer...

1 GPU, normal operation
```
Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
train: Scanning /all/yolo/labels/train.cache... 7386 images, 0 backgrounds, 0 corrupt: 100%|██████████| 7386/7386 [00:00<?, ?it/s]
val: Scanning /all/yolo/labels/val.cache... 921 images, 0 backgrounds, 0 corrupt: 100%|██████████| 921/921 [00:00<?, ?it/s]
Plotting labels to /all/yolo_output/all_20240819/labels.jpg...

```

> 1 GPU, no output on screen after Freezing layer
```
Transferred 319/355 items from pretrained weights
DDP: debug command /home/test/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 58649 /home/test/.config/Ultralytics/DDP/_temp_zpgk844x138581078171936.py
Ultralytics YOLOv8.2.78 🚀 Python-3.12.3 torch-2.3.1+cu121 CUDA:0 (NVIDIA L40S, 45596MiB)
                                                           CUDA:1 (NVIDIA L40S, 45596MiB)
Overriding model.yaml nc=80 with nc=4000
Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'

```

Older versions appear to work / start ok

### Environment

Ultralytics YOLOv8.2.78 🚀 Python-3.12.3 torch-2.3.1+cu121 CUDA:0 (NVIDIA L40S, 45596MiB)
Setup complete ✅ (256 CPUs, 2015.5 GB RAM, 386.3/7095.4 GB disk)

OS                  Linux-6.8.0-40-generic-x86_64-with-glibc2.39
Environment         Linux
Python              3.12.3
Install             pip
RAM                 2015.50 GB
CPU                 AMD EPYC 9754 128-Core Processor
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

yolo model.cfg

### Additional

This issue was noticed in the last few versions > 8.2.70

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by apiszcz** [comment]
updated all packages on system, restarted.
Working normally with DDP and 10GPU's

**Comment by glenn-jocher** [comment]
@apiszcz great to hear that updating the packages resolved the issue! If you encounter any further problems, feel free to reach out. Happy training!

**Comment by apiszcz** [comment]
Attempted same session that operated properly on 8/19/2024 this morning and same behavior,
Output freezes at Freezing layer 'model.22.dfl.conv.weight'
Please let me know what type of log file ore other information is needed to diagnose this.

**Comment by glenn-jocher** [comment]
Thank you for the detailed information. To diagnose the issue, please ensure you are using the latest version of the Ultralytics package. If the problem persists, could you provide the training logs and any error messages from the stalled sessions? This will help us investigate further.

**Comment by apiszcz** [comment]
Hi!, after a while a stack trace is emitted.

```

Overriding model.yaml nc=80 with nc=4000
Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
[rank7]:[E ProcessGroupNCCL.cpp:563] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800004 milliseconds before
timing out.
[rank6]:[E ProcessGroupNCCL.cpp:563] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800005 milliseconds before
timing out.
[rank5]:[E ProcessGroupNCCL.cpp:563] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800005 milliseconds before
timing out.
[rank1]:[E ProcessGroupNCCL.cpp:563] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800005 milliseconds before
timing out.
[rank3]:[E ProcessGroupNCCL.cpp:563] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800004 milliseconds before
timing out.
[rank9]:[E ProcessGroupNCCL.cpp:563] [Rank 9] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800005 milliseconds before
timing out.
[rank1]:[E ProcessGroupNCCL.cpp:626] [Rank 1] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank7]:[E ProcessGroupNCCL.cpp:626] [Rank 7] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank3]:[E ProcessGroupNCCL.cpp:626] [Rank 3] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank5]:[E ProcessGroupNCCL.cpp:626] [Rank 5] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank6]:[E ProcessGroupNCCL.cpp:626] [Rank 6] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank9]:[E ProcessGroupNCCL.cpp:626] [Rank 9] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank4]:[E ProcessGroupNCCL.cpp:563] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800009 milliseconds before
timing out.
[rank8]:[E ProcessGroupNCCL.cpp:563] [Rank 8] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800008 milliseconds before
timing out.
[rank2]:[E ProcessGroupNCCL.cpp:563] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800009 milliseconds before
timing out.
[rank4]:[E ProcessGroupNCCL.cpp:626] [Rank 4] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank8]:[E ProcessGroupNCCL.cpp:626] [Rank 8] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank2]:[E ProcessGroupNCCL.cpp:626] [Rank 2] Work WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank0]:[E ProcessGroupNCCL.cpp:563] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLGATHER, NumelIn=1, NumelOut=10, Timeout(ms)=10800000) ran for 10800005 milliseconds before
 timing out.
[rank0]:[E ProcessGroupNCCL.cpp:626] [Rank 0] Work WorkNCCL(SeqNum=2, OpType=ALLGATHER, NumelIn=1, NumelOut=10, Timeout(ms)=10800000) timed out in blocking wait (TORCH_NCCL_BLOCKING_WAIT=1).
[rank9]:[E ProcessGroupNCCL.cpp:577] [Rank 9] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank9]:[E ProcessGroupNCCL.cpp:583] [Rank 9] To avoid data inconsistency, we are taking the entire process down.
[rank6]:[E ProcessGroupNCCL.cpp:577] [Rank 6] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank6]:[E ProcessGroupNCCL.cpp:583] [Rank 6] To avoid data inconsistency, we are taking the entire process down.
[rank4]:[E ProcessGroupNCCL.cpp:577] [Rank 4] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank4]:[E ProcessGroupNCCL.cpp:583] [Rank 4] To avoid data inconsistency, we are taking the entire process down.
[rank9]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 9] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: 1554246621.
[rank9]:[E ProcessGroupNCCL.cpp:577] [Rank 9] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank6]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 6] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: 1147907655.
[rank6]:[E ProcessGroupNCCL.cpp:577] [Rank 6] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank8]:[E ProcessGroupNCCL.cpp:577] [Rank 8] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank8]:[E ProcessGroupNCCL.cpp:583] [Rank 8] To avoid data inconsistency, we are taking the entire process down.
[rank4]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 4] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: 1114435412.
[rank4]:[E ProcessGroupNCCL.cpp:577] [Rank 4] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank8]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 8] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: 788264198.
[rank8]:[E ProcessGroupNCCL.cpp:577] [Rank 8] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank7]:[E ProcessGroupNCCL.cpp:577] [Rank 7] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank7]:[E ProcessGroupNCCL.cpp:583] [Rank 7] To avoid data inconsistency, we are taking the entire process down.
[rank5]:[E ProcessGroupNCCL.cpp:577] [Rank 5] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank5]:[E ProcessGroupNCCL.cpp:583] [Rank 5] To avoid data inconsistency, we are taking the entire process down.
[rank7]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 7] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: 771170517.
[rank7]:[E ProcessGroupNCCL.cpp:577] [Rank 7] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank6]: Traceback (most recent call last):
[rank6]:   File "/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py", line 13, in <module>
[rank6]:     results = trainer.train()
[rank6]:               ^^^^^^^^^^^^^^^
[rank6]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank6]:     self._do_train(world_size)
[rank6]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank6]:     self._setup_train(world_size)
[rank6]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 269, in _setup_train
[rank6]:     dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
[rank6]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/test/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank6]:     return func(*args, **kwargs)
[rank6]:            ^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/test/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
[rank6]:     work.wait()
[rank6]: torch.distributed.DistBackendError: [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800005 milliseconds
 before timing out.
[rank9]: Traceback (most recent call last):
[rank9]:   File "/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py", line 13, in <module>
[rank9]:     results = trainer.train()
[rank9]:               ^^^^^^^^^^^^^^^
[rank9]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank9]:     self._do_train(world_size)
[rank9]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank9]:     self._setup_train(world_size)
[rank9]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 269, in _setup_train
[rank9]:     dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
[rank9]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank9]:   File "/test/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank9]:     return func(*args, **kwargs)
[rank9]:            ^^^^^^^^^^^^^^^^^^^^^
[rank9]:   File "/test/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
[rank9]:     work.wait()
[rank9]: torch.distributed.DistBackendError: [Rank 9] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800005 milliseconds
 before timing out.
[rank7]: Traceback (most recent call last):
[rank7]:   File "/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py", line 13, in <module>
[rank7]:     results = trainer.train()
[rank7]:               ^^^^^^^^^^^^^^^
[rank7]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank7]:     self._do_train(world_size)
[rank7]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank7]:     self._setup_train(world_size)
[rank7]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 269, in _setup_train
[rank7]:     dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
[rank7]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/test/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank7]:     return func(*args, **kwargs)
[rank7]:            ^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/test/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
[rank7]:     work.wait()
[rank7]: torch.distributed.DistBackendError: [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800004 milliseconds
 before timing out.
[rank5]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 5] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: 1395908454.
[rank5]:[E ProcessGroupNCCL.cpp:577] [Rank 5] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]:[E ProcessGroupNCCL.cpp:577] [Rank 3] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]:[E ProcessGroupNCCL.cpp:583] [Rank 3] To avoid data inconsistency, we are taking the entire process down.
[rank4]: Traceback (most recent call last):
[rank4]:   File "/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py", line 13, in <module>
[rank4]:     results = trainer.train()
[rank4]:               ^^^^^^^^^^^^^^^
[rank4]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank4]:     self._do_train(world_size)
[rank4]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank4]:     self._setup_train(world_size)
[rank4]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 269, in _setup_train
[rank4]:     dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
[rank4]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/test/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank4]:     return func(*args, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/test/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
[rank4]:     work.wait()
[rank4]: torch.distributed.DistBackendError: [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800009 milliseconds
 before timing out.
[rank5]: Traceback (most recent call last):
[rank5]:   File "/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py", line 13, in <module>
[rank5]:     results = trainer.train()
[rank5]:               ^^^^^^^^^^^^^^^
[rank5]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank5]:               ^^^^^^^^^^^^^^^                                                                                                                                                          11:13:09 [204/1707]
[rank5]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank5]:     self._do_train(world_size)
[rank5]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank5]:     self._setup_train(world_size)
[rank5]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 269, in _setup_train
[rank5]:     dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
[rank5]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/test/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank5]:     return func(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/test/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
[rank5]:     work.wait()
[rank5]: torch.distributed.DistBackendError: [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800005 milliseconds
 before timing out.
[rank8]: Traceback (most recent call last):
[rank8]:   File "/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py", line 13, in <module>
[rank8]:     results = trainer.train()
[rank8]:               ^^^^^^^^^^^^^^^
[rank8]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank8]:     self._do_train(world_size)
[rank8]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank8]:     self._setup_train(world_size)
[rank8]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 269, in _setup_train
[rank8]:     dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
[rank8]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank8]:   File "/test/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank8]:     return func(*args, **kwargs)
[rank8]:            ^^^^^^^^^^^^^^^^^^^^^
[rank8]:   File "/test/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
[rank8]:     work.wait()
[rank8]: torch.distributed.DistBackendError: [Rank 8] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800008 milliseconds
 before timing out.
[rank2]:[E ProcessGroupNCCL.cpp:577] [Rank 2] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank2]:[E ProcessGroupNCCL.cpp:583] [Rank 2] To avoid data inconsistency, we are taking the entire process down.
[rank3]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 3] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: 910344404.
[rank3]:[E ProcessGroupNCCL.cpp:577] [Rank 3] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank2]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 2] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: 374261579.
[rank2]:[E ProcessGroupNCCL.cpp:577] [Rank 2] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py", line 13, in <module>
[rank3]:     results = trainer.train()
[rank3]:               ^^^^^^^^^^^^^^^
[rank3]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank3]:     self._do_train(world_size)
[rank3]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank3]:     self._setup_train(world_size)
[rank3]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 269, in _setup_train
[rank3]:     dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
[rank3]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/test/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank3]:     return func(*args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/test/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                       11:13:09 [152/1707]
[rank3]:   File "/test/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
[rank3]:     work.wait()
[rank3]: torch.distributed.DistBackendError: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800004 milliseconds
 before timing out.
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py", line 13, in <module>
[rank2]:     results = trainer.train()
[rank2]:               ^^^^^^^^^^^^^^^
[rank2]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank2]:     self._do_train(world_size)
[rank2]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank2]:     self._setup_train(world_size)
[rank2]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 269, in _setup_train
[rank2]:     dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
[rank2]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/test/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank2]:     return func(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/test/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
[rank2]:     work.wait()
[rank2]: torch.distributed.DistBackendError: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800009 milliseconds
 before timing out.
[rank1]:[E ProcessGroupNCCL.cpp:577] [Rank 1] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank1]:[E ProcessGroupNCCL.cpp:583] [Rank 1] To avoid data inconsistency, we are taking the entire process down.
[rank1]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 1] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: 1429004818.
[rank1]:[E ProcessGroupNCCL.cpp:577] [Rank 1] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py", line 13, in <module>
[rank1]:     results = trainer.train()
[rank1]:               ^^^^^^^^^^^^^^^
[rank1]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank1]:     self._do_train(world_size)
[rank1]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank1]:     self._setup_train(world_size)
[rank1]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 269, in _setup_train
[rank1]:     dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
[rank1]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/test/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/test/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
[rank1]:     work.wait()
[rank1]: torch.distributed.DistBackendError: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1, NumelOut=1, Timeout(ms)=10800000) ran for 10800005 milliseconds
 before timing out.
[rank0]:[E ProcessGroupNCCL.cpp:577] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank0]:[E ProcessGroupNCCL.cpp:583] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
[rank0]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 0] Timeout at NCCL work: 2, last enqueued NCCL work: 2, last completed NCCL work: 1.
[rank0]:[E ProcessGroupNCCL.cpp:577] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py", line 13, in <module>
[rank0]:     results = trainer.train()
[rank0]:               ^^^^^^^^^^^^^^^
[rank0]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank0]:               ^^^^^^^^^^^^^^^                                                                                                                                                          11:13:10 [100/1707]
[rank0]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 208, in train
[rank0]:     self._do_train(world_size)
[rank0]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank0]:     self._setup_train(world_size)
[rank0]:   File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 273, in _setup_train
[rank0]:     self.model = nn.parallel.DistributedDataParallel(self.model, device_ids=[RANK], find_unused_parameters=True)
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/test/lib/python3.12/site-packages/torch/nn/parallel/distributed.py", line 798, in __init__
[rank0]:     _verify_param_shape_across_processes(self.process_group, parameters)
[rank0]:   File "/test/lib/python3.12/site-packages/torch/distributed/utils.py", line 269, in _verify_param_shape_across_processes
[rank0]:     return dist._verify_params_across_processes(process_group, tensors, logger)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.distributed.DistBackendError: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLGATHER, NumelIn=1, NumelOut=10, Timeout(ms)=10800000) ran for 10800005 millisecond
s before timing out.
W0820 11:13:10.538000 131603968713024 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 66545 closing signal SIGTERM
W0820 11:13:10.538000 131603968713024 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 66547 closing signal SIGTERM
W0820 11:13:10.539000 131603968713024 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 66548 closing signal SIGTERM
W0820 11:13:10.539000 131603968713024 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 66549 closing signal SIGTERM
W0820 11:13:10.539000 131603968713024 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 66550 closing signal SIGTERM
W0820 11:13:10.539000 131603968713024 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 66552 closing signal SIGTERM
W0820 11:13:10.539000 131603968713024 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 66553 closing signal SIGTERM
E0820 11:13:10.970000 131603968713024 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 66544) of binary: /test/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/test/lib/python3.12/site-packages/torch/distributed/run.py", line 883, in <module>
    main()
  File "/test/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/test/lib/python3.12/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/test/lib/python3.12/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/test/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/test/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/atestuser/.config/Ultralytics/DDP/_temp_11sf89us140392200661056.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-20_11:13:10
  host      : testhost
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 66546)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-20_11:13:10
[2]:                                                                                                                                                                                             17:17:51 [48/1707]
  time      : 2024-08-20_11:13:10
  host      : testhost
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 66551)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-20_11:13:10
  host      : testhost
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 66544)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/test/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/test/lib/python3.12/site-packages/ultralytics/cfg/__init__.py", line 834, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/test/lib/python3.12/site-packages/ultralytics/engine/model.py", line 812, in train
    self.trainer.train()
  File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 203, in train
    raise e
  File "/test/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 201, in train
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/test/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '10', '--master_port', '32823', '/home/atestuser/.config/Ultralytics/DDP/_temp_11sf8
9us140392200661056.py']' returned non-zero exit status 1.





















```

**Comment by glenn-jocher** [comment]
@apiszcz it looks like the issue is related to a timeout in the NCCL communication during the DDP setup. Please ensure you are using the latest version of the Ultralytics package. If the problem persists, try setting the environment variable `NCCL_DEBUG=INFO` to get more detailed logs and help diagnose the issue.

**Comment by apiszcz** [comment]
https://github.com/Lightning-AI/pytorch-lightning/issues/3117
https://github.com/Lightning-AI/pytorch-lightning/pull/3819

This may fix the issue
export NCCL_P2P_DISABLE=1

Tested 5 starts in a row with 10GPU's no issues.

Wow.

https://lightning.ai/forums/t/training-freezes-at-initializing-ddp-global-rank/3057
[LuisVMoura](https://lightning.ai/forums/u/LuisVMoura)
[Jun 2023](https://lightning.ai/forums/t/training-freezes-at-initializing-ddp-global-rank/3057/2)
Hey man, I have the same issue some time ago. But in my case i was working with 6 RTX A6000 in a SuperMicro server. The issue was related to the way the GPUs intercomunicates.

I solve the problem setting NCCL_P2P_DISABLE as 1, using the following:

export NCCL_P2P_DISABLE=1

and then runing the .py file in the cmd.

In my understand, the GPUs try to communicate by the NVlink (witch i dont have) so They just stop in the process trying to do that, and the Only way to end this is to kill the process.

I hope this help you, good luck.

**Comment by glenn-jocher** [comment]
Thank you for sharing this potential solution. Please try setting `export NCCL_P2P_DISABLE=1` and see if it resolves the issue. If the problem persists, ensure you are using the latest version of the Ultralytics package.

**Comment by glenn-jocher** [comment]
@apiszcz great to hear that the issue has been resolved. Thank you for sharing the additional information on P2P modes. If you encounter any further issues, feel free to reopen the issue or start a new one. Happy training!
