### ISSUE TITLE
How to use GPU for prediction?

### ISSUE THREAD

**Issue by mriamnobody** [ultralytics/ultralytics#1619]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**

> The command I'm using for prediction is `yolo predict model=yolov8n.pt --source="rtsp://username:password@IP:PORT/cam/realmonitor?channel=1&subtype=0"`

**

I have conducted a search and reviewed related issues, but this particular issue is different. The output of the command `torch.cuda.is_available()` returns `False`. I tried installing the torch+cu package with filename `torch-1.12.0+cu113-cp310-cp310-win_amd64.whl`. At the end of the successful installation of the torch+cu package, the following error is displayed:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.1 requires torch==2.0.0, but you have torch 1.12.0+cu113 which is incompatible.
```
When I run  the command for prediction after installing the torch+cu I'm getting the following errors:

First these two:

![Screenshot (2227)](https://user-images.githubusercontent.com/14347205/227716029-1254730d-3827-47db-b140-34a4ac4de3c2.png)

![Screenshot (2228)](https://user-images.githubusercontent.com/14347205/227716035-8cbf267f-caa0-4673-9473-8984a5a95b2b.png)

And later this:
```
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\trying.py", line 8, in <module>
    model.train(data="coco128.yaml", epochs=3)  # train the model
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\model.py", line 327, in train
    self.trainer.train()
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 186, in train
    self._do_train(RANK, world_size)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 263, in _do_train
    self._setup_train(rank, world_size)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 209, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 643, in check_amp
    assert amp_allclose(YOLO('yolov8n.pt'), im)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 631, in amp_allclose
    a = m(im, device=device, verbose=False)[0].boxes.boxes  # FP32 inference
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\model.py", line 99, in __call__
    return self.predict(source, stream, **kwargs)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\model.py", line 228, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\predictor.py", line 114, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\predictor.py", line 176, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\v8\detect\predict.py", line 23, in postprocess
    preds = ops.non_max_suppression(preds,
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\utils\ops.py", line 245, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\torchvision\ops\boxes.py", line 40, in nms
    _assert_has_ops()
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\torchvision\extension.py", line 48, in _assert_has_ops
    raise RuntimeError(
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
```
Before installing the torch+cu the prediction command worked fine but was consuming 72% of CPU and there was no load on GPU.

**Comment by glenn-jocher** [comment]
@mriamnobody see See https://docs.ultralytics.com/quickstart/ or if you are having local environment issues try one of the environments below:

## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

**Comment by mriamnobody** [comment]
Thanks for the clarification @glenn-jocher. The link you provided does not contain any information related to the usage of torch+cu or the issues encountered during its installation.

**Comment by glenn-jocher** [comment]
@mriamnobody ah yes, you are correct, the above links are for already-existing environments that have torch previously installed. For information on installing torch in a new environment please see https://pytorch.org/get-started/locally/

**Comment by mriamnobody** [comment]
@glenn-jocher. I first uninstalled `torch=2.0.0` and `torchvision=0.15.1`, then installed `torch=2.0.0` and `torchaudio=2.0.1` with CUDA support using the command: `pip3 install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu117`. The installation was successful, and when I executed my script, the GPU initially processed the training load. However, the script ultimately crashed and displayed the following error:
```

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.Detect                [80, [64, 128, 256]]
YOLOv8n summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

Ultralytics YOLOv8.0.57  Python-3.10.7 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24575MiB)
yolo\engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=coco128.yaml, epochs=3, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs\detect\train3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.Detect                [80, [64, 128, 256]]
Model summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

Transferred 355/355 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\fileee.py", line 19, in <module>
    model.train(data="coco128.yaml", epochs=3)  # train the model
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\model.py", line 327, in train
    self.trainer.train()
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 186, in train
    self._do_train(RANK, world_size)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 263, in _do_train
    self._setup_train(rank, world_size)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 209, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 643, in check_amp
    assert amp_allclose(YOLO('yolov8n.pt'), im)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 631, in amp_allclose
    a = m(im, device=device, verbose=False)[0].boxes.boxes  # FP32 inference
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\model.py", line 99, in __call__
    return self.predict(source, stream, **kwargs)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\yolov8\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\model.py", line 228, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\predictor.py", line 114, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\yolov8\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\predictor.py", line 176, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\v8\detect\predict.py", line 23, in postprocess
    preds = ops.non_max_suppression(preds,
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\utils\ops.py", line 245, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\yolov8\lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\yolov8\lib\site-packages\torch\_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

CPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
QuantizedCPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:144 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:491 [backend fallback]
Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:280 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:63 [backend fallback]
AutogradOther: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:30 [backend fallback]
AutogradCPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:34 [backend fallback]
AutogradCUDA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:42 [backend fallback]
AutogradXLA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:46 [backend fallback]
AutogradMPS: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:54 [backend fallback]
AutogradXPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:38 [backend fallback]
AutogradHPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:67 [backend fallback]
AutogradLazy: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:50 [backend fallback]
AutogradMeta: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:58 [backend fallback]
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:294 [backend fallback]
AutocastCPU: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:487 [backend fallback]
AutocastCUDA: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:354 [backend fallback]
FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:815 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1073 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:210 [backend fallback]
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:152 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:487 [backend fallback]
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:148 [backend fallback]
```
I think I'm definitely missing something here.

**Comment by mriamnobody** [comment]
I apologize for my earlier mistake. I had forgotten to remove the `torchvision` package that was installed using the requirements.txt file. After uninstalling `torchvision` and installing the CUDA-supported package, the error has changed. Here is the new error message I am encountering:

```
                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.Detect                [80, [64, 128, 256]]
YOLOv8n summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

Ultralytics YOLOv8.0.57  Python-3.10.7 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24575MiB)
yolo\engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=coco128.yaml, epochs=3, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs\detect\train6

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.Detect                [80, [64, 128, 256]]
Model summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

Transferred 355/355 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias
train: Scanning C:\Users\rosha\Downloads\Compressed\ultralytics-main\datasets\coco128\labels\train2017.cache... 126 ima
val: Scanning C:\Users\rosha\Downloads\Compressed\ultralytics-main\datasets\coco128\labels\train2017.cache... 126 image
Plotting labels to runs\detect\train6\labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\detect\train6
Starting training for 3 epochs...

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.Detect                [80, [64, 128, 256]]
YOLOv8n summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

Ultralytics YOLOv8.0.57  Python-3.10.7 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24575MiB)
yolo\engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=coco128.yaml, epochs=3, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs\detect\train7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.Detect                [80, [64, 128, 256]]
Model summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

Transferred 355/355 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias
train: Scanning C:\Users\rosha\Downloads\Compressed\ultralytics-main\datasets\coco128\labels\train2017.cache... 126 ima
val: Scanning C:\Users\rosha\Downloads\Compressed\ultralytics-main\datasets\coco128\labels\train2017.cache... 126 image
Plotting labels to runs\detect\train7\labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\detect\train7
Starting training for 3 epochs...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\fileee.py", line 19, in <module>
    model.train(data="coco128.yaml", epochs=3)  # train the model
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\model.py", line 327, in train
    self.trainer.train()
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 186, in train
    self._do_train(RANK, world_size)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 285, in _do_train
    pbar = enumerate(self.train_loader)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\yolov8\lib\site-packages\torch\utils\data\dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\yolov8\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\yolov8\lib\site-packages\torch\utils\data\dataloader.py", line 1043, in __init__
    w.start()
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

**Comment by mriamnobody** [comment]
Indeed, this tool is excellent; however, there is room for improvement in the documentation. Enhancing the clarity and completeness of the documentation would undoubtedly benefit users and facilitate a better understanding of the tool's functionality.

**Comment by mriamnobody** [comment]
I forgot to mention a crucial detail: I deleted the Ultralytics folder, set up a virtual environment (venv), and executed all the commands within this venv.

**Comment by mriamnobody** [comment]
@glenn-jocher @AyushExel @plashchynski @onuralpszr @Laughing-q

**Comment by mriamnobody** [comment]
I solved the issue in https://github.com/ultralytics/ultralytics/issues/1619#issuecomment-1484157791 by using the below code.

```
from ultralytics import YOLO

def main():
      model = YOLO("yolov8n.yaml")
      model = YOLO("yolov8n.pt")

      model.train(data="coco128.yaml", epochs=3)

      metrics = model.val()

      results = model("rtsp://USERNAME:Password@IP:PORT/cam/realmonitor?channel=1&subtype=0",save=True)

      success = model.export(format="onnx")

      return results,metrics,success

if __name__ == '__main__':
    results,metrics,success = main()
```

It was happening due to a multithreading issue.

**Comment by mriamnobody** [comment]
From what I have learned and found to be working if you want to use CUDA variants of `torch` family you will first need to uninstall all the `torch` frameworks (`torch`, `torchvision` and also `torchaudio` if it is installed ) that were installed through `requirements.txt`. Removal of existing `torch` packages is important as they all are `CPU` variants. Then use the following command to install the CUDA variants `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`. If you want to install previous versions you can head to `https://pytorch.org/get-started/locally/` as mentioned by @glenn-jocher.

**Comment by AyushExel** [comment]
> Indeed, this tool is excellent; however, there is room for improvement in the documentation. Enhancing the clarity and completeness of the documentation would undoubtedly benefit users and facilitate a better understanding of the tool's functionality.

This is great feedback! Can you also describe the top 3 or so additions in docs that would make it better for you?

**Comment by mriamnobody** [comment]
Yes, I appreciate the opportunity to provide further feedback! Here are my top 3 suggestions for improving the documentation:

1. **More Examples:** It would be highly beneficial to include additional examples, particularly for beginners. Demonstrating how to use various sources, such as camera streams, would make the documentation more accessible and easier to understand for those just starting out.

2. **CUDA Installation Guide:** A step-by-step guide on how to install CUDA-based `torch` libraries would be a valuable addition. This could help users optimize their setup for GPU acceleration and improve overall performance.

3. **Troubleshooting Section:** Finally, including a comprehensive troubleshooting section could save users time and frustration. This section could cover common issues, their solutions, and tips for avoiding pitfalls, ensuring a smoother experience for all.

I hope these suggestions help improve the documentation and make it even more user-friendly. Thank you @AyushExel for considering my feedback!

**Comment by AyushExel** [comment]
@mriamnobody yes agreed. I'll try to write a FAQs section that can be used for both troubleshooting and a guide. I think the CUDA installation issues are isolated to Windows environments. If there are any other feedbacks, do let us know

**Comment by mriamnobody** [comment]
In the examples section, please consider incorporating scenarios where multiple camera streams serve as sources, if feasible. Additionally, kindly offer a comprehensive guide on implementing this feature. One of the prime use cases of this exceptional tool is for human or object detection utilizing IP cameras.

**Comment by MathewsJosh** [comment]
> > Indeed, this tool is excellent; however, there is room for improvement in the documentation. Enhancing the clarity and completeness of the documentation would undoubtedly benefit users and facilitate a better understanding of the tool's functionality.
> 
> This is great feedback! Can you also describe the top 3 or so additions in docs that would make it better for you?

Hi AyushExel, I know that this issue is not quite related to my suggestion. But I think it would be important to have in the documentation the following explanations for each task:

• Which epoch corresponds to the best weight (best.pt)? For example, is it the metric with best Precision, Recall or mAP?

• Are the automatically generated graphs (precision, recall, f1-score, confusion matrix, ...) at the end of training based on "best.pt", "last.pt" or another weigths/epochs?

Thanks!

**Comment by glenn-jocher** [comment]
@MathewsJosh hi! Thank you for sharing your feedback on the documentation of YOLOv8. Regarding your specific questions, we agree that it would be valuable to have this information documented. After training, the best weights (`best.pt`) are typically chosen based on the highest mean Average Precision (mAP) metric achieved during the validation process. As for the automatically generated graphs, these are usually based on the validation set and calculated at the end of each epoch during training. At the end of training, these graphs can be generated based on the weights of the last epoch or the best epoch, both of which should be documented in the user guide. We appreciate your input and are continually striving to improve the documentation to better serve our users.

**Comment by MathewsJosh** [comment]
> @MathewsJosh hi! Thank you for sharing your feedback on the documentation of YOLOv8. Regarding your specific questions, we agree that it would be valuable to have this information documented. After training, the best weights (`best.pt`) are typically chosen based on the highest mean Average Precision (mAP) metric achieved during the validation process. As for the automatically generated graphs, these are usually based on the validation set and calculated at the end of each epoch during training. At the end of training, these graphs can be generated based on the weights of the last epoch or the best epoch, both of which should be documented in the user guide. We appreciate your input and are continually striving to improve the documentation to better serve our users.

Hi @glenn-jocher, thanks for your quick response. I am glad to be able to help you improve this awesome tool even more.

As for your answers, I still have two questions.

1 - Are you referring to mAP@0.5 or to mAP@0.5-0.95? Or a mixture of both?

2 - What has been the default value in the source code for generating these graphs from the weights (best.pt or last.pt)? I ask this because I have some training from months ago and I am failing to identify which of these two weights my graphs belong to.

**Comment by glenn-jocher** [comment]
Hi @MathewsJosh, thank you for following up with your questions. To answer your first question, the best weights (`best.pt`) are typically chosen based on the highest mean Average Precision (mAP) achieved across all IoU thresholds (i.e., 0.5 to 0.95). 

As for your second question, the default behavior for generating the validation graphs is to produce them based on the weights of the last epoch rather than the weights of the best epoch. This behavior may vary depending on the source code and version you are using, so you may want to double-check your code to confirm which weights generated the graphs in your training from months ago. We hope this information is helpful, and we appreciate your feedback for helping us improve the documentation of YOLOv8.
