### ISSUE TITLE
OOM when using DDP inference YOLOV8

### ISSUE THREAD

**Issue by hutIngk** [ultralytics/ultralytics#19699]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/orgs/ultralytics/discussions) and found no similar questions.

### Question

Hi, I've seen other people having the similar problem but the solutions didn't work for me 

i am trying to using DDP to inference on my datset, which contain 640 images, but it occurs this error。
my GPU is 2 NVIDIA 3090 24G，it is not supposed to occur OOM
```
2025-03-14 18:44:28.305 | ERROR    | __mp_main__:run_v8:58 - Error in process 0: CUDA out of memory. Tried to allocate 9.77 GiB. GPU 0 has a total capacty of 23.69 GiB of which 2.10 GiB is free. Process 73168 has 21.58 GiB memory in use. Of the allocated memory 15.34 GiB is allocated by PyTorch, and 5.89 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2025-03-14 18:44:28.927 | ERROR    | __mp_main__:run_v8:58 - Error in process 1: CUDA out of memory. Tried to allocate 9.77 GiB. GPU 1 has a total capacty of 23.69 GiB of which 2.10 GiB is free. Process 73169 has 21.58 GiB memory in use. Of the allocated memory 15.34 GiB is allocated by PyTorch, and 5.89 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
**here is my code：**
```
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
'''
@Project ：yolov5 
@Author  ：htk
@Date    ：2025/1/10 19:31 
'''
import torch.distributed as dist
from ultralytics import YOLO
import time
import os
from loguru import logger
import torch
import torch.multiprocessing as mp

def run_v8(local_rank, path, model_path, batch_size=32, half=False, world_size=2):
    try:
        os.environ['RANK'] = str(local_rank)
        
        dist.init_process_group(backend='nccl', init_method='env://')
        torch.cuda.set_device(local_rank)
        device = torch.device(f'cuda:{local_rank}')

        model = YOLO(model_path) 
        model = model.to(device)

        img_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith(('.jpg', '.png', '.jpeg'))]
        num_imgs = len(img_files)

        imgs_per_process = num_imgs // world_size
        start_idx = local_rank * imgs_per_process
        end_idx = start_idx + imgs_per_process if local_rank != world_size - 1 else num_imgs
        local_img_files = img_files[start_idx:end_idx]

        dummy_input = torch.zeros(1, 3, 640, 640).to(device) 
        if half:
            dummy_input = dummy_input.half()
        _ = model(dummy_input, verbose=False)

        torch.cuda.empty_cache()
        t1 = time.time()
        results = model(local_img_files, batch=batch_size, verbose=False, device=device, half=half, imgsz=640)  # 推理
        inference_time = time.time() - t1

        if local_rank == 0:
            logger.info(f'batch size {batch_size} infer {num_imgs} images -- half:{half}, cost time: {inference_time:.2f}s')

    except Exception as e:
        logger.error(f"Error in process {local_rank}: {e}")


if __name__ == '__main__':
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'
    os.environ['WORLD_SIZE'] = '2'  # 使用 2 个 GPU

    path = r'/root/data1/datasets/xxx'
    model_path = r'yolov8l.pt'

    mp.spawn(run_v8, args=(path, model_path), nprocs=2, join=True)
```

i have tried the `torch.cuda.empty_cache()`  and `with torch.no_grad`, it is still not work for me
PLZ check this out for me, thanks man!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @hutIngk, thank you for your interest in Ultralytics 🚀! We appreciate you sharing your detailed code and setup for debugging.

From your description, it seems you're encountering a 🐛 CUDA out-of-memory (OOM) issue while running inference using Distributed Data Parallel (DDP). To help us investigate, could you please provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum-reproducible-example/)? This will allow us to better understand and debug the issue.

In the meantime, here's a checklist to ensure your setup is optimized:
1. **Upgrade**: Ensure you're using the latest version of the `ultralytics` package. You can upgrade with:
   ```bash
   pip install -U ultralytics
   ```
2. **Environment**: Verify your environment is configured correctly with all dependencies, including [PyTorch](https://pytorch.org/) and [CUDA](https://developer.nvidia.com/cuda-zone). YOLO works well in the following environments:
   - **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
   - **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
   - **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
   - **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

For further assistance, check our [Docs](https://docs.ultralytics.com/), particularly the [Python Usage](https://docs.ultralytics.com/usage/python/) section, and explore helpful debugging tips in the [Model Training Tips](https://docs.ultralytics.com/guides/model-training-tips/) guide.

You can also join our community for real-time discussions:
- **[Discord](https://discord.com/invite/ultralytics)** 🎧: Chat with developers and users.
- **[Discourse](https://community.ultralytics.com/)**: Engage in in-depth discussions.
- **[Subreddit](https://reddit.com/r/Ultralytics)**: Share knowledge and experiences.

An Ultralytics engineer will review your issue soon to provide further support. Please stay tuned 🚀!

**Comment by Y-T-G** [comment]
Why do you need DDP here? You can just launch two different processes on two different GPUs

**Comment by hutIngk** [comment]
> Why do you need DDP here? You can just launch two different processes on two different GPUs

I think DDP may have lower communication overhead

**Comment by Y-T-G** [comment]
If you're providing path to image files, then you need to chunk them manually. `batch` argument doesn't work for that. It will load all the images at once.

**Comment by hutIngk** [comment]
> If you're providing path to image files, then you need to chunk them manually. `batch` argument doesn't work for that. It will load all the images at once.

Thanks first , but i think it is not the problem that u say, because i tried use this common way:
```
def run_v8(path, model_path, batch_size=32, half=False):
    model = YOLO(model_path)  # pretrained YOLO11n model
    # dummy_detect = model(os.path.join(path, random.choice(os.listdir(path))), verbose=False)
    # dummy_detect = model(torch.zeros(1,3,224,224), verbose=False)
    t1 = time.time()
    results = model(path, batch=batch_size, verbose=False, device=0, half=half, imgsz=640)  # return a list of Results objects
    logger.info(f'batch size {batch_size} infer {len(os.listdir(path))} image -- half:{half}, cost time :{time.time()-t1}')
```
load 640 images at same time as u say,  didn't  happen OOM,

**Comment by Y-T-G** [comment]
Is that a single path or a list of all paths? If it's a list of all paths, it will load all the paths at once. The `batch` argument is not used.

**Comment by hutIngk** [comment]
> Is that a single path or a list of all paths? If it's a list of all paths, it will load all the paths at once. The `batch` argument is not used.

yes！i found that too，i changed my code and it worked，thanks a lot man！

**Comment by glenn-jocher** [comment]
Great to hear you resolved the OOM issue! For future reference, when processing large image sets with YOLO11, we recommend using the streaming mode (`stream=True`) which creates a memory-efficient generator of Results objects. This helps prevent memory buildup by processing images sequentially rather than loading all at once. The Predict Mode documentation shows how to implement this effectively for datasets and directories. Thanks for sharing your solution with the community! 🚀
