### ISSUE TITLE
RuntimeError: CUDA error: out of memory when train model on multiple GPUs

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#1971]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I encounter a CUDA out of memory issue on my workstation when I try to train a new model on my 2 A4000 16GB GPUs. 

I use docker to train the new model. I was observing the actual GPU memory usage, actually when the job only use about 1.5GB mem for each GPU. Also when the job quitted, the memory of one GPU is still not released and the temperature is high as running in full power. 

 Here is the model trainer info for my training job:

`Ultralytics YOLOv8.0.73 🚀 Python-3.10.9 torch-2.0.0 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
                                                     CUDA:1 (NVIDIA RTX A4000, 16376MiB)`
`yolo/engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=../[***].yaml, epochs=10, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=(0, 1), workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train2`

The full error log is

> Starting training for 10 epochs...
> 
>       Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
>   0%|          | 0/61 [00:00<?, ?it/s]
> 
> 
> Traceback (most recent call last):
>   File "/root/.config/Ultralytics/DDP/_temp_buuul4n8139640683097024.py", line 6, in <module>
>     trainer.train()
>   File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 190, in train
>     self._do_train(world_size)
>   File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 301, in _do_train
>     for i, batch in pbar:
>   File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/data/build.py", line 39, in __iter__
>     yield next(self.iterator)
>   File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
>     data = self._next_data()
>   File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
>     return self._process_data(data)
>   File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
>     data.reraise()
>   File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
>     raise exception
> RuntimeError: Caught RuntimeError in pin memory thread for device 1.
> Original Traceback (most recent call last):
>   File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 34, in do_one_step
>     data = pin_memory(data, device)
>   File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 60, in pin_memory
>     return type(data)({k: pin_memory(sample, device) for k, sample in data.items()})  # type: ignore[call-arg]
>   File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 60, in <dictcomp>
>     return type(data)({k: pin_memory(sample, device) for k, sample in data.items()})  # type: ignore[call-arg]
>   File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory
>     return data.pin_memory(device)
> RuntimeError: CUDA error: out of memory
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> 
>        1/10      1.15G      2.456      8.968      1.801         11        640:   2%|▏         | 1/61 [02:46<2:46:06, 166WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 22) of binary: /opt/conda/bin/python3
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 798, in <module>
>     main()
>   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> 
> /root/.config/Ultralytics/DDP/_temp_buuul4n8139640683097024.py FAILED
> 
> Failures:
>   <NO_OTHER_FAILURES>
> 
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-04-12_01:42:08
>   host      : f9495e3508ab
>   rank      : 1 (local_rank: 1)
>   exitcode  : 1 (pid: 22)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> 
> Traceback (most recent call last):
>   File "/opt/conda/bin/yolo", line 8, in <module>
>     sys.exit(entrypoint())
>   File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 391, in entrypoint
>     getattr(model, mode)(**overrides)  # default args from model
>   File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 365, in train
>     self.trainer.train()
>   File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 186, in train
>     raise e
>   File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 184, in train
>     subprocess.run(cmd, check=True)
>   File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '58315', '/root/.config/Ultralytics/DDP/_temp_buuul4n8139640683097024.py', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'data=../datasets/cop_fvi/cop_fvi.yaml', 'epochs=10', 'patience=50', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=(0, 1)', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'image_weights=False', 'rect=False', 'cos_lr=False', 'close_mosaic=0', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'line_thickness=3', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']' returned non-zero exit status 1.
> Sentry is attempting to send 2 pending error messages
> Waiting up to 2 seconds
> Press Ctrl-C to quit

Here is the screenshot of nvidia-smi before running the training job :
<img width="562" alt="image" src="https://user-images.githubusercontent.com/2324213/231327407-feac8db9-515f-4bc1-bc46-62ac1d7d3d61.png">

**Comment by darouwan** [comment]
I fix this issue by setting `worker=0`

But the GPU still cannot be released if GPU is out of memory when I set a large batch size. What I can do is to restart the computer.

**Comment by glenn-jocher** [comment]
@darouwan the issue with GPU memory being out of capacity can be resolved by setting the worker parameter as zero. However, if a large batch size is set, the GPU may still not be released. In this scenario, restarting the computer may be necessary to free up the GPU memory. It is important to monitor and adjust batch sizes according to available GPU capacity to prevent this issue from recurring in the future.

**Comment by darouwan** [comment]
@glenn-jocher Got it. Thanks. 

But one more strange thing is training time in docker is much slower than in native Windows env. The epoch time for training in docker is more than one minute and that's about 40 seconds in Windows when I test on single GPU.

**Comment by darouwan** [comment]
@glenn-jocher I found the reason for low performance, which is caused by the virtual env of python in wsl. When I use the system python environment in WSL, the training speed is same as local windows training. 

However, when I tried to test 2 GPUs training, the error

>    return type(data)({k: pin_memory(sample, device) for k, sample in data.items()})  # type: ignore[call-arg]
>   File "/home/miao/.local/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory
>     return data.pin_memory(device)
> RuntimeError: CUDA error: out of memory
 still happen. 

I have test the same training params on single gpu and it runs well. So it doesn't make sense when I use two gpus with double GPU mem on same batch size.

**Comment by glenn-jocher** [comment]
@darouwan it is great that you were able to identify the cause of the lower performance in your previous environment. However, new issues have arisen when attempting to train using dual GPUs with double GPU memory. In this scenario, a CUDA out of memory error occurs. This error is likely due to the fact that the increased batch size is exceeding the available memory on the GPUs. When training with multiple GPUs, the batch size should be distributed evenly to all GPUs to ensure that memory usage is relatively constant. Additionally, it is recommended to use a larger effective batch size, which is the sum of the batch sizes across all GPUs, to maximize training efficiency. It may also be helpful to monitor GPU memory usage during training to identify any potential memory leaks or inefficient memory usage.

**Comment by wangsun1996** [comment]
> @glenn-jocher I found the reason for low performance, which is caused by the virtual env of python in wsl. When I use the system python environment in WSL, the training speed is same as local windows training.
> 
> However, when I tried to test 2 GPUs training, the error
> 
> > return type(data)({k: pin_memory(sample, device) for k, sample in data.items()})  # type: ignore[call-arg]
> > File "/home/miao/.local/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory
> > return data.pin_memory(device)
> > RuntimeError: CUDA error: out of memory
> > still happen.
> 
> I have test the same training params on single gpu and it runs well. So it doesn't make sense when I use two gpus with double GPU mem on same batch size.

请问你的问题解决了吗？我的机器是两卡A100，单张卡的显存为40G。当我使用不同的数据集训练时（图片的分辨率相同），观察到两个现象：1.显存占用不平衡（两张卡相差7个G），且波动很大2.同样分辨率、同样训练参数的情况下，仅仅换了一个数据集，一直提示out of memory，哪怕BS设置为4，仍然出现超显存的问题

**Comment by glenn-jocher** [comment]
@wangsun1996 解决性能问题是个好消息！关于多GPU训练的内存问题，即使在两个GPU上使用相同的批量大小，也可能会遇到CUDA内存不足的错误。这可能是由于数据分布不均匀或某些GPU上的内存碎片化。请确保数据加载和批处理是高效的，并且尝试减少每个GPU上的批量大小来适应双GPU设置。此外，监控GPU内存使用情况，以便更好地理解内存分配和消耗。如果问题持续存在，请考虑在我们的文档中查找更多关于多GPU训练的最佳实践。

**Comment by jeffrey-cochran** [comment]
> t is great that you were able to identify the cause of the lower performance in your previous environment. However, new issues have arisen when attempting to train using dual GPUs with double GPU memory. In this scenario, a CUDA out of memory error occurs. This error is likely due to the fact that the increased batch size is exceeding the available memory on the GPUs. When training with multiple GPUs, the batch size should be distributed evenly to all GPUs to ensure that memory usage is relatively constant. Additionally, it is recommended to use a larger effective batch size, which is the sum of the batch sizes across all GPUs, to maximize training efficiency. It may also be helpful to monitor GPU memory usage during training to identify any potential memory leaks or inefficient memory usage.

This doesn't make sense to me. Was this written with ChatGPT or something?

**Comment by glenn-jocher** [comment]
@jeffrey-cochran thank you for flagging this. Let's address the multi-GPU memory issue directly: When using 2 GPUs, the batch size is automatically split between devices. The error suggests your per-GPU memory can't handle half the total batch size. Try reducing the total batch size (e.g., if using batch=16 on 1 GPU, try batch=8 when using 2 GPUs). 

For multi-GPU optimization, see the Accelerating Training with Multiple GPUs section in our YOLO Common Issues guide. Monitor memory usage with `torch.cuda.memory_reserved()` during training to find your system's limits.

If issues persist, please share:
1. Exact training command used
2. `nvidia-smi` output during training
3. Full error trace

We'll help resolve this efficiently.
