### ISSUE TITLE
Minimal train DDP crash using 2x5090 GPUs

### ISSUE THREAD

**Issue by cribbinsb** [ultralytics/ultralytics#19987]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.


### Ultralytics YOLO Component

Train

### Bug

I have done a clean install of a 2x5090 GPU system, using nvidia drivers 570.133.07, Python-3.12.9 torch-2.8.0.dev20250402+cu128  (nightly pytorch required by 5090, i believe)

The minimal "coco8" train sample (below) works with one GPU, but fails with DDP (device=[0,1]) 



### Environment

Ultralytics 8.3.100 🚀 Python-3.12.9 torch-2.8.0.dev20250402+cu128 CUDA:0 (NVIDIA GeForce RTX 5090, 32112MiB
)                                                     
Setup complete ✅ (32 CPUs, 251.5 GB RAM, 91.8/788.8 GB disk)                                       

OS                  Linux-6.8.0-57-generic-x86_64-with-glibc2.39
Environment         Linux
Python              3.12.9                                                                                  
Install             pip                                                                                     
Path                /home/###anaconda3/envs/yolo/lib/python3.12/site-packages/ultralytics                 
RAM                 251.46 GB     
Disk                91.8/788.8 GB                                                                           
CPU                 AMD EPYC 9174F 16-Core Processor                                                        
CPU count           32     
GPU                 NVIDIA GeForce RTX 5090, 32112MiB
GPU count           2
CUDA                12.8
                           
numpy               ✅ 2.1.1<=2.1.1,>=1.23.0          
matplotlib          ✅ 3.10.1>=3.3.0                  
opencv-python       ✅ 4.11.0.86>=4.6.0               
pillow              ✅ 11.1.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1                   
requests            ✅ 2.32.3>=2.23.0 
scipy               ✅ 1.15.2>=1.4.1                                                                        
torch               ✅ 2.8.0.dev20250402+cu128>=1.8.0
torch               ✅ 2.8.0.dev20250402+cu128!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.22.0.dev20250402+cu128>=0.9.0                                                      
tqdm                ✅ 4.67.1>=4.64.0        
psutil              ✅ 7.0.0                 
py-cpuinfo          ✅ 9.0.0                 
pandas              ✅ 2.2.3>=1.1.4                                                                         
seaborn             ✅ 0.13.2>=0.11.0                                                                       
ultralytics-thop    ✅ 2.0.14>=2.0.0                  


### Minimal Reproducible Example

```
from ultralytics import YOLO

# Load a model
model = YOLO("yolo11n.yaml")  # build a new model from YAML
model = YOLO("yolo11n.pt")  # load a pretrained model (recommended for training)
model = YOLO("yolo11n.yaml").load("yolo11n.pt")  # build from YAML and transfer weights

# Train the model
results = model.train(data="coco8.yaml", epochs=100, imgsz=640, device=[0,1])

### Additional

           Here is the failure:

python ddp_test.py                                                                                                                  
Transferred 499/499 items from pretrained weights                                                                                                                                
Ultralytics 8.3.100 🚀 Python-3.12.9 torch-2.8.0.dev20250402+cu128 CUDA:0 (NVIDIA GeForce RTX 5090, 32112MiB)                                                                    
                                                                   CUDA:1 (NVIDIA GeForce RTX 5090, 32120MiB)                                                                    
engine/trainer: task=detect, mode=train, model=yolo11n.yaml, data=coco8.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, d
evice=[0, 1], workers=8, project=None, name=train10, exist_ok=False, pretrained=yolo11n.pt, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=Fals
e, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, sp
lit=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False,
 augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=Tr
ue, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=
False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=6
4, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, 
copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train10                                     
                                                                                                                                                                                 
                   from  n    params  module                                       arguments                                                                                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                                                                                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                                                                                
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]                                                                      
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                                                                                
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]                                                                     
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]                                                                                6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]                                                                           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]                                                                              
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]                                                                           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                  
10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]                                                                                 
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']                                                                          
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                                                                                           
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]                                                                          
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']                                                                          
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                                                                                           
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]                                                                           
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                                                                                
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]                                                                                           
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]                                                                          
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]                                                                              
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]                                                                                           
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]                                                                           
 23        [16, 19, 22]  1    464912  ultralytics.nn.modules.head.Detect           [80, [64, 128, 256]]                                                                          
YOLO11n summary: 181 layers, 2,624,080 parameters, 2,624,064 gradients, 6.6 GFLOPs                                                                                               
                                                                                                                                                                                 
Transferred 499/499 items from pretrained weights                                                                                                                                
DDP: debug command /home/####/anaconda3/envs/yolo/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 50843 /home/####/.config/Ultralytics/DDP/_temp_nlki9hrm139
522556300320.py                                                                                                                                                                  
Ultralytics 8.3.100 🚀 Python-3.12.9 torch-2.8.0.dev20250402+cu128 CUDA:0 (NVIDIA GeForce RTX 5090, 32112MiB)                                                                    
                                                                   CUDA:1 (NVIDIA GeForce RTX 5090, 32120MiB)                                                                    
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1                                                                                       
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1                                                                                       
Transferred 499/499 items from pretrained weights                                                                                                                                
Freezing layer 'model.23.dfl.conv.weight'                                                                                                                                        
AMP: running Automatic Mixed Precision (AMP) checks...                                                                                                                           
AMP: checks passed ✅                                                                                                                                                            [rank0]: Traceback (most recent call last):                                                                                                                                      
[rank0]:   File "/home/####/.config/Ultralytics/DDP/_temp_nlki9hrm139522556300320.py", line 13, in <module>                                                                      
[rank0]:     results = trainer.train()                                                                                                                                           
[rank0]:               ^^^^^^^^^^^^^^^                                                   
[rank0]:   File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 211, in train                                                  
[rank0]:     self._do_train(world_size)                                                                                                                                          
[rank0]:   File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train                                              
[rank0]:     self._setup_train(world_size)                                                                                                                                       
[rank0]:   File "/home/#####/anaconda3/envs/yolo/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 278, in _setup_train                                           
[rank0]:     self.model = nn.parallel.DistributedDataParallel(self.model, device_ids=[RANK], find_unused_parameters=True)                                                        
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                        
[rank0]:   File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/nn/parallel/distributed.py", line 837, in __init__                                            
[rank0]:     _sync_module_states(                                                                                                                                                
[rank0]:   File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/distributed/utils.py", line 311, in _sync_module_states                                       
[rank0]:     _sync_params_and_buffers(process_group, module_states, broadcast_bucket_size, src)                                                                                  
[rank0]:   File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/distributed/utils.py", line 322, in _sync_params_and_buffers                                  
[rank0]:     dist._broadcast_coalesced(                                                                                                                                          
[rank0]: RuntimeError: CUDA error: an illegal memory access was encountered 
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.                                                 
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1                                                                                                                   
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.                                                                                                     
                                                                                                                                                                                 
[rank1]: Traceback (most recent call last):                                                                                                                                      
[rank1]:   File "/home/####/.config/Ultralytics/DDP/_temp_nlki9hrm139522556300320.py", line 13, in <module>                                                                      
[rank1]:     results = trainer.train()                                                                                                                                           
[rank1]:               ^^^^^^^^^^^^^^^                                                                                                                                           
[rank1]:   File "/home####/anaconda3/envs/yolo/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 211, in train                                                  
[rank1]:     self._do_train(world_size)                                                                                                                                          
[rank1]:   File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train                                              
[rank1]:     self._setup_train(world_size)                                                                                                                                       
[rank1]:   File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 278, in _setup_train                                           [rank1]:     self.model = nn.parallel.DistributedDataParallel(self.model, device_ids=[RANK], find_unused_parameters=True)                                                        
[rank1]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                        
[rank1]:   File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/nn/parallel/distributed.py", line 837, in __init__                                            
[rank1]:     _sync_module_states(                                                                                                                                                
[rank1]:   File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/distributed/utils.py", line 311, in _sync_module_states                                       
[rank1]:     _sync_params_and_buffers(process_group, module_states, broadcast_bucket_size, src)                                                                                  
[rank1]:   File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/distributed/utils.py", line 322, in _sync_params_and_buffers                                  
[rank1]:     dist._broadcast_coalesced(                                                                                                                                          
[rank1]: RuntimeError: CUDA error: an illegal memory access was encountered                                                                                                      
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.                                                 
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1                                                                                                                   
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.                                                                                                     
                                                                                                                                                                                 
W0402 18:13:04.160000 29708 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 29710 closing signal SIGTERM                                     
E0402 18:13:04.476000 29708 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 1 (pid: 29711) of binary: /home/####/anaconda3/e
nvs/yolo/bin/python                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                               
  File "<frozen runpy>", line 198, in _run_module_as_main            
  File "<frozen runpy>", line 88, in _run_code                                                                                                                                   
  File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/distributed/run.py", line 896, in <module>                                                             
    main()                                                                                                                                                                       
  File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper                          
    return f(*args, **kwargs)                                                                                                                                                    
           ^^^^^^^^^^^^^^^^^^                                                                                                                                                    
  File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in main                                                                 
    run(args)                                                                                                                                                                    
  File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/distributed/run.py", line 883, in run                                                                  
    elastic_launch(                                                                                                                                                              
  File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 139, in __call__                                                    
    return launch_agent(self._config, self._entrypoint, list(args))                                                                                                              
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent                                                
    raise ChildFailedError(                                                                                                                                                      
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:                                                                                                               
============================================================                                                                                                                     
/home/####/.config/Ultralytics/DDP/_temp_nlki9hrm139522556300320.py FAILED                                                                                                       
------------------------------------------------------------                                                                                                                     
Failures:                                                                                                                                                                        
  <NO_OTHER_FAILURES>                                                                                                                                                            
------------------------------------------------------------                                                                                                                     
Root Cause (first observed failure):                                                                                                                                             
[0]:                                                                                                                                                                             
  time      : 2025-04-02_18:13:04                                                                                                                                                
  host      : #####                                                                                                                                                              
  rank      : 1 (local_rank: 1)                                                                                                                                                  
  exitcode  : 1 (pid: 29711)                                                                                                                                                     
  error_file: <N/A>                                                                                                                                                              
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html                                                                                       
============================================================                                                                 
/home/####/.config/Ultralytics/DDP/_temp_nlki9hrm139522556300320.py FAILED                                                                                                       
------------------------------------------------------------                                                                                                                     
Failures:                                                                                                                                                                        
  <NO_OTHER_FAILURES>                                                                                                                                                            
------------------------------------------------------------                                                                                                                     
Root Cause (first observed failure):                                                                                                                                             
[0]:                                                                                                                                                                             
  time      : 2025-04-02_18:13:04                                                                                                                                                
  host      : #####                                                                                                                                                              
  rank      : 1 (local_rank: 1)                                                                                                                                                  
  exitcode  : 1 (pid: 29711)                                                                                                                                                     
  error_file: <N/A>                                                                                                                                                              
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html                                                                                       ============================================================                                                                                                                     
Traceback (most recent call last):                                                                                                                                               
  File ##############/ddp_test.py", line 9, in <module>                                                                                                     
    results = model.train(data="coco8.yaml", epochs=100, imgsz=640, device=[0,1])                                                                                                
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                
  File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/ultralytics/engine/model.py", line 791, in train                                                             
    self.trainer.train()                                                                                                                                                         
  File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 206, in train                                                           
    raise e                                                                                                                                                                      
  File "/home/####/anaconda3/envs/yolo/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 204, in train                                                           
    subprocess.run(cmd, check=True)                                                                                                                                              
  File "/home/####/anaconda3/envs/yolo/lib/python3.12/subprocess.py", line 573, in run                                                                                           
    raise CalledProcessError(retcode, process.args,                                                                                                                              
subprocess.CalledProcessError: Command '['/home####/anaconda3/envs/yolo/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '50843', '/home/####/.config/Ultralytics/DDP/_temp_nlki9hrm139522556300320.py']' returned non-zero exit status 1.          
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Seems like it doesn't support NCCL yet. It's a PyTorch issue.

**Comment by cribbinsb** [comment]
This still happens with the latest pytorch + ultralytics code; I am using the latest NCCL 2.26.2- seems like this should work on 5090. I am wondering if other people are seeing this issue and if there is any known workaround?

Should I raise a bug with pytorch?

**Comment by Y-T-G** [comment]
What's the output of `torch.cuda.nccl.version()`?

**Comment by echo385** [comment]
> This still happens with the latest pytorch + ultralytics code; I am using the latest NCCL 2.26.2- seems like this should work on 5090. I am wondering if other people are seeing this issue and if there is any known workaround?
> 
> Should I raise a bug with pytorch?

I have the same problem, do you solve it?

**Comment by cribbinsb** [comment]
> torch.cuda.nccl.version()

>>> import torch
>>> print(torch.cuda.nccl.version())
(2, 26, 2)

Believe this is the latest 2.26.2 (https://docs.nvidia.com/deeplearning/nccl/release-notes/index.html)

**Comment by Y-T-G** [comment]
What's the output of ?

```
from torch import distributed as dist
dist.is_available()
```

**Comment by cribbinsb** [comment]
> What's the output of
> 
> ```
> from torch import distributed as dist
> dist.is_available()
> ```

>>> from torch import distributed as dist
>>> dist.is_available()
True

**Comment by cribbinsb** [comment]
In case its interesting: If I run with NCCL debug and blocking cuda it's a little clearer; the first error is a cuda illegal memory access.


ubon1:43996:44019 [1] NCCL INFO [Proxy Service] Device 1 CPU core 29                                                                                             
ubon1:43995:44020 [0] NCCL INFO [Proxy Service] Device 0 CPU core 30                                                                                             
ubon1:43996:44015 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512                                                                                    
ubon1:43996:44015 [1] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer                                    
ubon1:43995:44014 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512                                                                                    
ubon1:43995:44014 [0] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer                                    
ubon1:43995:44014 [0] NCCL INFO CC Off, workFifoBytes 1048576                                                                                                    
ubon1:43996:44015 [1] NCCL INFO TUNER/Plugin: Could not find: libnccl-tuner.so. Using internal tuner plugin.                                                     
ubon1:43996:44015 [1] NCCL INFO ncclCommInitRankConfig comm 0x32e2e8c0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId c1000 commId 0xa8cdb34407f0e0df - Init COMPLETE 
ubon1:43996:44015 [1] NCCL INFO Init timings - ncclCommInitRankConfig: rank 1 nranks 2 total 24.01 (kernels 23.98, alloc 0.00, bootstrap 0.02, allgathers 0.00, t
opo 0.00, graphs 0.00, connections 0.00, rest 0.00)                                                                                                              
ubon1:43995:44014 [0] NCCL INFO TUNER/Plugin: Could not find: libnccl-tuner.so. Using internal tuner plugin.                                                     
ubon1:43995:44014 [0] NCCL INFO ncclCommInitRankConfig comm 0x3a70fb70 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 41000 commId 0xa8cdb34407f0e0df - Init COMPLETE 
ubon1:43995:44014 [0] NCCL INFO Init timings - ncclCommInitRankConfig: rank 0 nranks 2 total 24.01 (kernels 23.99, alloc 0.00, bootstrap 0.01, allgathers 0.00, t
opo 0.00, graphs 0.00, connections 0.00, rest 0.00)                                                                                                              
ubon1:43995:44023 [0] NCCL INFO Channel 00 : 0[0] -> 1[1] via SHM/direct/direct                                                                                  
ubon1:43996:44024 [1] NCCL INFO Channel 00 : 1[1] -> 0[0] via SHM/direct/direct                                                                                  
ubon1:43995:44023 [0] NCCL INFO Channel 01 : 0[0] -> 1[1] via SHM/direct/direct                                                                                  
ubon1:43996:44024 [1] NCCL INFO Channel 01 : 1[1] -> 0[0] via SHM/direct/direct                                                                                  
ubon1:43995:44023 [0] NCCL INFO Connected all rings, use ring PXN 0 GDR 1                                                                                        
ubon1:43996:44024 [1] NCCL INFO Connected all rings, use ring PXN 0 GDR 1                                                                                        
                                                                                                                                                                 
[2025-04-07 07:01:55] mtest:43995:43995 [0] enqueue.cc:1556 NCCL WARN Cuda failure 700 'an illegal memory access was encountered'

**Comment by glenn-jocher** [comment]
Thanks for providing the detailed NCCL debug logs, @cribbinsb.

The `cuda illegal memory access was encountered` error during the DDP synchronization step strongly suggests an issue within the PyTorch, CUDA, or NCCL libraries, particularly given the use of new RTX 5090 hardware and a nightly PyTorch build.

Since Ultralytics relies on PyTorch for DDP functionality, the most effective path forward would be to [report this issue directly to the PyTorch GitHub repository](https://github.com/pytorch/pytorch/issues). They are best positioned to diagnose these kinds of low-level CUDA/NCCL integration problems. Please include your detailed environment information, the minimal reproducible code, and the full error logs (including the NCCL debug output) in your report to them.

**Comment by cribbinsb** [comment]
I'm please to report it seems this has now been fixed. You need to upgrade nvidia-nccl-cu12 to 2.26.2.post1 (or presumably any future later version) with:

pip install --upgrade nvidia-nccl-cu12

**Comment by sama-cow** [comment]
can u respectfully provide, how u set the 5090 to be able to perform model training, i am running into kernel image not found for execution error

**Comment by glenn-jocher** [comment]
@sama-cow The "kernel image not found for execution" error typically indicates a mismatch between your CUDA driver version and the CUDA toolkit version your PyTorch build is expecting. For RTX 5090 GPUs, you'll need:

1. The latest NVIDIA drivers (570+ series)
2. CUDA 12.x toolkit compatibility
3. A PyTorch version built for CUDA 12.x (usually labeled as cu128)

To fix your specific issue:

1. Make sure you have the latest NVIDIA drivers installed
2. Install PyTorch with CUDA 12.x support (either stable or nightly as needed)
3. Update NCCL as mentioned above: `pip install --upgrade nvidia-nccl-cu12`

If you need further assistance with your specific setup, please create a new issue with complete details about your environment, including the output of `nvidia-smi` and how you installed PyTorch.

**Comment by cribbinsb** [comment]
> can u respectfully provide, how u set the 5090 to be able to perform model training, i am running into kernel image not found for execution error

What is working for me (with 2x5090) right now is:
- Ubuntu 24.04
- nvidia drivers 570.133.07
- Cuda 12.8
- Pytorch "nightly" cuda 12.8 from here https://pytorch.org/get-started/locally
- Python nccl 2.26.2.post1 (pip install --upgrade nvidia-nccl-cu12)
- Latest ultralytics

I'm also finding 2x5090 is almost twice as fast as 2x4090 which is a positive surprise; training a yolo11L variant, 640x640, I get around 30 mins for an epoch with 350K images, around 200 images/second (batch size 64)

**Comment by glenn-jocher** [comment]
Thanks for sharing your detailed working configuration @cribbinsb! This is extremely valuable information for others using RTX 5090 GPUs. The performance metrics you're reporting (30 minutes per epoch on 350K images with YOLO11L at 640x640) is impressive - nearly 2x the performance over 4090s matches what we'd expect from the architecture improvements.

Your complete solution with specific versions of:
- Ubuntu 24.04
- NVIDIA drivers 570.133.07
- CUDA 12.8
- PyTorch nightly with CUDA 12.8
- NCCL 2.26.2.post1
- Latest Ultralytics

Creates a perfect reference for anyone setting up these new GPUs for YOLO training. I'm glad the NCCL upgrade resolved the original issue with distributed training.

**Comment by leeyg-gnu** [comment]
<img width="1475" height="435" alt="Image" src="https://github.com/user-attachments/assets/508e77a7-fcce-4383-a1a0-241b82fe9a51" />

I also tried to perform multi-GPU training on my 5090 2-way setup with the same versions installed,
but it doesn’t work correctly.

The only small difference is that my system is Ubuntu 24.04.1 LTS.
Could that be the cause of the issue?

When I start the training, I can hear the GPUs spinning up,
but the training log stops right at the point shown in the image and doesn’t progress further.

**Comment by Y-T-G** [comment]
@leeyg-gnu From your loga, it's using Gloo and not NCCL. Did you install NCCL like suggested before?

**Comment by leeyg-gnu** [comment]
python -c "import torch; print(torch.__version__)"
python -c "import torch; print(torch.version.cuda)"
python -c "import torch; print(torch.cuda.nccl.version())"

2.10.0.dev20251102+cu128
12.8
(2, 27, 5)
_______________________________________________________________________________________________________________________________________
>>> import torch
>>> print(torch.distributed.is_nccl_available())
True
_______________________________________________________________________________________________________________________________________
I initially attempted to install NCCL 2.26.2.post1, but it was incompatible with the current PyTorch build, so I upgraded to NCCL 2.27.5, which works correctly.

In this environment, when running the following training code:

results = model.train(
    data="coco128.yaml",
    epochs=100,
    imgsz=640,
    device=[0, 1],
    workers=1
)

the training runs without any errors when workers=1, but errors occur when workers is set to 2 or higher.

<img width="1170" height="274" alt="Image" src="https://github.com/user-attachments/assets/e3a61ec8-164a-426c-bd12-2dc68da49d00" />

In addition, when workers=1, the logs appear as shown above.

**Comment by Y-T-G** [comment]
You should not use PyTorch nightly. Just use latest stable PyTorch. 5090 is already supported in stable PyTorch

**Comment by leeyg-gnu** [comment]
The training runs normally with the following settings:
results = model.train(data="DOTAv1.5.yaml", 
                      epochs=100, 
                      imgsz=640, 
                      device=[0, 1], 
                      batch=8, 
                      workers=1)

However, an error occurs when workers is set to a value greater than 1.
My CPU is an Intel Xeon w5-2465X with 16 cores and 32 threads. Could this be the cause of the problem?

**Comment by Y-T-G** [comment]
Use PyTorch 2.9

**Comment by leeyg-gnu** [comment]
I installed PyTorch 2.9, but the same issue still occurs.

**Comment by glenn-jocher** [comment]
@leeyg-gnu Thanks for checking with 2.9. Since `workers=1` succeeds but `>1` fails, this points to a DataLoader multiprocessing/start‑method issue rather than NCCL. Please try forcing a safe start method and backend, then re‑test:

```python
# run as a script (important for spawn)
import os, torch
os.environ["TORCH_DISTRIBUTED_DEFAULT_BACKEND"] = "nccl"
os.environ["TORCH_DISTRIBUTED_DEBUG"] = "DETAIL"

torch.multiprocessing.set_start_method("spawn", force=True)

from ultralytics import YOLO
if __name__ == "__main__":
    YOLO("yolo11n.pt").train(data="coco128.yaml", device=[0, 1], workers=4, batch=16, epochs=1)
```

As a cross‑check, also try the CLI path (no Python API init code):
```bash
yolo detect train model=yolo11n.pt data=coco128.yaml device=0,1 workers=4 epochs=1
```

If it still hangs/errors, please attach:
- Output of `yolo checks` (or `!yolo checks` in notebooks)
- Full text traceback/log (not a screenshot), including the first ~50 lines with `TORCH_DISTRIBUTED_DEBUG=DETAIL`
- Exact `pip list | grep -E "torch|torchvision|nccl"` versions

For reference, see the multi‑GPU examples in our [multi‑GPU training guide](https://docs.ultralytics.com/modes/train/#multi-gpu-training) and the environment diagnostics described in the [check_yolo reference](https://docs.ultralytics.com/reference/utils/checks/#ultralyticsutilschecksyolo). If this persists, please open a new issue with the above details so we can track it separately from this closed thread.

**Comment by leeyg-gnu** [comment]
I’m still encountering the same error. I’ve opened a new issue and attached the full output logs for reference. Your help in reviewing it would be greatly appreciated.

**Comment by glenn-jocher** [comment]
Thanks for opening the new issue and attaching the logs—we’ll track it there; I’ll review and follow up in that thread.
