### ISSUE TITLE
OBB training out of memory

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/ultralytics#20843]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi all! I am trying to train my first OBB model. it is just for testing, so i have a very basic dataset with just 6 train images and 1 validation image. each images has about 30 instances of 2 classes. again, i do not need a good result, its just a proof of concept. 

I have a setup with 2 gpus with 16gb of ram, so plenty of memory for this task. During training it uses about 6 gb of ram in total. but then suddenly after X (random) epochs the training crashes with "out of memory" error. i tried to enable `%env PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` but that did not change the result. 

i tried training on one gpu or with both, tried to enable caching in ram or on disk, tried lowering the batch size to 1, tried enabling and disabling augmentation. I tried various network sizes (n,s,m) it did not make a difference. here is the error message i get and below my system specs. what am i missing?

my training command:

`
!yolo obb train model=yolo11m-obb.yaml batch=6 epochs=3000 data='/mnt/Data/datasets/aaa/obb/data.yaml' \
augment=False device=[0,1] patience=1000 name='Obb_V1.0.0_m_Y11_' imgsz=1024`

The last epochs and the error:

```      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
   203/3000      4.46G      2.717      1.583      3.579        570       1024: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all          1        122      0.254      0.186       0.17     0.0551

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
   204/3000      4.58G      3.062      1.759      3.667        722       1024: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/cnnserver/.config/Ultralytics/DDP/_temp_0c5oe6s2125604036212144.py", line 13, in <module>
[rank0]:     results = trainer.train()
[rank0]:   File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 212, in train
[rank0]:     self._do_train(world_size)
[rank0]:   File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 439, in _do_train
[rank0]:     self.metrics, self.fitness = self.validate()
[rank0]:   File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 636, in validate
[rank0]:     metrics = self.validator(self)
[rank0]:   File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 223, in __call__
[rank0]:     preds = self.postprocess(preds)
[rank0]:   File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/models/yolo/detect/val.py", line 123, in postprocess
[rank0]:     return ops.non_max_suppression(
[rank0]:   File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/utils/ops.py", line 319, in non_max_suppression
[rank0]:     i = nms_rotated(boxes, scores, iou_thres)
[rank0]:   File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/utils/ops.py", line 162, in nms_rotated
[rank0]:     ious = batch_probiou(boxes, boxes)
[rank0]:   File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/utils/metrics.py", line 274, in batch_probiou
[rank0]:     hd = (1.0 - (-bd).exp() + eps).sqrt()
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.48 GiB. GPU 0 has a total capacity of 15.48 GiB of which 1.90 GiB is free. Including non-PyTorch memory, this process has 13.55 GiB memory in use. Of the allocated memory 12.85 GiB is allocated by PyTorch, and 171.08 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
W0528 08:14:42.860000 472146 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 472149 closing signal SIGTERM
E0528 08:14:42.862000 472146 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 472148) of binary: /home/cnnserver/anaconda3/envs/aaa/bin/python
Traceback (most recent call last):
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/torch/distributed/run.py", line 896, in <module>
    main()
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/cnnserver/.config/Ultralytics/DDP/_temp_0c5oe6s2125604036212144.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-28_08:14:42
  host      : cnnserver-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 472148)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/cnnserver/anaconda3/envs/aaa/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 981, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/engine/model.py", line 793, in train
    self.trainer.train()
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 207, in train
    raise e
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 205, in train
    subprocess.run(cmd, check=True)
  File "/home/cnnserver/anaconda3/envs/aaa/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/cnnserver/anaconda3/envs/aaa/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '38481', '/home/cnnserver/.config/Ultralytics/DDP/_temp_0c5oe6s2125604036212144.py']' returned non-zero exit status 1.
```

### Environment

```
Ultralytics 8.3.128 🚀 Python-3.10.16 torch-2.7.0+cu128 CUDA:0 (NVIDIA GeForce RTX 5070 Ti, 15851MiB)
Setup complete ✅ (24 CPUs, 125.3 GB RAM, 102.7/983.2 GB disk)

OS                  Linux-6.11.0-25-generic-x86_64-with-glibc2.39
Environment         Linux
Python              3.10.16
Install             pip
Path                /home/cnnserver/anaconda3/envs/cratevision/lib/python3.10/site-packages/ultralytics
RAM                 125.30 GB
Disk                102.7/983.2 GB
CPU                 Intel Xeon w5-2545
CPU count           24
GPU                 NVIDIA GeForce RTX 5070 Ti, 15851MiB
GPU count           2
CUDA                12.8

numpy               ✅ 2.1.2>=1.23.0
matplotlib          ✅ 3.10.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.15.2>=1.4.1
torch               ✅ 2.7.0+cu128>=1.8.0
torch               ✅ 2.7.0+cu128!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.22.0+cu128>=0.9.0
tqdm                ✅ 4.67.1>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.14>=2.0.0
```

### Minimal Reproducible Example

!yolo obb train model=yolo11m-obb.yaml batch=6 epochs=3000 data='/mnt/Data/datasets/aaa/obb/data.yaml' \
augment=False device=[0,1] patience=1000 name='Obb_V1.0.0_m_Y11_' imgsz=1024

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Can you reproduce it with one of the stock datasets?

https://docs.ultralytics.com/datasets/obb/#what-datasets-are-currently-supported-for-obb-training-in-ultralytics-yolo-models

**Comment by MasIgor** [comment]
i am trying to reproduce it, but there is a problem. the error appears after one or 2 epochs when the score is >0. so for my small dataset for example, it takes lets say 45 epoch to get away from the 0, then at epoch 46 or 47 it crashes. i am starting from scratch, so my model is the yaml file, not the pt file. 

now, i downloaded the 8-image dataset you posted, but even after 2k epochs the value is still at zero, so i am unable to reproduce. i took the 8 image as it is the closest to my situation. trying with 4k epochs now, if it fails i will post the results, else i will try with a bigger dataset.

**Comment by MasIgor** [comment]
i did some more trying.. it does ONLY happen if i start with a yaml from scratch as model, not with a pt as model. 
i was not able to reproduce with the test dataset because it never goes above 0 in 5k epochs with just 4 images.
so i can go around this problem by starting with a pt file. but something is off here. maybe you can try on your end with some simple images that will get a result in a few epochs.

**Comment by Y-T-G** [comment]
Does OOM occur on your dataset if you disable validation (`val=False`)?

**Comment by Y-T-G** [comment]
> ious = batch_probiou(boxes, boxes)

Can you also find out how many boxes are being passed here when the error occurs?

**Comment by Petros626** [comment]
@MasIgor https://github.com/ultralytics/ultralytics/issues/7030, https://github.com/ultralytics/ultralytics/issues/10102

**Comment by MasIgor** [comment]
@Y-T-G It is not happening with validation disabled.

i will try to make the other test asap and report back. any idea why starting with the PT instead of the YAML as model solves the issue?

**Comment by Y-T-G** [comment]
> i will try to make the other test asap and report back. any idea why starting with the PT instead of the YAML as model solves the issue?

Probably PT doesn't create a lot of incorrect predictions since it's already trained. The issue is probably related to the number of predicted boxes.

**Comment by MasIgor** [comment]
@Y-T-G is this what you needed?

ERROR:root:[DEBUG] nms_rotated failed in /home/cnnserver/anaconda3/envs/aaa/lib/python3.10/site-packages/ultralytics/utils/ops.py
• boxes type:   <class 'torch.Tensor'>
• boxes dtype:  torch.float32
• boxes shape:  torch.Size([26963, 5])
• first rows:
tensor([[6.9900e+02, 8.6500e+01, 1.5512e+02, 2.6531e+01, 1.0199e-01],
        [6.9900e+02, 1.0250e+02, 1.5475e+02, 2.6562e+01, 9.9731e-02],
        [7.1550e+02, 1.0250e+02, 1.5475e+02, 2.6406e+01, 1.0126e-01],
        [6.9900e+02, 1.1850e+02, 1.5475e+02, 2.6766e+01, 9.8938e-02],
        [6.9950e+02, 2.1450e+02, 1.5488e+02, 2.6719e+01, 1.0046e-01]], device='cuda:0')
                 Class     Images  Instances      Box(P          R      mAP50  m

**Comment by Y-T-G** [comment]
@Laughing-q Can we limit the number of predicted boxes used in `batch_probiou` calculation to avoid memory issue?

**Comment by Laughing-q** [comment]
@MasIgor Hey since it's not reproducible on our sample test dataset, is it possible you share you small dataset here for us to reproduce and debug this a bit? Thank you!

**Comment by MasIgor** [comment]
@Laughing-q 

sure, here is the download link: https://we.tl/t-Fklc8daYxz

**Comment by Laughing-q** [comment]
@MasIgor Hey thanks for sharing the dataset. I tested it and able to reproduce the issue. The issue here happens is because there are a lot low-confidence scores objects passing to `batch_probiou` function where we get all the iou values for obb objects:
https://github.com/ultralytics/ultralytics/blob/487e27639595047cff8775dab5e2ff268d8647c4/ultralytics/utils/ops.py#L174
Due to torchvision does not have such nms specifically for rotated objects hence we can not use optimized `torchvision.ops.nms` operation we are using for regular detection task, so we had to implement this by our own, and to speed up the whole nms process for rotated objects we are using fast-nms method(which kinda sacrifices memory to gain speed and decent final results).
The simplest solution here is to use a bit higher `conf` value i.e. `0.01`(the default one is 0.001 if you don't explicitly pass a value) to filter those low-confidence scores objects, which makes sense as I personally also use `conf=0.01` in my training configuration for all the official OBB models training.
I've submitted a [PR](https://github.com/ultralytics/ultralytics/pull/20923) to lower the conf to 0.01 by default if users don't explicitly pass a value, before it gets merged please try to set `conf=0.01` in your training command to fix the issue. Please let me know if it works to you. Thanks!

**Comment by MasIgor** [comment]
@Laughing-q that makes sense.. And yes, i can confirm that this solves the issue. with 0.01 conf it did not crash. thank you very much!

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has been merged in https://github.com/ultralytics/ultralytics/pull/20923, thanks to the efforts of Laughing-q and contributions from glenn-jocher.

Key updates in this release (ultralytics 8.3.150) include:
- Streamlining the validation process by removing the unused progress bar parameter from all validator class constructors.
- Adjusting the default confidence threshold for oriented bounding box (OBB) validation tasks to 0.01, which helps reduce memory usage and improve stability when working with rotated bounding boxes.
- Explicitly setting the confidence threshold to 0.001 in the benchmarking utility to ensure consistent and reproducible performance comparisons.
- No user-facing changes are expected, so typical workflows should remain unaffected.

To check if the changes resolve your issue, you can upgrade to the latest version using:
```
pip install -U ultralytics>=8.3.150
```
Alternatively, you can try the latest main branch directly:
```
pip install git+https://github.com/ultralytics/ultralytics.git@main
```
Or, if you prefer, simply wait for the next official PyPI release.

Feedback is greatly appreciated—please let us know if this update resolves your issue or if any problems persist. Thank you for reporting this and helping improve Ultralytics! 🙏
