### ISSUE TITLE
Nan results when training with GPU

### ISSUE THREAD

**Issue by Abecadarian** [ultralytics/ultralytics#2263]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I've been trying to train a segmentation model using my NVIDIA GeForce GTX 1650 GPU, and it keeps giving me nan results for the segmentation losses even when I disable AMP:

[results.csv](https://github.com/ultralytics/ultralytics/files/11335450/results.csv)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@MarcBresson thanks for sharing your solution! It's great to hear that you were able to resolve the issue by reverting to CUDA 11.7. This might help other users who encounter similar problems. If you have any other questions or need further assistance, feel free to ask!
