### ISSUE TITLE
batch=-1 gives out cuda.OutOfMemoryError in ver-8.0.88 but not in ver-8.0.26

### ISSUE THREAD

**Issue by AzwadFawadHasan** [ultralytics/ultralytics#2274]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I couldn't start training my dataset on batch=-1(auto) on the latest ultralytics edition. But using the older version 8.0.26 allows me to run the training command. See the pictures below

![image](https://user-images.githubusercontent.com/106096161/234718421-a1739de9-9c72-4df0-99a2-03930c854eb7.png)
gives error 
![image](https://user-images.githubusercontent.com/106096161/234718492-74dcdc5a-d5df-42c8-8ec8-3539e2d34f77.png)

rolling back to the older version 8.0.26
![image](https://user-images.githubusercontent.com/106096161/234718622-0165cf41-0558-47b8-8af1-30b573fd05a2.png)
runs the training at a healthy it/s
![image](https://user-images.githubusercontent.com/106096161/234718686-3a6814ea-b02f-4b9f-a5b3-e867935499b8.png)

### Environment

-yolo version 8.0.88
-Windows 10
-3050ti 4GB laptop gpu, 32GB RAM, 5700H cpu

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@glenn-jocher did something change regarding autobatch recently?

**Comment by pderrenger** [comment]
@AzwadFawadHasan you can modify the autobatch fraction here in ultralytics/yolo/utils/autobatch, by default it's set to attempt to use 2/3 of your CUDA memory, but it's experiment and may fail.


`def autobatch(model, imgsz=640, fraction=0.67, batch_size=16):
`

**Comment by AzwadFawadHasan** [comment]
@pderrenger Alright I'll take a look

**Comment by glenn-jocher** [comment]
Thank you for your report @AzwadFawadHasan. We appreciate it. It seems that autobatch is behaving differently in YOLOv8 version 8.0.88 compared to the older version 8.0.26. A potential solution to this problem could be modifying autobatch fraction in the `utils/autobatch.py` file. By default, the fraction is set to 2/3 of the available CUDA memory. However, this is subject to experimentation and may not work in some cases. We'll investigate this further and update you as soon as possible.

**Comment by AzwadFawadHasan** [comment]
@glenn-jocher  alright. Thanks!

**Comment by kvnptl** [comment]
`batch=-1`, AutoBatch, works for me on a single GPU. 

But for multi-GPU, it gave the error `ValueError: batch_size should be a positive integer value, but got batch_size=-1`

**Comment by glenn-jocher** [comment]
@kvnptl thank you for bringing this to our attention. `batch=-1` is used to enable Autobatch which dynamically adjusts the batch size to fit the available GPU memory per batch. However, it seems that there's an issue with Autobatch on multi-GPU systems that is resulting in the `ValueError` you encountered. We apologize for any inconvenience this may have caused. 

Our team will look into this issue and work towards resolving it. In the meantime, you can try setting the batch size to a positive integer value to avoid this error. We appreciate your contributions to YOLOv8 and will update this issue as soon as we have a solution.

If you have any further questions or concerns, please don't hesitate to ask. We're always here to help.
