### ISSUE TITLE
PyTorch reserves a lot of memory, causing torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by SixtyTrees** [ultralytics/ultralytics#2292]
I train my detection model with the following command:

yolo detect train data=my.yaml model=yolov8n.yaml epochs=100 imgsz=384

And run into torch.cuda.OutOfMemoryError

$USER$\anaconda3\envs\ultralytics\lib\site-packages\ultralytics\yolo\utils\tal.py", line 186, in select_topk_candidates
    is_in_topk = torch.zeros(metrics.shape, dtype=torch.long, device=metrics.device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 6.00 GiB total capacity; 1.80 GiB already allocated; 0 bytes free; 4.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I've changes dome parameters mask_ratio: 1 (my objects are small), batch: 2, workers: 1  

Which settings should I change to allocate less memory to pytorch?

**Comment by SixtyTrees** [comment]
@glenn-jocher Batch size is already set to `batch: 2` and image size to 384 (works with img size 256). I am training with the latest version of PyTorch 2.0 (it seems that PyTorch 1.x (it seems that PyTorch 1.x consumes less memory). I don't have any other apps that consume GPU (as evident from nvidia-smi).

Should I change `nbs: 64` to something lower? Should I change any other parameters? Are there other ways to decrease the size of memory, allocated to PyTorch. 
I am concerned that my models (I have 5 of them) might not fit in prod memory (2x8Gb).

**Comment by stastatun** [comment]
What is the number of labels per image of your training data? I had the same issue with training when my images had a very large amount of small objects. 

My workaround was to split the images into smaller parts for training, then to export the model with production parameters after.

**Comment by glenn-jocher** [comment]
@SixtyTrees thank you for reaching out to us. To help us provide a solution to your memory allocation error, could you please let us know how many labels per image are in your training data? Large numbers of small objects in your images can greatly increase the model's memory requirements during training. If you have many labels in your images, splitting the images into smaller parts for training and exporting the model with production parameters after could be a solution to train with less memory. Please let us know if this solution works for you, and if not, we can explore other solutions.

**Comment by SixtyTrees** [comment]
Solved it by setting 
workspace: 1  # TensorRT: workspace size (GB)
instead of 4. Not sure, why Ultralytics allocates 4 Gb for workspace byh default (sounds like a lot).

**Comment by glenn-jocher** [comment]
@SixtyTrees thank you for reaching out to us with your solution to the Ultralytics YOLOv8 training memory allocation issue!

Setting `workspace: 1` instead of the default `workspace: 4` for TensorRT is a valid solution to reducing memory allocation during training.

As for your question regarding the optimization algorithm, please note that the choice of optimizer depends on the data and model architecture. While Adam optimization performs well on some tasks, in some cases (such as image classification tasks) Stochastic Gradient Descent (SGD) with momentum has been shown to be more effective. However, the optimal choice of optimization algorithm ultimately depends on your specific use case, and we recommend experimenting with various options to determine the best performance.

Let us know if you have any further questions or issues, and we'll be happy to help!
