### ISSUE TITLE
SAM3 inference fails on MPS (Mac M2) due to pin_memory() usage

### ISSUE THREAD

**Issue by codingbugss** [ultralytics/ultralytics#22954]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

# Bug Description
I am trying to use the new SAM3 model on an Apple M2 chip (Mac) with device='mps'.
I encountered a RuntimeError located in ultralytics/models/sam/sam3/geometry_encoders.py.
The error occurs because pin_memory() followed by .to() behaves differently on the PyTorch MPS backend compared to CUDA, causing a storage conflict.
To Reproduce
Run the following code on a Mac with Apple Silicon:

```python
from ultralytics.models.sam import SAM3SemanticPredictor

# Initialize predictor
predictor = SAM3SemanticPredictor(
    overrides=dict(
        task="segment",
        mode="predict",
        model="sam3.pt", 
        device="mps"
    ),
    bpe_path="bpe_simple_vocab_16e6.txt.gz"
)

predictor.set_image("test_image.jpg")

# Trigger inference
results = predictor(
    text=["person"],
    device="mps"
)
```

### Environment

❯ yolo checks
Ultralytics 8.3.237 🚀 Python-3.12.11 torch-2.9.1 CPU (Apple M2)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 391.1/460.4 GB disk)

OS                     macOS-26.1-arm64-arm-64bit
Environment            Darwin
Python                 3.12.11
Install                pip
Path                   /Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics
RAM                    16.00 GB
Disk                   391.1/460.4 GB
CPU                    Apple M2
CPU count              8
GPU                    None
GPU count              None
CUDA                   None

numpy                  ✅ 2.3.5>=1.23.0
matplotlib             ✅ 3.10.8>=3.3.0
opencv-python          ✅ 4.11.0.86>=4.6.0
pillow                 ✅ 12.0.0>=7.1.2
pyyaml                 ✅ 6.0.3>=5.3.1
requests               ✅ 2.32.5>=2.23.0
scipy                  ✅ 1.16.3>=1.4.1
torch                  ✅ 2.9.1>=1.8.0
torch                  ✅ 2.9.1!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision            ✅ 0.24.1>=0.9.0
psutil                 ✅ 7.1.3>=5.8.0
polars                 ✅ 1.36.1>=0.20.0
ultralytics-thop       ✅ 2.0.18>=2.0.18

### Minimal Reproducible Example

```python
from ultralytics.models.sam import SAM3SemanticPredictor

# Initialize predictor
predictor = SAM3SemanticPredictor(
    overrides=dict(
        task="segment",
        mode="predict",
        model="sam3.pt", 
        device="mps"
    ),
    bpe_path="bpe_simple_vocab_16e6.txt.gz"
)

predictor.set_image("test_image.jpg")

# Trigger inference
results = predictor(
    text=["person"],
    device="mps"
)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @codingbugss, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com/) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

This is an automated response 🤖—an Ultralytics engineer will also assist soon ✅

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example/) to help us debug it. You’ve already shared a solid MRE (thank you!)—if you can, please also include:
-Exact traceback text (full error + stack) from the failing run
-Whether the failure happens with `device="mps"` only, and if `device="cpu"` behaves differently on the same machine
-The exact `sam3.pt` source you’re using and confirmation the `bpe_simple_vocab_16e6.txt.gz` path is correct

If this is a custom training ❓ Question, please provide as much information as possible, including dataset image examples and training logs, and verify you are following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com/). Or dive into threads on our [Subreddit](https://www.reddit.com/r/Ultralytics/) to share knowledge with the community.

## Upgrade

Upgrade to the latest `ultralytics` package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/) to verify your issue is not already resolved in the latest version:

```bash
pip install -U ultralytics
```

## Environments

YOLO may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by codingbugss** [comment]
Trackback like this:

```
Ultralytics 8.3.237 🚀 Python-3.12.11 torch-2.9.1 MPS (Apple M2)
WARNING ⚠️ imgsz=[640] must be multiple of max stride 14, updating to [644]

Traceback (most recent call last):
  File "/Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/with_text.py", line 26, in <module>
    results = predictor(
              ^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 225, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 38, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 329, in stream_inference
    preds = self.inference(im, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 2316, in inference
    return self._inference_features(features, *prompts, text=text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 2268, in _inference_features
    outputs = self.model.forward_grounding(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/sam3/sam3_image.py", line 312, in forward_grounding
    prompt, prompt_mask = self._encode_prompt(img_feats, img_pos_embeds, vis_feat_sizes, geometric_prompt)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/sam3/sam3_image.py", line 129, in _encode_prompt
    geo_feats, geo_masks = self.geometry_encoder(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/sam3/geometry_encoders.py", line 385, in forward
    final_embeds, final_mask = self._encode_boxes(
                               ^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/sam3/geometry_encoders.py", line 291, in _encode_boxes
    scale = scale.pin_memory().to(device=boxes_xyxy.device, non_blocking=True)
            ^^^^^^^^^^^^^^^^^^
RuntimeError: Attempted to set the storage of a tensor on device "cpu" to a storage on different device "mps:0".  This is no longer allowed; the devices must match.
```

**Comment by Y-T-G** [comment]
@codingbugss Does this work?

```
pip install git+https://github.com/ultralytics/ultralytics@mps-sam3
```

**Comment by codingbugss** [comment]
@Y-T-G This now works properly. After checking the differences from the main branch, I found that the issue was resolved by removing the pin_memory() method from the line:
```
scale = scale.pin_memory().to(device=boxes_xyxy.device, non_blocking=True)
```

- When no device is specified, the program runs without errors:
```
image 1/1 /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/test_image.jpg: 644x644 6 childs, 595.3ms
Speed: 1.7ms preprocess, 595.3ms inference, 4.7ms postprocess per image at shape (1, 3, 644, 644)
```

- However, when specifying device='mps', another error occurs:
```
Ultralytics 8.3.237 🚀 Python-3.12.11 torch-2.9.1 MPS (Apple M2)
WARNING ⚠️ imgsz=[640] must be multiple of max stride 14, updating to [644]

Traceback (most recent call last):
  File "/Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/with_text.py", line 26, in <module>
    results = predictor(
              ^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 225, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Results into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 38, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 330, in stream_inference
    preds = self.inference(im, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 2316, in inference
    return self._inference_features(features, *prompts, text=text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 2268, in _inference_features
    outputs = self.model.forward_grounding(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/ultralytics/models/sam/sam3/sam3_image.py", line 294, in forward_grounding
    prompt, prompt_mask = self._encode_prompt(img_feats, img_pos_embeds, vis_feat_sizes, geometric_prompt)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/ultralytics/models/sam/sam3/sam3_image.py", line 111, in _encode_prompt
    geo_feats, geo_masks = self.geometry_encoder(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/ultralytics/models/sam/sam3/geometry_encoders.py", line 398, in forward
    final_embeds, final_mask = concat_padded_sequences(final_embeds, final_mask, cls, cls_mask)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/test/lib/python3.12/site-packages/ultralytics/models/sam/sam3/geometry_encoders.py", line 45, in concat_padded_sequences
    torch._assert_async(is_right_padded(mask1))
NotImplementedError: The operator 'aten::_assert_async' is not currently implemented for the MPS device. If you want this op to be considered for addition please comment on https://github.com/pytorch/pytorch/issues/141287 and mention use-case, that resulted in missing op as well as commit hash 5811a8d7da873dd699ff6687092c225caffcf1bb. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

This appears to be a PyTorch MPS fallback issue. After adding the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1`, the program runs successfully—but the speed is even slower than running on the CPU by default:
```
image 1/1 /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/test_image.jpg: 644x644 6 childs, 3453.2ms
Speed: 136.8ms preprocess, 3453.2ms inference, 34.0ms postprocess per image at shape (1, 3, 644, 644)
```

**In summary: **The program can now output results normally, but it feels like the MPS performance is not being fully utilized. There seems to be an underlying issue that needs to be addressed.

**Comment by Y-T-G** [comment]
@codingbugss I updated it. Can you try again?

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has now been merged in the linked PR: [Fix SAM3 inference with MPS](https://github.com/ultralytics/ultralytics/pull/22956) ✅

### What changed that may resolve this
This PR focuses on making SAM3 inference more stable (especially on MPS) by tightening up tensor layout and conversions during attention:

- **Forces contiguous tensors before attention** (e.g. `self.norm1(tgt).contiguous()`), which can prevent edge-case failures or slowdowns caused by non-contiguous memory.
- **Avoids repeated dtype conversions** by converting `memory` once to the target dtype, making it contiguous, and reusing it for both cross-attention `key` and `value`.
- **Makes padding checks stricter and clearer** by replacing `torch._assert_async(...)` with an explicit `torch._assert(..., "Mask is not right padded")`, improving determinism and debuggability.
- **Removes unnecessary pinned-memory usage** for a small CPU tensor (`scale`) before moving it to device, simplifying the transfer path.

### Credit
Big thanks to @Y-T-G for the fix and improvements, and to everyone who helped report and validate the behavior.

### How to test the fix
If already using the PyPI package, testing against the latest `main` is the fastest way to confirm:

- Install from `main`:
  - `pip install -U git+https://github.com/ultralytics/ultralytics.git@main`

Alternatively, it’s also fine to **wait for the next official PyPI release**, which should include this merge.

### Feedback requested
If possible, please retest SAM3 inference on the same MPS setup and share whether this resolves the issue (and any logs/tracebacks if it still reproduces).

Thanks 🙏 for reporting this—further feedback is welcome if anything persists.

**Comment by codingbugss** [comment]
successfully resolved this issue—great job! The test results are as follows:
- When no device is specified:
```
Ultralytics 8.3.239 🚀 Python-3.12.11 torch-2.9.1 CPU (Apple M2)
WARNING ⚠️ imgsz=[640] must be multiple of max stride 14, updating to [644]

image 1/1 /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/test_image.jpg: 644x644 6 childs, 7069.1ms
Speed: 3.1ms preprocess, 7069.1ms inference, 8.0ms postprocess per image at shape (1, 3, 644, 644)
```

- When specifying device='mps':
```
Ultralytics 8.3.239 🚀 Python-3.12.11 torch-2.9.1 MPS (Apple M2)
WARNING ⚠️ imgsz=[640] must be multiple of max stride 14, updating to [644]

image 1/1 /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/test_image.jpg: 644x644 6 childs, 591.5ms
Speed: 177.0ms preprocess, 591.5ms inference, 62.3ms postprocess per image at shape (1, 3, 644, 644)
```

**Comment by glenn-jocher** [comment]
Thanks for retesting and confirming it’s resolved on `8.3.239`—those timings with `device="mps"` indicate it’s staying on MPS (and you shouldn’t need `PYTORCH_ENABLE_MPS_FALLBACK=1` anymore); if you hit any new MPS-only operator gaps or performance regressions, please open a new issue with the full traceback plus `yolo checks` output, and in the meantime the current usage notes/examples are in the [SAM 3 docs](https://docs.ultralytics.com/models/sam-3/).
