### ISSUE TITLE
RuntimeError: repeat() Not Supported for Complex on Apple M2 with SAM3VideoSemanticPredictor

### ISSUE THREAD

**Issue by codingbugss** [ultralytics/ultralytics#22967]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I encounter a RuntimeError related to complex number handling in repeat() when using SAM3VideoSemanticPredictor for video segmentation on an Apple M2 device with MPS backend. The error occurs during rotary position encoding processing in the memory attention module.

Traceback like this:
```
Ultralytics 8.3.239 🚀 Python-3.12.11 torch-2.9.1 MPS (Apple M2)
WARNING ⚠️ imgsz=[640] must be multiple of max stride 14, updating to [644]
video 1/1 (frame 1/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 6960.4ms
Traceback (most recent call last):
  File "/Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/with_video.py", line 19, in <module>
    for r in results:
             ^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 59, in generator_context
    response = gen.send(request)
               ^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 330, in stream_inference
    preds = self.inference(im, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 2593, in inference
    return self._run_single_frame_inference(frame, reverse=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 2663, in _run_single_frame_inference
    ) = self._det_track_one_frame(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 2796, in _det_track_one_frame
    tracker_low_res_masks_global, tracker_obj_scores_global = self.run_tracker_propagation(
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 2938, in run_tracker_propagation
    obj_ids_local, low_res_masks_local, obj_scores_local = self._propogate_tracker_one_frame_local_gpu(
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 3428, in _propogate_tracker_one_frame_local_gpu
    out_obj_ids, out_low_res_masks, out_obj_scores = self.tracker.propagate_in_video(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 2414, in propagate_in_video
    current_out = self._run_single_frame_inference(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/predict.py", line 1358, in _run_single_frame_inference
    current_out = self.model.track_step(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/modules/sam.py", line 942, in track_step
    sam_outputs, _, _ = self._track_step(
                        ^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/modules/sam.py", line 868, in _track_step
    pix_feat = self._prepare_memory_conditioned_features(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/modules/sam.py", line 783, in _prepare_memory_conditioned_features
    pix_feat_with_mem = self.memory_attention(
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/modules/memory_attention.py", line 284, in forward
    output = layer(
             ^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/modules/memory_attention.py", line 163, in forward
    tgt = self._forward_ca(tgt, memory, query_pos, pos, num_k_exclude_rope)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/modules/memory_attention.py", line 133, in _forward_ca
    tgt2 = self.cross_attn_image(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/modules/blocks.py", line 440, in forward
    q, k[:, :, :num_k_rope] = apply_rotary_enc(
                              ^^^^^^^^^^^^^^^^^
  File "/Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics/models/sam/modules/utils.py", line 215, in apply_rotary_enc
    freqs_cis = freqs_cis.repeat(*([1] * (freqs_cis.ndim - 2)), r, 1)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: repeat(): Not supported for complex yet!
```

### Environment

❯ yolo checks
Ultralytics 8.3.239 🚀 Python-3.12.11 torch-2.9.1 CPU (Apple M2)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 380.6/460.4 GB disk)

OS                     macOS-26.1-arm64-arm-64bit
Environment            Darwin
Python                 3.12.11
Install                pip
Path                   /Users/xiaobolingyu/uvenvs/yolo_sam3/lib/python3.12/site-packages/ultralytics
RAM                    16.00 GB
Disk                   380.6/460.4 GB
CPU                    Apple M2
CPU count              8
GPU                    None
GPU count              None
CUDA                   None

numpy                  ✅ 2.3.5>=1.23.0
matplotlib             ✅ 3.10.8>=3.3.0
opencv-python          ✅ 4.11.0.86>=4.6.0
pillow                 ✅ 12.0.0>=7.1.2
pyyaml                 ✅ 6.0.3>=5.3.1
requests               ✅ 2.32.5>=2.23.0
scipy                  ✅ 1.16.3>=1.4.1
torch                  ✅ 2.9.1>=1.8.0
torch                  ✅ 2.9.1!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision            ✅ 0.24.1>=0.9.0
psutil                 ✅ 7.1.3>=5.8.0
polars                 ✅ 1.36.1>=0.20.0
ultralytics-thop       ✅ 2.0.18>=2.0.18

### Minimal Reproducible Example

```
from ultralytics.models.sam import SAM3VideoSemanticPredictor

# Initialize semantic video predictor
overrides = dict(
    conf=0.25, 
    task="segment", 
    mode="predict", 
    imgsz=640, 
    model="/Users/xiaobolingyu/workspace/models/sam3/sam3.pt", 
    half=True, 
    device="mps"
)
predictor = SAM3VideoSemanticPredictor(overrides=overrides)

# Track concepts using text prompts
results = predictor(source="bedroom.mp4", text=["child"], stream=True, save=True)

# Process results
for r in results:
    # r.show()  # Display frame with tracked objects
    pass
```

### Additional

I modified Line 215 in sam/modules/utils.py by adding a device check for MPS, as shown below:
```
if freqs_cis.device.type == 'mps':
    freqs_cis = freqs_cis.cpu().repeat(*([1] * (freqs_cis.ndim - 2)), r, 1).to(freqs_cis.device)
else:
    freqs_cis = freqs_cis.repeat(*([1] * (freqs_cis.ndim - 2)), r, 1)
```

After this change, the code runs successfully, with the following logs:
```
Ultralytics 8.3.239 🚀 Python-3.12.11 torch-2.9.1 MPS (Apple M2)
WARNING ⚠️ imgsz=[640] must be multiple of max stride 14, updating to [644]
video 1/1 (frame 1/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 5236.0ms
video 1/1 (frame 2/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2211.3ms
video 1/1 (frame 3/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2275.7ms
video 1/1 (frame 4/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2225.9ms
video 1/1 (frame 5/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2180.3ms
video 1/1 (frame 6/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2231.8ms
```

Judging from the runtime, it seems that MPS does not support repeat() on complex tensors. The workaround of moving the tensor to CPU for the repeat operation and then transferring it back to MPS does work, but it introduces noticeable time overhead. Do you have any alternative solutions?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @codingbugss, thank you for your interest in Ultralytics 🚀! This is an automated response to help us triage your issue quickly—an Ultralytics engineer will also assist soon 🙌

We recommend a visit to the [Docs](https://docs.ultralytics.com/) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example/) to help us debug it.✅ Thanks for already sharing an MRE and full traceback—could you also add a small self-contained repro that doesn’t depend on a local model/video path (or attach a tiny sample video + exact model name/weights used), so we can reproduce this MPS complex `repeat()` behavior reliably on our side? 🧪

If this is a custom training ❓ Question, please provide as much information as possible, including dataset image examples and training logs, and verify you are following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com/). Or dive into threads on our [Subreddit](https://www.reddit.com/r/Ultralytics/) to share knowledge with the community.

## Upgrade

Upgrade to the latest `ultralytics` package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/) to verify your issue is not already resolved in the latest version:

```bash
pip install -U ultralytics
```

## Environments

YOLO may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Y-T-G** [comment]
Can you try ?

`pip install git+https://github.com/ultralytics/ultralytics@sam3vid-mps`

**Comment by codingbugss** [comment]
@Y-T-G 
it works:
```
Ultralytics 8.3.239 🚀 Python-3.12.11 torch-2.9.1 MPS (Apple M2)
WARNING ⚠️ imgsz=[640] must be multiple of max stride 14, updating to [644]
video 1/1 (frame 1/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 4929.2ms
video 1/1 (frame 2/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2183.3ms
video 1/1 (frame 3/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2195.5ms
video 1/1 (frame 4/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2133.6ms
video 1/1 (frame 5/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2190.7ms
video 1/1 (frame 6/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2220.6ms
video 1/1 (frame 7/200) /Users/xiaobolingyu/workspace/src/python/tests/test_yolosam3/bedroom.mp4: 644x644 2 0s, 2586.9ms
```

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has now been merged in [PR #22968](https://github.com/ultralytics/ultralytics/pull/22968) (`ultralytics 8.3.240` SAM3 Apple MPS tensor `repeat()` fixes) by @Y-T-G, with contributions from @glenn-jocher.

### What changed (and why it may fix this)
This PR targets Apple Silicon / PyTorch MPS failures related to SAM rotary embeddings, specifically where MPS can error on complex-tensor `repeat()` calls:

- **Fixes `apply_rotary_enc()`** in `ultralytics/models/sam/modules/utils.py` to avoid **unsupported complex `repeat()` on MPS**.
- **Only repeats key frequencies when needed**: the repeat operation is now conditional and runs only when the computed repeat factor `r > 1` (avoids unnecessary work when `r <= 1`).
- **MPS-safe repeat path**: on MPS, it converts complex tensors to real (`view_as_real`), repeats safely, then converts back (`view_as_complex`).
- **Non-MPS behavior preserved**: other devices keep the original complex `repeat()` path.
- Also includes a **version bump to `8.3.240`**.

### How to test the fix
Any of the following options should help confirm whether this resolves the problem:

- Install the version that includes the changes:
  - `pip install -U "ultralytics>=8.3.240"`
- Or test the latest `main` directly:
  - `pip install -U git+https://github.com/ultralytics/ultralytics.git@main`
- Alternatively, it’s also fine to **wait for the next official PyPI release** if a fresh build is preferred.

### Feedback request
If possible, share whether the issue is resolved after upgrading (and include any relevant logs/stack traces if it still reproduces). 🙏 Thanks for reporting this—additional details are always welcome if anything persists.
