### ISSUE TITLE
sam3 error

### ISSUE THREAD

**Issue by ZLT-a-LL** [ultralytics/ultralytics#23119]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Why does the prediction instance of sam3 fail to be initialized in the class, and calling it in a class function results in an error? Furthermore, loading predictions entirely within a thread also encounters the same error

### Environment

(yolo11) PS E:\A_worker\W_XM\ZLT_api_test\ai-api-server8001> yolo checks
Ultralytics 8.3.248  Python-3.12.12 torch-2.9.1+cu128 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 8192MiB)
Setup complete  (20 CPUs, 31.7 GB RAM, 838.9/953.9 GB disk)

OS                     Windows-11-10.0.26100-SP0
Environment            Windows
Python                 3.12.12
Install                pip
Path                   E:\Miniconda\envs\yolo11\Lib\site-packages\ultralytics
RAM                    31.71 GB
Disk                   838.9/953.9 GB
CPU                    12th Gen Intel Core i7-12700H
CPU count              20
GPU                    NVIDIA GeForce RTX 3050 Ti Laptop GPU, 8192MiB
GPU count              1
CUDA                   12.8

numpy                   2.2.6>=1.23.0
matplotlib              3.10.8>=3.3.0
opencv-python           4.12.0.88>=4.6.0
pillow                  12.0.0>=7.1.2
pyyaml                  6.0.3>=5.3.1
requests                2.32.5>=2.23.0
scipy                   1.16.3>=1.4.1
torch                   2.9.1+cu128>=1.8.0
torch                   2.9.1+cu128!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision             0.24.1+cu128>=0.9.0
psutil                  7.1.3>=5.8.0
polars                  1.36.1>=0.20.0
ultralytics-thop        2.0.18>=2.0.18
(yolo11) PS E:\A_worker\W_XM\ZLT_api_test\ai-api-server8001> 

### Minimal Reproducible Example

import threading

from ultralytics.models.sam import SAM3SemanticPredictor
import time

import logging
import numpy as np

class SAM3YOLO:
    def __init__(self):
        # self.overrides = dict(
        #     conf=0.7,
        #     task="segment",
        #     mode="predict",
        #     imgsz=640,
        #     model=r"E:\A_worker\W_XM\yolo11_sam3\models\sam3\sam3.pt",
        #     half=True,  # Use FP16 for faster inference
        #     device="0",
        #     save=False,
        #     # iou=0.5,
        # )
        self.text_prompts="The person holding the fishing rod"
        #
        # self.predictor = SAM3SemanticPredictor(overrides=self.overrides)
        #
        self._warm_up_model()
        #
        # self.predictor.set_image(r"E:\A_worker\W_XM\ZLT_api_test\ai-api-server8001\test_videos\2.JPG")

        for i in range(50):
            time.sleep(1)
            print(f'主进程执行{i}秒')
        # results = self.predictor(self.text_prompts )

    def _warm_up_model(self):
        """异步预热SAM3模型，不阻塞主进程"""

        def warm_up_task():
            """预热任务函数"""
            try:

                overrides = dict(
                    conf=0.7,
                    task="segment",
                    mode="predict",
                    imgsz=640,
                    model=r"E:\A_worker\W_XM\yolo11_sam3\models\sam3\sam3.pt",
                    half=True,  # Use FP16 for faster inference
                    device="0",
                    save=False,
                    # iou=0.5,
                )
                logging.info("开始异步预热SAM3模型...")

                self.predictor = SAM3SemanticPredictor(overrides=overrides)
                # 创建一张简单的测试图片（全黑或全白）
                warm_up_image = np.zeros((640, 640, 3), dtype=np.uint8)
                # 或者使用白色背景
                # warm_up_image = np.ones((640, 640, 3), dtype=np.uint8) * 255

                # 执行预热推理

                start_time = time.time()
                self.predictor.set_image(warm_up_image)
                results = self.predictor(text=self.text_prompts)
                warmup_time = time.time() - start_time

                logging.info(f"SAM3模型预热完成，耗时: {warmup_time:.2f}秒")

                # 记录预热结果状态
                if hasattr(results[0], 'boxes') and results[0].boxes is not None:
                    logging.info(f"预热检测到 {len(results[0].boxes)} 个目标")
                else:
                    logging.info("预热未检测到目标（正常情况）")

            except Exception as e:
                logging.error(f"SAM3模型预热失败: {e}")

        # 创建并启动预热线程
        warm_up_thread = threading.Thread(
            target=warm_up_task,
            name="SAM3-WarmUp-Thread",
            daemon=True  # 设置为守护线程，主进程退出时自动结束
        )
        warm_up_thread.start()
        # warm_up_task()

        # 不等待线程完成，立即返回
        logging.info("已启动SAM3模型预热线程，主进程继续执行...")
if __name__ == '__main__':

    predict=SAM3YOLO()

### Additional

error：C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:111: block: [10,0,0], thread: [29,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:111: block: [10,0,0], thread: [30,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:111: block: [10,0,0], thread: [31,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
ERROR:root:SAM3模型预热失败: CUDA error: device-side assert triggered
Search for `cudaErrorAssert' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @ZLT-a-LL, thank you for your interest in Ultralytics 🚀! This is an automated response to help you get unblocked quickly—an Ultralytics engineer will also assist soon.

We recommend a visit to the [Docs](https://docs.ultralytics.com/) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example/) to help us debug it.  
You already shared a great start—could you please tighten it into an MRE that:
-uses only a single image and a minimal prompt
-includes the exact `ultralytics` version (`yolo checks` output is perfect ✅)
-includes the full traceback (not just the CUDA assertion lines)
-avoids extra threading logic if possible, then provides a second MRE that *only* adds threading (since your report involves initialization + threads) 🧵

If this is a custom training ❓ Question, please provide as much information as possible, including dataset image examples and training logs, and verify you are following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com/). Or dive into threads on our [Subreddit](https://www.reddit.com/r/Ultralytics/) to share knowledge with the community.

## Upgrade

Upgrade to the latest `ultralytics` package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/) to verify your issue is not already resolved in the latest version:

```bash
pip install -U ultralytics
```

## Environments

YOLO may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Y-T-G** [comment]
You can see the reason for the error by running it on CPU

**Comment by ZLT-a-LL** [comment]
This is an error reported on the CPU：SAM3模型预热失败: index 1 is out of bounds for dimension 0 with size 1

**Comment by ZLT-a-LL** [comment]
I tried loading the sam3 model directly in the main process for image inference, and it worked fine. However, when I used it in a class or used a separate thread for inference, I encountered this error

**Comment by Y-T-G** [comment]
What's the full traceback of error

**Comment by ZLT-a-LL** [comment]
index 1 is out ofbounds forDimension 0 with size 1
Only the above line reports an error, but I can use the sam3 library of meta to load models in threads and classes for inference, which is completely normal

**Comment by Y-T-G** [comment]
You should remove try except and get the full traceback 

```
except Exception as e:
            logging.error(f"SAM3模型预热失败: {e}")
```

**Comment by ZLT-a-LL** [comment]
Exception in thread SAM3-WarmUp-Thread:
Traceback (most recent call last):
  File "E:\Miniconda\envs\yolo11\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "E:\Miniconda\envs\yolo11\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "E:\A_worker\W_XM\ZLT_api_test\ai-api-server8001\predict_sam3_yolo_img_text.py", line 147, in warm_up_task
    results = thread_local_predictor(text="The person holding the fishing rod")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Miniconda\envs\yolo11\Lib\site-packages\ultralytics\engine\predictor.py", line 225, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Results into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Miniconda\envs\yolo11\Lib\site-packages\torch\utils\_contextlib.py", line 38, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "E:\Miniconda\envs\yolo11\Lib\site-packages\ultralytics\engine\predictor.py", line 330, in stream_inference
    preds = self.inference(im, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Miniconda\envs\yolo11\Lib\site-packages\ultralytics\models\sam\predict.py", line 2333, in inference
    return self._inference_features(features, *prompts, text=text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Miniconda\envs\yolo11\Lib\site-packages\ultralytics\models\sam\predict.py", line 2285, in _inference_features
    outputs = self.model.forward_grounding(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Miniconda\envs\yolo11\Lib\site-packages\ultralytics\models\sam\sam3\sam3_image.py", line 297, in forward_grounding
    txt_feats = backbone_out["language_features"][:, text_ids]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
IndexError: index 1 is out of bounds for dimension 0 with size 1

**Comment by ZLT-a-LL** [comment]
It is the latest ultralytics library

**Comment by glenn-jocher** [comment]
The traceback is consistent with passing `text` as a plain string: `SAM3SemanticPredictor` expects `text: list[str]`, and when a `str` is passed it can create a mismatch between `text_ids` and the cached `language_features`, leading to the out-of-bounds index in `forward_grounding` (see the `text` typing/handling in the [SAM3 predictor reference](https://docs.ultralytics.com/reference/models/sam/predict/) and how classes/text embeddings are set in [SAM3 `set_classes()`](https://docs.ultralytics.com/reference/models/sam/sam3/sam3_image/)). Please call it like this (works the same in threads/classes, as long as you don’t share a single predictor instance across threads):

```python
self.text_prompts = ["The person holding the fishing rod"]  # list[str], not str
results = self.predictor(text=self.text_prompts)
```

**Comment by ZLT-a-LL** [comment]
Okay, thank you. The problem has been solved

**Comment by glenn-jocher** [comment]
Glad that fixed it—if anything else comes up (especially threading-related), please open a new issue with the full text traceback and your `yolo checks` output so we can take a look.
