### ISSUE TITLE
Multi-GPU DDP training hangs before first validation on YOLO26 (regression in 8.4.40+)

### ISSUE THREAD

**Issue by hitimr** [ultralytics/ultralytics#24536]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train, Multi-GPU, Val

### Bug

Multi-GPU (DDP) training with `yolo26s.pt` hangs silently at ~95% of the first epoch's training batches, immediately before validation starts. The hang is fully deterministic across multiple restarts (identical failure point on every run) and reproduces with two different `batch` values — the failure index scales with batches per epoch:

- `batch=64` → hangs at **41/43** (95%) of epoch 1
- `batch=32` → hangs at **83/85** (98%) of epoch 1

In both cases, the hang occurs in the last 1–2 training batches, immediately before validation. No traceback is produced — the job stays running indefinitely until SLURM kills it at the wall-time limit.

#### Log evidence

**1. The training reaches the very end of epoch 1, then stops:**

```
Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
1/200      23G      1.663     0.9309   0.003412         40       1600: 95% ━━━━━━━━━━━─ 41/43 2.7it/s 15.5s<0.7s
[no further output for 25+ minutes]
```

**2. `nvidia-smi` during the hang shows all GPUs at 100% util:**

```
+-----------------------------------------+----------------------+----------------------+
|   0  NVIDIA A100-SXM-64GB           On  | 00000000:1D:00.0 Off |                    0 |
| N/A   47C    P0             123W / 474W |  25388MiB / 65536MiB |    100%      Default |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM-64GB           On  | 00000000:56:00.0 Off |                    0 |
| N/A   48C    P0             123W / 474W |  25460MiB / 65536MiB |    100%      Default |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM-64GB           On  | 00000000:8F:00.0 Off |                    0 |
| N/A   47C    P0             118W / 458W |  25460MiB / 65536MiB |    100%      Default |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM-64GB           On  | 00000000:C8:00.0 Off |                    0 |
| N/A   44C    P0              94W / 465W |  25386MiB / 65536MiB |    100%      Default |
+-----------------------------------------+----------------------+----------------------+
```

**3. The 4 DDP ranks show a deadlock pattern under `ps`:**

```
   PID %CPU STAT WCHAN                     CMD
404484 97.6 Rsl  -                         python .../DDP/_temp_*.py    <- rank 0, spinning
404485  7.5 Ssl  hrtimer_nanosleep         python .../DDP/_temp_*.py    <- rank 1, in time.sleep()
404486 96.9 Rsl  -                         python .../DDP/_temp_*.py    <- rank 2, spinning
404487 96.8 Rsl  -                         python .../DDP/_temp_*.py    <- rank 3, spinning
```

Three ranks are pinned at ~97% CPU busy-waiting in NCCL helper threads. One rank is in `hrtimer_nanosleep` — Linux's syscall for Python's `time.sleep()`.

**4. With `val: False` set as a diagnostic test, training proceeds past epoch 1 and the bug manifests differently — as a loud crash in `_handle_nan_recovery` instead of a hang:**

```
[rank1]: Traceback (most recent call last):
[rank1]:   File ".../ultralytics/engine/trainer.py", line 246, in train
[rank1]:     self._do_train()
[rank1]:   File ".../ultralytics/engine/trainer.py", line 537, in _do_train
[rank1]:     if self._handle_nan_recovery(epoch):
[rank1]:   File ".../ultralytics/engine/trainer.py", line 929, in _handle_nan_recovery
[rank1]:     dist.broadcast_object_list(broadcast_list, 0)
[rank1]:   File ".../torch/distributed/distributed_c10d.py", line 3140, in broadcast_object_list
[rank1]:     object_tensor = torch.empty(...)
[rank1]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate more than 1EB memory.
```

**5. Single-GPU training on the same setup works correctly without any issues**:

```
1/200      45.7G      2.467      95.24   0.005723         51       1600: 0% ──── 0/85  17.1s
1/200      45.7G      2.272      93.68   0.004816         49       1600: 1% ──── 1/85 2.7s/it 17.9s<3:43
...
1/200      45.7G      1.739      30.92   0.003737          5       1600: 100% ━━━━━━━━━━━━ 85/85 1.2it/s 1:13
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 9% ━─── 1/11 22.3s/it
[...validation completes normally, training proceeds to epoch 2...]
```

#### Suspected root cause

**PR #24089** ("Per-image precision/recall/F1 support") shipped in **v8.4.40** added a new `dist.gather_object()` call in `models/yolo/detect/val.py::_gather_image_metrics()` to aggregate per-image metrics dictionaries (keyed by image filenames) across DDP ranks during validation. The v8.4.40 release notes explicitly state: *"Multi-GPU validation now correctly gathers and merges image_metrics across ranks"*.

### Environment

Ultralytics 8.4.51 🚀 Python-3.11.7 torch-2.5.1+cu121 CUDA:0 (NVIDIA A100-SXM-64GB, 64945MiB)
                                                     CUDA:1 (NVIDIA A100-SXM-64GB, 64945MiB)
                                                     CUDA:2 (NVIDIA A100-SXM-64GB, 64945MiB)
                                                     CUDA:3 (NVIDIA A100-SXM-64GB, 64945MiB)

OS                     Linux (CINECA Leonardo HPC, boost_usr_prod partition)
Python                 3.11.7
torch                  2.5.1+cu121
torchvision            (matching torch 2.5)
CUDA                   12.1
GPUs                   4× NVIDIA A100-SXM-64GB on a single node
Driver                 535.274.02
NCCL                   bundled with torch 2.5.1
Filesystem             Lustre (shared scratch)

### Minimal Reproducible Example

```python
from ultralytics import YOLO

model = YOLO("yolo26s.pt")
model.train(
    data="data.yaml",
    epochs=10,
    batch=32,
    imgsz=1600,
    device=[0, 1, 2, 3],
    amp=False,
    val=True,
)
```

Dataset: 2696 train / 675 val images, 1 class. Hang reproduces with default config; changing `amp`, `optimizer`, `lr0`, augmentation settings, `workers`, `freeze`, etc. does not affect whether the hang occurs.

### Additional

**Workaround:**

```bash
pip install ultralytics==8.4.8
```

Training proceeds normally on this version with no other changes required.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @hitimr, thank you for the detailed report and for providing a clear reproducible example for this Ultralytics 🚀 bug. This is an automated response to help get things moving quickly, and an Ultralytics engineer will also assist you soon.
We recommend a visit to the [Docs](https://docs.ultralytics.com/) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python) and [CLI](https://docs.ultralytics.com/usage/cli) usage examples and where many of the most common questions may already be answered.
Since this is a 🐛 Bug Report, thank you for already including a [minimum reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example/) along with environment details, logs, and version comparison info. That level of detail is very helpful 🙌
If this is a custom training ❓ Question, please provide as much information as possible, including dataset image examples and training logs, and verify you are following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips).
Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com/). Or dive into threads on our [Subreddit](https://www.reddit.com/r/Ultralytics/) to share knowledge with the community.
## Upgrade
Upgrade to the latest `ultralytics` package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/) to verify your issue is not already resolved in the latest version:
```bash
pip install -U ultralytics
```
## Environments
YOLO may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo26"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>
## Status
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml/badge.svg" alt="Ultralytics CI"></a>
If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes) and [Tasks](https://docs.ultralytics.com/tasks) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by raimbekovm** [comment]
@onuralpszr wdyt?

**Comment by Laughing-q** [comment]
@hitimr currently I just got 2 idle gpus so testing with 2 gpus
```python
from ultralytics import YOLO

model = YOLO("yolo26s.pt")
model.train(
    data="coco128.yaml",
    epochs=10,
    batch=32,
    imgsz=1600,
    device=[2, 3],
    amp=False,
    val=True,
)
```
and I'm not able to reproduce the issue here, training finished from my side:
```text
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2827.7±941.4 MB/s, size: 46.7 KB)
train: Scanning /home/shared/datasets/coco128/labels/train2017... 126 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 128/128 3.7Kit/s 0.0s
train: New cache created: /home/shared/datasets/coco128/labels/train2017.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2102.7±774.3 MB/s, size: 47.3 KB)
val: Scanning /home/shared/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 128/128 13.8Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /home/lq/codes/ultralytics/runs/detect/train-2/labels.jpg...
Image sizes 1600 train, 1600 val
Using 16 dataloader workers
Logging results to /home/lq/codes/ultralytics/runs/detect/train-2
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10      63.8G      1.981      2.437    0.02126         16       1600: 100% ━━━━━━━━━━━━ 4/4 1.9s/it 7.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.9it/s 0.7s
                   all        128        929      0.546      0.473      0.514      0.327

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/10      60.7G      1.843       2.43    0.01901         16       1600: 100% ━━━━━━━━━━━━ 4/4 1.8it/s 2.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s
                   all        128        929       0.54      0.488      0.514      0.324

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/10      60.6G      1.788      2.328    0.01885         16       1600: 100% ━━━━━━━━━━━━ 4/4 1.8it/s 2.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s
                   all        128        929      0.569      0.491       0.53      0.332

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/10      60.6G       1.67      1.995    0.01689         16       1600: 100% ━━━━━━━━━━━━ 4/4 1.8it/s 2.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s
                   all        128        929      0.575        0.5      0.536       0.34

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/10      60.6G      1.707      1.899     0.0187         16       1600: 100% ━━━━━━━━━━━━ 4/4 1.8it/s 2.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s
                   all        128        929      0.571      0.509      0.546      0.351

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/10      60.6G      1.559      1.677    0.01489         16       1600: 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s
                   all        128        929      0.595      0.499      0.557      0.356

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/10      60.9G      1.639      1.858      0.019         16       1600: 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s
                   all        128        929       0.61        0.5      0.565       0.36

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/10      61.1G      1.553      1.657    0.01755         16       1600: 100% ━━━━━━━━━━━━ 4/4 1.8it/s 2.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s
                   all        128        929      0.625      0.498      0.576      0.368

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/10      60.7G      1.608      1.752    0.02086         16       1600: 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s
                   all        128        929      0.623      0.512      0.578      0.368

10 epochs completed in 0.013 hours.
Optimizer stripped from /home/lq/codes/ultralytics/runs/detect/train-2/weights/last.pt, 20.6MB
Optimizer stripped from /home/lq/codes/ultralytics/runs/detect/train-2/weights/best.pt, 20.6MB

```

**Comment by filaPro** [comment]
Same thing actually. ultralytics==8.4.58

**Comment by glenn-jocher** [comment]
Got it, that still points to the DDP validation path in [`BaseTrainer._do_train()`](https://docs.ultralytics.com/reference/engine/trainer#ultralytics.engine.trainer.BaseTrainer._do_train) / [`validate()`](https://docs.ultralytics.com/reference/engine/trainer#ultralytics.engine.trainer.BaseTrainer.validate); please paste your full text logs from all ranks plus `yolo checks` output (or `ultralytics.utils.checks.collect_system_info()` if there may be mixed installs), and confirm whether `val=False` avoids the hang on `8.4.58`.

**Comment by UNeedCryDear** [comment]
The same! The difference is that when training the segmentation model, the process gets stuck at the very first epoch — not even any epoch-related logs are printed. When training the OBB model, however, the error pops up after several epochs. I initially suspected a hardware problem, but after rolling back the software version, training works properly again.
```bash
ubuntu22.04
gpu:H20*8
python:3.12
CUDA:12.9(X),12.8(X)
cudnn:8.9.7(X),9.23(X)
torch:2.7.1_cu128（X）；2.10.0_cu128(X)；2.11.0_cu128(X)
ultralytics :8.4.66(x),8.4.65(x),8.4.37(x),8.4.37(x)
```


@Laughing-q The first few epochs run smoothly for the OBB model, but the error sometimes occurs after  11~20. As for the seg-model, it gets stuck right at the first epoch.
+ seg:

<img width="1003" height="233" alt="Image" src="https://github.com/user-attachments/assets/07c54bc5-2d3c-402a-b0ab-e6b0756851a6" />

<img width="1080" height="485" alt="Image" src="https://github.com/user-attachments/assets/b4f8c8c2-29f5-4e05-a30e-f13dc345f0d1" />

+ OBB

```bash
[rank4]:[E601 07:25:57.393526823 ProcessGroupNCCL.cpp:756] [Rank 4] Work WorkNCCL(SeqNum=201809, OpType=BROADCAST, NumelIn=32, NumelOut=32, Timeout(ms)=10800000) timed out in blocking wait.
[rank4]:[E601 07:25:58.934659321 ProcessGroupNCCL.cpp:684] [Rank 4] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank4]:[E601 07:25:58.934667788 ProcessGroupNCCL.cpp:698] [Rank 4] To avoid data inconsistency, we are taking the entire process down.
[rank4]: Traceback (most recent call last):
[rank4]:   File "/home/ubuntu/.config/Ultralytics/DDP/_temp_3b39_bxa139648849054848.py", line 19, in <module>
[rank4]:     results = trainer.train()
[rank4]:               ^^^^^^^^^^^^^^^
[rank4]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 246, in train
[rank4]:     self._do_train()
[rank4]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 539, in _do_train
[rank4]:     self.metrics, self.fitness = self.validate()
[rank4]:                                  ^^^^^^^^^^^^^^^
[rank4]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 771, in validate
[rank4]:     dist.broadcast(buffer, src=0)
[rank4]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank4]:     return func(*args, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2718, in broadcast
[rank4]:     work.wait()
[rank4]: torch.distributed.DistBackendError: [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=201809, OpType=BROADCAST, NumelIn=32, NumelOut=32, Timeout(ms)=10800000) ran for 10800000 milliseconds before timing out.
     8/1000      18.1G     0.6001     0.3698    0.03362   0.001635         32        640: 100% ━━━━━━━━━━━╸ 4976/4977 2.3it/s 3:26:40<0.4s
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/.config/Ultralytics/DDP/_temp_3b39_bxa139648849054848.py", line 19, in <module>
[rank0]:     results = trainer.train()
[rank0]:               ^^^^^^^^^^^^^^^
[rank0]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 246, in train
[rank0]:     self._do_train()
[rank0]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 486, in _do_train
[rank0]:     self.optimizer_step()
[rank0]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 750, in optimizer_step
[rank0]:     self.scaler.step(self.optimizer)
[rank0]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 461, in step
[rank0]:     retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in _maybe_opt_step
[rank0]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in <genexpr>
[rank0]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank0]:                ^^^^^^^^
[rank0]: RuntimeError: CUDA error: Invalid access of peer GPU memory over nvlink or a hardware error
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/ubuntu/.config/Ultralytics/DDP/_temp_3b39_bxa139648849054848.py", line 19, in <module>
[rank1]:     results = trainer.train()
[rank1]:               ^^^^^^^^^^^^^^^
[rank1]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 246, in train
[rank1]:     self._do_train()
[rank1]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 486, in _do_train
[rank1]:     self.optimizer_step()
[rank1]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 750, in optimizer_step
[rank1]:     self.scaler.step(self.optimizer)
[rank1]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 461, in step
[rank1]:     retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
[rank1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in _maybe_opt_step
[rank1]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in <genexpr>
[rank1]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank1]:                ^^^^^^^^
[rank1]: RuntimeError: CUDA error: Invalid access of peer GPU memory over nvlink or a hardware error
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/ubuntu/.config/Ultralytics/DDP/_temp_3b39_bxa139648849054848.py", line 19, in <module>
[rank3]:     results = trainer.train()
[rank3]:               ^^^^^^^^^^^^^^^
[rank3]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 246, in train
[rank3]:     self._do_train()
[rank3]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 486, in _do_train
[rank3]:     self.optimizer_step()
[rank3]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 750, in optimizer_step
[rank3]:     self.scaler.step(self.optimizer)
[rank3]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 461, in step
[rank3]:     retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
[rank3]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in _maybe_opt_step
[rank3]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in <genexpr>
[rank3]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank3]:                ^^^^^^^^
[rank3]: RuntimeError: CUDA error: Invalid access of peer GPU memory over nvlink or a hardware error
[rank3]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank3]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank3]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/ubuntu/.config/Ultralytics/DDP/_temp_3b39_bxa139648849054848.py", line 19, in <module>
[rank2]:     results = trainer.train()
[rank2]:               ^^^^^^^^^^^^^^^
[rank2]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 246, in train
[rank2]:     self._do_train()
[rank2]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 486, in _do_train
[rank2]:     self.optimizer_step()
[rank2]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 750, in optimizer_step
[rank2]:     self.scaler.step(self.optimizer)
[rank2]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 461, in step
[rank2]:     retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
[rank2]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in _maybe_opt_step
[rank2]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in <genexpr>
[rank2]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank2]:                ^^^^^^^^
[rank2]: RuntimeError: CUDA error: Invalid access of peer GPU memory over nvlink or a hardware error
[rank2]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank2]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank2]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank5]: Traceback (most recent call last):
[rank5]:   File "/home/ubuntu/.config/Ultralytics/DDP/_temp_3b39_bxa139648849054848.py", line 19, in <module>
[rank5]:     results = trainer.train()
[rank5]:               ^^^^^^^^^^^^^^^
[rank5]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 246, in train
[rank5]:     self._do_train()
[rank5]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 486, in _do_train
[rank5]:     self.optimizer_step()
[rank5]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 750, in optimizer_step
[rank5]:     self.scaler.step(self.optimizer)
[rank5]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 461, in step
[rank5]:     retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
[rank5]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in _maybe_opt_step
[rank5]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in <genexpr>
[rank5]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank5]:                ^^^^^^^^
[rank5]: RuntimeError: CUDA error: Invalid access of peer GPU memory over nvlink or a hardware error
[rank5]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank5]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank5]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank6]: Traceback (most recent call last):
[rank6]:   File "/home/ubuntu/.config/Ultralytics/DDP/_temp_3b39_bxa139648849054848.py", line 19, in <module>
[rank6]:     results = trainer.train()
[rank6]:               ^^^^^^^^^^^^^^^
[rank6]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 246, in train
[rank6]:     self._do_train()
[rank6]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 486, in _do_train
[rank6]:     self.optimizer_step()
[rank6]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 750, in optimizer_step
[rank6]:     self.scaler.step(self.optimizer)
[rank6]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 461, in step
[rank6]:     retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
[rank6]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in _maybe_opt_step
[rank6]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in <genexpr>
[rank6]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank6]:                ^^^^^^^^
[rank6]: RuntimeError: CUDA error: Invalid access of peer GPU memory over nvlink or a hardware error
[rank6]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank6]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank6]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank7]: Traceback (most recent call last):
[rank7]:   File "/home/ubuntu/.config/Ultralytics/DDP/_temp_3b39_bxa139648849054848.py", line 19, in <module>
[rank7]:     results = trainer.train()
[rank7]:               ^^^^^^^^^^^^^^^
[rank7]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 246, in train
[rank7]:     self._do_train()
[rank7]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 486, in _do_train
[rank7]:     self.optimizer_step()
[rank7]:   File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 750, in optimizer_step
[rank7]:     self.scaler.step(self.optimizer)
[rank7]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 461, in step
[rank7]:     retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
[rank7]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in _maybe_opt_step
[rank7]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank7]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 355, in <genexpr>
[rank7]:     if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
[rank7]:                ^^^^^^^^
[rank7]: RuntimeError: CUDA error: Invalid access of peer GPU memory over nvlink or a hardware error
[rank7]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank7]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank7]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: Invalid access of peer GPU memory over nvlink or a hardware error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f830c7785e8 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xe0 (0x7f830c70d4a2 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3c2 (0x7f830cea5422 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x1e79f (0x7f830ce6d79f in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x20060 (0x7f830ce6f060 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x2028c (0x7f830ce6f28c in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #6: <unknown function> + 0x44d2a2 (0x7f82ff3aa2a2 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f830c752f39 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #8: c10d::Reducer::~Reducer() + 0x329 (0x7f82f0d0efd9 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0xc3ee72 (0x7f82ffb9be72 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x37346a (0x7f82ff2d046a in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0xc49161 (0x7f82ffba6161 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0x37d8c0 (0x7f82ff2da8c0 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0x37df21 (0x7f82ff2daf21 in /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0x1f2deb (0x562a6a869deb in /share/app/miniconda3/envs/torch27/bin/python)
frame #15: <unknown function> + 0x24c2d4 (0x562a6a8c32d4 in /share/app/miniconda3/envs/torch27/bin/python)
frame #16: <unknown function> + 0x1f2deb (0x562a6a869deb in /share/app/miniconda3/envs/torch27/bin/python)
frame #17: <unknown function> + 0x2f2ad0 (0x562a6a969ad0 in /share/app/miniconda3/envs/torch27/bin/python)
frame #18: <unknown function> + 0x20b83f (0x562a6a88283f in /share/app/miniconda3/envs/torch27/bin/python)
frame #19: <unknown function> + 0x2f27dc (0x562a6a9697dc in /share/app/miniconda3/envs/torch27/bin/python)
frame #20: <unknown function> + 0x2f1ef3 (0x562a6a968ef3 in /share/app/miniconda3/envs/torch27/bin/python)
frame #21: Py_FinalizeEx + 0x181 (0x562a6a94eb01 in /share/app/miniconda3/envs/torch27/bin/python)
frame #22: <unknown function> + 0x144edd (0x562a6a7bbedd in /share/app/miniconda3/envs/torch27/bin/python)
frame #23: Py_BytesMain + 0x37 (0x562a6a915a37 in /share/app/miniconda3/envs/torch27/bin/python)
frame #24: <unknown function> + 0x29d90 (0x7f831bdf2d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #25: __libc_start_main + 0x80 (0x7f831bdf2e40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #26: <unknown function> + 0x29e8c7 (0x562a6a9158c7 in /share/app/miniconda3/envs/torch27/bin/python)

W0601 07:26:08.827000 3827077 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3827098 closing signal SIGTERM
W0601 07:26:08.829000 3827077 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3827099 closing signal SIGTERM
W0601 07:26:08.829000 3827077 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3827100 closing signal SIGTERM
W0601 07:26:08.830000 3827077 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3827101 closing signal SIGTERM
W0601 07:26:08.830000 3827077 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3827102 closing signal SIGTERM
W0601 07:26:08.831000 3827077 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3827103 closing signal SIGTERM
W0601 07:26:08.831000 3827077 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3827104 closing signal SIGTERM
E0601 07:26:11.301000 3827077 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: -6) local_rank: 0 (pid: 3827097) of binary: /share/app/miniconda3/envs/torch27/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/distributed/run.py", line 896, in <module>
    main()
  File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/ubuntu/.config/Ultralytics/DDP/_temp_3b39_bxa139648849054848.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2026-06-01_07:26:08
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 3827097)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 3827097
============================================================
Traceback (most recent call last):
  File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/model.py", line 792, in train
    self.trainer.train()
  File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 240, in train
    raise e
  File "/data0/pycharm/YOLO/ultralytics_26/ultralytics/engine/trainer.py", line 238, in train
    subprocess.run(cmd, check=True)
  File "/share/app/miniconda3/envs/torch27/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/share/app/miniconda3/envs/torch27/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '8', '--master_port', '59121', '/home/ubuntu/.config/Ultralytics/DDP/_temp_3b39_bxa139648849054848.py']' returned non-zero exit status 1.
````

**Comment by UNeedCryDear** [comment]
By the way, the  same environment works fine with YOLOv5，my Env torch27 &torch210&torch211

**Comment by UNeedCryDear** [comment]
Finally, I resolved the issue by setting num_workers=0. It is confirmed that DataLoader causes a deadlock when used with DDP,if num_workers>=1.

https://github.com/ultralytics/ultralytics/blob/1425b060c0c5a8c54cd7b154e5ecbf4702210e4f/ultralytics/cfg/default.yaml#L21

**Comment by glenn-jocher** [comment]
Thanks, that’s a helpful isolation result—`workers=0` bypassing the hang strongly points to the DDP dataloader worker path in [`build_dataloader()`](https://docs.ultralytics.com/reference/data/build#ultralytics.data.build.build_dataloader); please post the text output of `yolo checks` (or `ultralytics.utils.checks.collect_system_info()` if you may have mixed installs) and confirm whether the traceback paths match the loaded package, since your logs show a local `ultralytics` checkout path.

**Comment by UNeedCryDear** [comment]
@glenn-jocher 
I updated the packages to the latest  `pip install -U ultralytics`, and pulled the newest source code using git clone. I only modified the dataset path and set the devices to 1, 2, 3, 4.


/share/app/miniconda3/envs/torch27/bin/python /data0/YOLO/yolo26/ultralytics_test_ddp/train_yolov26_seg.py 
/data0/YOLO/yolo26/ultralytics_test_ddp/ultralytics/__init__.py
WARNING ⚠️ Multiple Ultralytics installations detected. The `yolo` command uses: /share/app/miniconda3/envs/torch27/lib/python3.12/site-packages/ultralytics, but current session imports from: /data0/YOLO/yolo26/ultralytics_test_ddp/ultralytics. This may cause version conflicts. Install your local copy in editable mode with 'pip install -e /data0/YOLO/yolo26/ultralytics_test_ddp' to avoid issues. See https://docs.ultralytics.com/quickstart/
Ultralytics 8.4.67 🚀 Python-3.12.12 torch-2.7.1+cu128 CUDA:0 (NVIDIA H20, 97348MiB)
Setup complete ✅ (224 CPUs, 1511.5 GB RAM, 235.1/889.6 GB disk)

OS                     Linux-5.15.0-184-generic-x86_64-with-glibc2.35
Environment            Linux
Python                 3.12.12
Install                git
Path                   /data0/YOLO/yolo26/ultralytics_test_ddp/ultralytics
RAM                    1511.46 GB
Disk                   235.1/889.6 GB
CPU                    Intel Xeon Platinum 8480+
CPU count              224
GPU                    NVIDIA H20, 97348MiB
GPU count              8
CUDA                   12.8

numpy                  ✅ 2.2.6>=1.23.0
matplotlib             ✅ 3.10.7>=3.3.0
opencv-python          ✅ 4.12.0.88>=4.6.0
pillow                 ✅ 11.3.0>=7.1.2
pyyaml                 ✅ 6.0.3>=5.3.1
requests               ✅ 2.32.5>=2.23.0
scipy                  ✅ 1.16.2>=1.4.1
torch                  ✅ 2.7.1+cu128>=1.8.0
torch                  ✅ 2.7.1+cu128!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision            ✅ 0.22.1+cu128>=0.9.0
psutil                 ✅ 7.1.1>=5.8.0
polars                 ✅ 1.34.0>=0.20.0
nvidia-ml-py           ✅ 13.610.43>=12.0.0
ultralytics-thop       ✅ 2.0.18>=2.0.18
Ultralytics 8.4.67 🚀 Python-3.12.12 torch-2.7.1+cu128 CUDA:0 (NVIDIA H20, 97348MiB)
                                                      CUDA:1 (NVIDIA H20, 97348MiB)
                                                      CUDA:2 (NVIDIA H20, 97348MiB)
                                                      CUDA:3 (NVIDIA H20, 97348MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=80, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/data0/YOLO/yolo26/ultralytics_test_ddp/config/test_seg.yaml, degrees=90, deterministic=True, device=0,1,2,3, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=False, epochs=800, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.5, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=./yolo26n-seg.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=test_ddp-3, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/data0/YOLO/yolo26/ultralytics_test_ddp/runs/test, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/data0/YOLO/yolo26/ultralytics_test_ddp/runs/test/test_ddp-3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=0, workspace=None
Overriding model.yaml nc=80 with nc=2

**Comment by glenn-jocher** [comment]
Thanks, this confirms the run is still in a mixed-install state; because the DDP subprocess is spawned from [the training path in `BaseTrainer.train()`](https://docs.ultralytics.com/reference/engine/trainer#ultralytics.engine.trainer.BaseTrainer.train), the parent process and all ranks need to import the same `ultralytics` package, so please retest in a clean single-source setup first (either editable local checkout or only the pip package). If `workers>=1` still hangs there for `segment` or `obb`, please open a new issue with the full text logs since that is a separate path from this original `detect` report.

**Comment by UNeedCryDear** [comment]
Befor start，use commod : "pip install -e .", it still hangs!
```bash
/share/app/miniconda3/envs/torch27/bin/python /data0/pycharm/YOLO/yolo26/ultralytics_test_ddp/train_yolov26_seg.py 
/data0/pycharm/YOLO/yolo26/ultralytics_test_ddp/ultralytics/__init__.py
Ultralytics 8.4.67 🚀 Python-3.12.12 torch-2.7.1+cu128 CUDA:0 (NVIDIA H20, 97348MiB)
Setup complete ✅ (224 CPUs, 1511.5 GB RAM, 235.2/889.6 GB disk)

OS                     Linux-5.15.0-184-generic-x86_64-with-glibc2.35
Environment            Linux
Python                 3.12.12
Install                git
Path                   /data0/pycharm/YOLO/yolo26/ultralytics_test_ddp/ultralytics
RAM                    1511.46 GB
Disk                   235.2/889.6 GB
CPU                    Intel Xeon Platinum 8480+
CPU count              224
GPU                    NVIDIA H20, 97348MiB
GPU count              8
CUDA                   12.8

numpy                  ✅ 2.2.6>=1.23.0
matplotlib             ✅ 3.10.7>=3.3.0
opencv-python          ✅ 4.12.0.88>=4.6.0
pillow                 ✅ 11.3.0>=7.1.2
pyyaml                 ✅ 6.0.3>=5.3.1
requests               ✅ 2.32.5>=2.23.0
scipy                  ✅ 1.16.2>=1.4.1
torch                  ✅ 2.7.1+cu128>=1.8.0
torch                  ✅ 2.7.1+cu128!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision            ✅ 0.22.1+cu128>=0.9.0
psutil                 ✅ 7.1.1>=5.8.0
polars                 ✅ 1.34.0>=0.20.0
nvidia-ml-py           ✅ 13.610.43>=12.0.0
ultralytics-thop       ✅ 2.0.18>=2.0.18
Ultralytics 8.4.67 🚀 Python-3.12.12 torch-2.7.1+cu128 CUDA:0 (NVIDIA H20, 97348MiB)
                                                      CUDA:1 (NVIDIA H20, 97348MiB)
                                                      CUDA:2 (NVIDIA H20, 97348MiB)
                                                      CUDA:3 (NVIDIA H20, 97348MiB)

```
By cmd "pip uninstall ultralytics  " and "pip install ultralytics  ", and then running code:
```bash
# work will A in [0,1,2,4,8] and B in [4,8,16,32,48]
yolo train data=test_ddp.yaml model=yolo26n-seg.pt epochs=100  device=0,1,2,3,4 workers=A batch=B (√)
# hangs if batch>=64 and workers>0.
yolo train data=test_ddp.yaml model=yolo26n-seg.pt epochs=100  device=0,1,2,3,4 workers=1 batch=64 （×）
# but run code with: 
yolo train data=test_ddp.yaml model=yolo26n-seg.pt epochs=100  device=0 workers=8 batch=256 (√)
```
No OOM occurred batch 256.

**Comment by glenn-jocher** [comment]
Thanks, that rules out the mixed-install case and the `workers=0` vs `workers>0` threshold is useful; since this is now a separate reproducible multi-GPU `segment` dataloader-worker issue rather than the original `detect` validation report, please open a new issue for visibility and include the exact passing/failing commands, full text traceback from all ranks, `yolo checks`, and a minimal repro dataset if possible, while using `workers=0` as the current workaround; the relevant code path is in [`build_dataloader()`](https://docs.ultralytics.com/reference/data/build#ultralytics.data.build.build_dataloader) and the DDP launch in [`BaseTrainer.train()`](https://docs.ultralytics.com/reference/engine/trainer#ultralytics.engine.trainer.BaseTrainer.train).

**Comment by Y-T-G** [comment]
@UNeedCryDear If your DDP training is hanging, you should try running the same command with `workers=0` and it will show you the error.

**Comment by glenn-jocher** [comment]
Thanks everyone for the detailed reports and version comparisons — this is now fully root-caused, and the good news is it's **already fixed on `main`**.

## Root cause

This is the DDP "unused parameter" reducer deadlock, **not** the per-image metrics gather (#24089) that was originally suspected. The actual regression was #24413 (v8.4.49), which removed `find_unused_parameters=True` from the `DistributedDataParallel` wrapper. YOLO26's head has conditionally-active branches (C2PSA / SPPF / end2end `Detect` via `flow_model`): when a mini-batch's TAL assignment leaves a detection scale (P3/P4/P5) with no ground-truth, those head parameters receive no gradient. Without `find_unused_parameters=True`, DDP's reducer waits indefinitely for their all-reduce, and with `TORCH_NCCL_BLOCKING_WAIT=1` the other ranks busy-spin — exactly the "3 ranks at ~97% CPU, 1 sleeping" pattern @hitimr captured. Because batch composition is deterministic for a fixed dataset + sampler, the offending batch lands at the same index every run, so it looks like a fully deterministic hang at ~95% of epoch 1.

This was fixed by #24620 (v8.4.64), which re-added `find_unused_parameters=not bool(self.args.compile)`.

## Why the versions line up

| Version | `find_unused_parameters` | Result |
|---|---|---|
| 8.4.8 (workaround) | present | ✅ works |
| **8.4.49** (#24413) | **removed** | deadlock introduced |
| 8.4.51 / 8.4.58 | missing | ❌ hang (this report) |
| **8.4.64** (#24620) | **re-added** | fixed |
| 8.4.75 (`main`) | present | ✅ works |

@hitimr you were on 8.4.51 and @filaPro on 8.4.58 — both inside the broken 8.4.49–8.4.63 window. The `8.4.8` workaround predates the regression, which is why it works.

## Reproduction / verification (4× A100-SXM 80GB, NVLink)

- Current `main` trains your exact config (`yolo26s`, `imgsz=1600`, `batch=32`, `device=0,1,2,3`, `amp=False`, `val=True`) cleanly through validation — on both torch 2.8 and your torch 2.5.1+cu121 / NCCL 2.21.5.
- Reverting the single line to the buggy `find_unused_parameters=False` state and forcing a scale-starved batch reproduces it precisely:
  ```
  RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one ...
  Parameter indices which did not receive grad for rank 0: 426 427 428 ...
  ```
- Flipping that one line back (current `main`) → 10 epochs complete cleanly. A/B confirmed.

## Fix

Please upgrade to the latest release (≥ 8.4.64, ideally ≥ 8.4.70 which also includes #24810 for DDP AMP-broadcast sync):

```bash
pip install -U ultralytics
```

Closing as resolved on `main`. If anyone still sees a DDP hang on **≥ 8.4.64**, please open a new issue with full text logs from all ranks and `yolo checks`.

> Note for @UNeedCryDear: your runs are on 8.4.66/67 (after the fix above) and `workers=0` resolves them, so that's a separate dataloader-worker path rather than this regression. Please open a dedicated issue with your exact passing/failing commands and full multi-rank traceback so we can track it independently.
