### ISSUE TITLE
GPU memory usage increasing during segmentation inference

### ISSUE THREAD

**Issue by sovit-123** [ultralytics/ultralytics#281]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I was running YOLOv8 instance segmentation video inference using the pretrained models. Noticed that the GPU memory usage keeps on increasing before eventually running Out Of Memory and throwing an OOM error. Some observations:
1. The rate of increase largely depends on the number of detections. More detections => sooner OOM error.
2. Happens in both cases, with and without `retina_masks` argument. **But happens much faster when `retina_masks=True`**.
3. Some numerical perspective:
- On a 6 GB GTX 1060 with `retina_masks=True`, a 1280x720 video runs for about 3 seconds before running out of memory.
- On a 40 GB A100 with `retina_masks=True`, a 1280x720 video runs for about 60 seconds before running out of memory.

As it is also happening when having as large as 40 GB VRAM, it can become a bigger issue eventually.
@AyushExel @glenn-jocher   
Hope you get some time to look into the issue.

### Environment

 - YOLOv8, Python 3.9, TORCHVISION 0.13.0, TORCH 1.12.0, A100 40GB
 - Ubuntu 20.04
 - Python 3.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@sovit-123 please use the latest release, it treats model.predict() as a python generator, which can solve the memory issue.
related PR. [https://github.com/ultralytics/ultralytics/pull/239](https://github.com/ultralytics/ultralytics/pull/239)

**Comment by sovit-123** [comment]
@Laughing-q 
Thanks for the suggestion. I tried that. I think it helps to a good extent. Now, for a 34-second video, I do not run Out Of Memory till the end of the prediction which happened before on a 6 GB GTX 1060. But there is till some increase in memory usage.
For reference, the prediction started with around 1200 MB usage (Nano model) on nvidia-smi and ended with around 2000 MB usage. 
This is the usage command:
`yolo task=segment mode=predict source=video_1.mp4 save=False show=True retina_masks=True`

I think, OOM may still happen with longer videos on limited VRAM GPUs.

**Comment by AyushExel** [comment]
@Laughing-q wait the cli interface doesn't return any output right? Then how is this happening.. Or its something we have to do today?

**Comment by Laughing-q** [comment]
@AyushExel @Laughing-q I tested a long video, and yes the memory increased at the beginning then it kept at this level all the time(about 2mins I think). I think the memory issue has gone.
![UStgu77Vwc](https://user-images.githubusercontent.com/61612323/212006205-0d2f150a-370b-471c-80f8-b330379f2534.png)
@sovit-123 I used the same command with your, just changed the source path.

**Comment by AyushExel** [comment]
Yay 🙌 nice

**Comment by sovit-123** [comment]
Thanks for the detailed info.
Ran it on a much longer video (5 minutes) and was able to run it successfully. One weird thing though, using the Nano model, by the end of the prediction it was using more VRAM compared to the X model. It may be because of extra false detections. I cannot think of anything else now.
Still, I think the issue is solved. Thanks again for the quick response. I am closing the issue.

**Comment by SinDongHwan** [comment]
i faced same issue when test video using yolo11 segmentation model(this images is yolo11n-seg.pt).

i don't know why stack gpu memory usage.

It's not stacked when others models, such as detect, pose, cls and etc)

![Image](https://github.com/user-attachments/assets/dc6c3303-2bb1-4264-9b6e-72320903dd79)

![Image](https://github.com/user-attachments/assets/0bcc3a05-b9ee-4835-90c4-7bf7f6f52764)

**Comment by glenn-jocher** [comment]
@SinDongHwan Thanks for reporting this issue. The memory accumulation occurs because by default, the results from all frames are stored in memory. Try adding `stream=True` to your code:

```python
from ultralytics import YOLO

model = YOLO('yolo11n-seg.pt')
model.predict('test1.mp4', save=True, stream=True)
```

This creates a generator that processes frames one at a time without accumulating them in memory. The segmentation models use more memory because they store mask data in addition to bounding boxes, which can stack up quickly during video processing.
