### ISSUE TITLE
Training interruption problem 

### ISSUE THREAD

**Issue by 7assanx7** [ultralytics/ultralytics#2859]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I updated ultralytics to latest version 8.0.109 and pytorch with version 2.0.0 now when I start training I get this error:

 C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [127,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
      1/150       4.2G      1.522      7.959      1.793         36        640:  18%|█▊        | 42/235 [00:23<01:46,  1.81it/s]
Traceback (most recent call last):
  File "E:\GradProject\SignLanguage\trainn.py", line 9, in <module>
    model.train(data='data.yaml', epochs=150, workers=0)  # train the model
  File "E:\GradProject\hassan\lib\site-packages\ultralytics\yolo\engine\model.py", line 371, in train
    self.trainer.train()
  File "E:\GradProject\hassan\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "E:\GradProject\hassan\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 329, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "E:\GradProject\hassan\lib\site-packages\ultralytics\yolo\v8\detect\train.py", line 98, in criterion
    return self.compute_loss(preds, batch)
  File "E:\GradProject\hassan\lib\site-packages\ultralytics\yolo\v8\detect\train.py", line 211, in __call__
    _, target_bboxes, target_scores, fg_mask, _ = self.assigner(
  File "E:\GradProject\hassan\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\GradProject\hassan\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\GradProject\hassan\lib\site-packages\ultralytics\yolo\utils\tal.py", line 112, in forward
    mask_pos, align_metric, overlaps = self.get_pos_mask(pd_scores, pd_bboxes, gt_labels, gt_bboxes, anc_points,
  File "E:\GradProject\hassan\lib\site-packages\ultralytics\yolo\utils\tal.py", line 133, in get_pos_mask
    align_metric, overlaps = self.get_box_metrics(pd_scores, pd_bboxes, gt_labels, gt_bboxes, mask_in_gts * mask_gt)
  File "E:\GradProject\hassan\lib\site-packages\ultralytics\yolo\utils\tal.py", line 152, in get_box_metrics
    bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*w
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

how can i fix that ?

**Comment by glenn-jocher** [comment]
@7assanx7 hello, it seems that you are facing a 'device-side assert triggered' error while training YOLOv8. This usually occurs when there is an out-of-bounds error when accessing a value in your tensor. Since you have recently updated PyTorch and YOLOv8, it is possible that there is a mismatch between the versions you are using. 

One possible solution is to upgrade your CUDA version since the issue appears to be a CUDA error. Additionally, you may try setting `CUDA_LAUNCH_BLOCKING=1` for debugging purposes. Another potential solution is to check that your bounding box or mask labels are correct and not out of bounds. 

I hope this helps! Let me know if you still encounter any issues.

**Comment by 7assanx7** [comment]
> @7assanx7 hello, it seems that you are facing a 'device-side assert triggered' error while training YOLOv8. This usually occurs when there is an out-of-bounds error when accessing a value in your tensor. Since you have recently updated PyTorch and YOLOv8, it is possible that there is a mismatch between the versions you are using.
> 
> One possible solution is to upgrade your CUDA version since the issue appears to be a CUDA error. Additionally, you may try setting `CUDA_LAUNCH_BLOCKING=1` for debugging purposes. Another potential solution is to check that your bounding box or mask labels are correct and not out of bounds.
> 
> I hope this helps! Let me know if you still encounter any issues.

Yes, the problem was in the dataset. I found a file containing a class number higher than the identifier in data.yam

**Comment by glenn-jocher** [comment]
@7assanx7 Glad to hear that you were able to identify the problem. It is not uncommon for the `device-side assert` error to be caused by errors in the bounding box or mask labels. It's important to ensure that your dataset is properly formatted with correctly labeled classes and bounding boxes. 

Please feel free to reach out if you have any more issues or questions. Good luck with your training!
