### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kopyl** [ultralytics/ultralytics#3181]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

Hey. I'm facing bugs with ultralytics.YOLO.
Was wondering if somebody could help me fixing them (:
Getting TypeError: 'NoneType' object is not subscriptable

Here is how i do the inference with a model:
I put up a Flask server: https://pastebin.com/kBLb8fz5

Here is how i make requests:
https://pastebin.com/RynvyyBu

I'm making a lot of async requests with the SAME image at once. Getting this error message:
```
File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/v8/detect/predict.py", line 26, in postprocess
    path = self.batch[0]
TypeError: 'NoneType' object is not subscriptable
```

When i make requests one at a time – i'm fine. No issues.
I was not able to make a Flask server work without errors on either 64 processes or one.
With 64 processes client can't get responses for a long time (i still was not able to wait until it finishes)
With 1 process – TypeError

Full traceback: https://pastebin.com/vTcB5xJ1

Running on CPU (AWS EC2 C5A 16xlarge – 64 CPU, 128 GB RAM). No GPU

Also was getting RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR error when tried it with GPU
Full traceback: https://pastebin.com/8J7SLw4f
Error:
```
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
```

But when I convert a model to ONNX – no errors. Except that the scores get lower. For some predictions – drastically lower, for some – just slightly.

One of the images I tried:
https://cdn.discordapp.com/attachments/1096822099345145969/1117198390585987092/68a31cb7cc50b355a63624176e095c250cb39e6c.jpg
URL backup: https://audios-ai.s3.amazonaws.com/68a31cb7cc50b355a63624176e095c250cb39e6c.jpg

Training Yolov8 model and inferencing is done with the same Python's Ultralytics package.

- YOLO: Ultralytics YOLOv8.0.117
- OS: Ubuntu 22.04.2 LTS
- Python: 3.10.6

**Comment by kopyl** [comment]
Now i got `RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR`
Full traceback: https://pastebin.com/8J7SLw4f

**Comment by kopyl** [comment]
I made a lot of async requests like this:

```
import aiohttp
import asyncio


async def make_request(session):
    url = "https://..."
    payload = {
        "image_url": "https://cdn.discordapp.com/attachments/1096822099345145969/1117198390585987092/68a31cb7cc50b355a63624176e095c250cb39e6c.jpg"
    }
    headers = {
        "Authorization": "8Jw1kj5Woa4SDHtD%hH!7v4--",
    }
    async with session.post(url, json=payload, headers=headers) as response:
        return await response.json()


async with aiohttp.ClientSession() as session:
    tasks = []

    for i in range(0, 60):
        tasks.append(asyncio.create_task(make_request(session)))

    results = await asyncio.gather(*tasks)
    for result in results:
        print(result)
```

**Comment by glenn-jocher** [comment]
It looks like you're encountering a few different issues here, so let's try to break them down:

1. **TypeError: 'NoneType' object is not subscriptable**: This error usually means that you're trying to access an item from a variable that's supposed to be a list or similar container, but it's actually `None`. In this case, it looks like `self.batch` is `None`, so trying to access `self.batch[0]` raises this error. This might be happening due to the concurrent access of the model in a Flask application. When you're handling many asynchronous requests, some may end up accessing the model while it is in an unstable state, causing unpredictable behaviors. 

   A solution to this might be adding a lock around the model inference to ensure that only one request can access it at a time. You can use Python's threading.Lock for this purpose. Here's a simple example:

   ```python
   from threading import Lock

   lock = Lock()

   @app.route('/predict', methods=['POST'])
   def predict():
       lock.acquire()
       try:
           # model inference code
       finally:
           lock.release()
   ```

   However, this will make your application run each prediction serially, which might not be ideal if you have a high traffic server. A better approach might be to use a queue to store the incoming requests, and then process them in batches, which should be more efficient.

2. **RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR**: This error might be due to an issue with CUDA or cuDNN, or it could be related to your GPU memory. Since you mentioned you get this error when running on a GPU, it's possible that your GPU is running out of memory. You could try reducing the batch size to lower memory consumption. Also, make sure that your CUDA and cuDNN versions are compatible with your PyTorch version.

3. **Model scores lower after converting to ONNX**: This is a common issue and might be due to various reasons. One reason could be that PyTorch and ONNX use different strategies for operations like padding, which can lead to slightly different results. Also, the conversion process might introduce approximation errors. You could try to improve the accuracy by increasing the precision of the conversion (use float64 instead of float32, if not already doing so). 

   However, keep in mind that achieving exactly the same results between PyTorch and ONNX is not always possible. If the difference in scores is significant, it might be worth revisiting the conversion process and making sure everything is done correctly. It might also help to update your PyTorch and ONNX versions to the latest ones, as there have been numerous improvements and bug fixes related to ONNX conversion in recent PyTorch versions.

I hope this helps! Let me know if you have any other questions.

**Comment by kopyl** [comment]
@glenn-jocher could you please tell me how to convert yolo8 model with Ultralytics to float64?

I only know the export method which has the "half" parameter which makes the onnx model float16 instead of float32

**Comment by kopyl** [comment]
@glenn-jocher do you know any Ultralytics developer who can fix this bug in the library?

**Comment by kopyl** [comment]
@glenn-jocher 

> This might be happening due to the concurrent access of the model in a Flask application. When you're handling many asynchronous requests, some may end up accessing the model while it is in an unstable state, causing unpredictable behaviors.

Why there is no such issue with ONNX then? Why Ultralytics does not make sure that inference is handled one at a time?

**Comment by kopyl** [comment]
@glenn-jocher 

> A better approach might be to use a queue to store the incoming requests, and then process them in batches

How to process them in batches?

**Comment by kopyl** [comment]
@glenn-jocher it see that it's fixed by passing `threaded=False` to the `app.run` function in Slack .

> When you're handling many asynchronous requests, some may end up accessing the model while it is in an unstable state, causing unpredictable behaviors.

Why can't developers of Ultralytics can't prevent that?

**Comment by kopyl** [comment]
@glenn-jocher from my side it seems that it can be fixed with an infinite loop of retries:

```
while True:
        try:
            results = model(image_url)
            break
        except TypeError:
            continue
```

I did not know by the way that Flask handles by default everything in Threads...

So specifying `threaded=False` helps too but makes the app very slow. Basically the same Threading lock as you suggested...

I'm going to see whether I can use 64 processes at a time without encountering this issue.
