### ISSUE TITLE
Yolov8 training Big dataset reporting error NCCL

### ISSUE THREAD

**Issue by wangyang581** [ultralytics/ultralytics#3182]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug
![image](https://github.com/ultralytics/ultralytics/assets/67748803/9614164e-b62a-4696-97de-debbd1c2f998)

![image](https://github.com/ultralytics/ultralytics/assets/67748803/14fbf523-ec66-41a5-80ff-108614eca6ff)

![image](https://github.com/ultralytics/ultralytics/assets/67748803/73585b5d-3742-4e91-a6a3-fb421832dcf7)

![image](https://github.com/ultralytics/ultralytics/assets/67748803/73e6deb5-82a8-4e55-a06d-d227212681a3)

### Environment

Docker container generated from Dockerfile

FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime
RUN pip install --no-cache nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com

ADD https://ultralytics.com/assets/Arial.ttf https://ultralytics.com/assets/Arial.Unicode.ttf /root/.config/Ultralytics/

RUN apt update \
    && apt install --no-install-recommends -y gcc git zip curl htop libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg g++

RUN apt upgrade --no-install-recommends -y openssl tar

RUN mkdir -p /usr/src/ultralytics
WORKDIR /usr/src/ultralytics

RUN git clone https://github.com/ultralytics/ultralytics /usr/src/ultralytics
ADD https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt /usr/src/ultralytics/

RUN python3 -m pip install --upgrade pip wheel
RUN pip install --no-cache -e . albumentations comet thop pycocotools onnx onnx-simplifier onnxruntime-gpu

ENV OMP_NUM_THREADS=1

### Additional

When I use yolov8 to perform multi card training on the object365 dataset, after reading the data, when I start training the first epoch, the Progress bar does not advance. After a period of time, an NCCL error is reported. I attempted to train with a smaller dataset and did not encounter this issue. The environment I use is the docker container generated from the Dockerfile in yolov8. Since I have no previous experience in training such a Big data set, I do not know where the problem is and how to solve it

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Based on your description, it appears like the issue could be related to the size of the Object365 dataset and how it's being loaded into memory, especially since you don't encounter the issue with a smaller dataset. This could be causing the NCCL error due to inter-GPU communication problems.

Here are some things you could try:

1. **Reduce Batch Size**: Depending on your GPU memory, large datasets like Object365 might require smaller batch sizes to fit into memory. The error could be arising because the GPUs are running out of memory.

2. **Increase shared memory for Docker**: Docker containers have a limited amount of shared memory (`/dev/shm`). This is often not enough for PyTorch's dataloader, which uses shared memory to share data between main process and worker subprocesses. You can increase Docker's shared memory size by adding `--shm-size` argument to the `docker run` command like so: `docker run --gpus all --shm-size=1g ...`.

3. **Dataloader worker adjustment**: Try to decrease the number of workers in the data loader (set `num_workers=0`). In a multi-GPU setup, each GPU will launch the number of workers specified, which might exceed the system limit when using a large dataset.

4. **Use a different backend for distributed training**: PyTorch offers different backends for distributed training (`nccl`, `gloo`, `mpi`). You can try switching the backend to see if it resolves the issue. Keep in mind that `nccl` is recommended for multi-GPU setup, but it could be worth trying the others. For example:

    ```python
    torch.distributed.init_process_group(backend='gloo')
    ```

5. **Update NCCL**: Ensure you have the latest NCCL version. There might be a bug in your current version causing the issue. You can update NCCL through the NVIDIA website.

6. **Setting Environment Variables**: Set the following environment variables before your training script:

    ```bash
    export NCCL_SOCKET_IFNAME=eth0
    export NCCL_IB_DISABLE=1
    ```

   These variables specify that NCCL uses the ethernet for inter-GPU communication and disables the infiniband, which could cause issues in some environments.

Remember to check your system logs and NCCL debug logs for any additional information that might help diagnose the problem. You can enable NCCL debug logging by setting `NCCL_DEBUG=INFO` environment variable.

**Comment by glenn-jocher** [comment]
Great news 😃! Your original issue may now be resolved ✅ in PR #3197. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by wangyang581** [comment]
Thank you for your reply. I have upgraded ultralytics to a new version and resolved this issue. I wish you good health and a happy life

**Comment by pderrenger** [comment]
@wangyang581 you're very welcome! I'm thrilled to hear that the upgrade resolved the issue for you. Wishing you continued success with your training, and thank you for your well wishes. If you have any more questions or need further assistance in the future, please don't hesitate to reach out. Have a wonderful day and happy training with YOLOv8! 🚀🌟
