### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by Fusica** [ultralytics/ultralytics#3243]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

When attempting to train rtdetr-l.yaml using a Python file, I encountered an issue. There were no problems when using coco8.yaml, but switching to VOC or coco resulted in the mentioned problem.

This is my python file:
```
from ultralytics import RTDETR

model = RTDETR("rtdetr-l.yaml")
model.info()  # display model information
model.train(data="coco.yaml", epochs=150, batch=12) 
```
and the Error reporting:
```
Traceback (most recent call last):
  File "try.py", line 5, in <module>
    model.train(data="coco.yaml", epochs=150, batch=12)   # train
  File "/home/wf/xwj/ultralytics/ultralytics/vit/rtdetr/model.py", line 106, in train
    self.trainer.train()
  File "/home/wf/xwj/ultralytics/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/wf/xwj/ultralytics/ultralytics/yolo/engine/trainer.py", line 338, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/home/wf/.conda/envs/xwj/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/wf/.conda/envs/xwj/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
```

### Environment

- Ultralytics YOLOv8.0.119 🚀 Python-3.8.16 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3080, 10010MiB)

### Minimal Reproducible Example

```
from ultralytics import RTDETR

model = RTDETR("rtdetr-l.yaml")
model.info()  # display model information
model.train(data="coco.yaml", epochs=150, batch=12)   # train
# model.predict("path/to/image.jpg")  # predict
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Fusica hi there! Thanks for reaching out and providing all the necessary information. The error you encountered, `RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED`, typically indicates an issue with GPU memory allocation.

Here are a few steps you can take to address this problem:
- Ensure that you have enough available GPU memory to train your model. You can try reducing the batch size or image size to reduce memory usage.
- Verify that your GPU drivers are up to date.
- If you're using multiple GPUs, try training with a single GPU to see if the issue persists.
- If you're using a shared GPU environment, make sure that other processes are not using excessive memory.

Please give these suggestions a try and let me know if the issue persists or if you have any further questions.

**Comment by glenn-jocher** [comment]
@Fusica I've used your code and get correct training with no errors. I've added a non-reproducible tag to this issue.

<img width="1085" alt="Screenshot 2023-06-18 at 15 10 50" src="https://github.com/ultralytics/ultralytics/assets/26833433/4fdb5efb-18b5-44f8-b47f-5ebffb4d57d6">

**Comment by Fusica** [comment]
Solved! Just a simple CUDA out of memory. I thought the changes in the dataset would not affect the batch, so I used the batch size of coco8. Reducing the batch size solves the problem very well.

**Comment by glenn-jocher** [comment]
@Fusica great to hear that you were able to solve the issue! The `CUDA out of memory` error typically occurs when the GPU memory is insufficient to train the model with the specified batch size. In your case, using the batch size intended for the `coco8` dataset might have exceeded the available GPU memory when training with other datasets.

By reducing the batch size, you were able to allocate sufficient memory for training and resolve the issue. This adjustment allows the GPU to handle the computations without running out of memory.

If you encounter any further questions or need assistance with YOLOv8, feel free to ask. We're here to help!
