### ISSUE TITLE
Training YOLOv8 with 2 GPUs hangs before starting.

### ISSUE THREAD

**Issue by YaserAlOsh** [ultralytics/ultralytics#3904]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Multi-GPU

### Bug

Hello,
When training YOLOv8 with 2 GPUs on a kaggle environment (2xT4), I see the following error, which does not actually stop the code from running:

![image](https://github.com/ultralytics/ultralytics/assets/25433731/7dde9cf1-d425-48bb-9ba7-1a8c7b2927c1)

***************************************************************************************************
The code keeps on running but even after waiting for close to 40 minutes nothing happens. No training starts.
I have made sure that both of the GPUs are accessible by running:
```
import torch
torch.cuda.device_count()
```
 After manually interrupting the kernel, I see the following trace output:

`KeyboardInterrupt                         Traceback (most recent call last)
Cell In[13], line 3
      1 from ultralytics import YOLO
      2 model = YOLO('yolov8m.pt')
----> 3 results = model.train(data=data_yaml, epochs=100,batch=8,imgsz=1280, device=[0, 1])

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py:372, in YOLO.train(self, **kwargs)
    370     self.model = self.trainer.model
    371 self.trainer.hub_session = self.session  # attach optional HUB session
--> 372 self.trainer.train()
    373 # Update model and cfg after training
    374 if RANK in (-1, 0):

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py:186, in BaseTrainer.train(self)
    184 try:
    185     LOGGER.info(f'DDP command: {cmd}')
--> 186     subprocess.run(cmd, check=True)
    187 except Exception as e:
    188     raise e

File /opt/conda/lib/python3.10/subprocess.py:505, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    503 with Popen(*popenargs, **kwargs) as process:
    504     try:
--> 505         stdout, stderr = process.communicate(input, timeout=timeout)
    506     except TimeoutExpired as exc:
    507         process.kill()

File /opt/conda/lib/python3.10/subprocess.py:1146, in Popen.communicate(self, input, timeout)
   1144         stderr = self.stderr.read()
   1145         self.stderr.close()
-> 1146     self.wait()
   1147 else:
   1148     if timeout is not None:

File /opt/conda/lib/python3.10/subprocess.py:1209, in Popen.wait(self, timeout)
   1207     endtime = _time() + timeout
   1208 try:
-> 1209     return self._wait(timeout=timeout)
   1210 except KeyboardInterrupt:
   1211     # [https://bugs.python.org/issue25942](https://bugs.python.org/issue25942%3C/span%3E)
   1212     # The first keyboard interrupt waits briefly for the child to
   1213     # exit under the common assumption that it also received the ^C
   1214     # generated SIGINT and will exit rapidly.
   1215     if timeout is not None:

File /opt/conda/lib/python3.10/subprocess.py:1959, in Popen._wait(self, timeout)
   1957 if self.returncode is not None:
   1958     break  # Another thread waited.
-> 1959 (pid, sts) = self._try_wait(0)
   1960 # Check the pid and loop as waitpid has been known to
   1961 # return 0 even without WNOHANG in odd situations.
   1962 # [http://bugs.python.org/issue14396.](http://bugs.python.org/issue14396.%3C/span%3E)
   1963 if pid == self.pid:

File /opt/conda/lib/python3.10/subprocess.py:1917, in Popen._try_wait(self, wait_flags)
   1915 """All callers to this function MUST hold self._waitpid_lock."""
   1916 try:
-> 1917     (pid, sts) = os.waitpid(self.pid, wait_flags)
   1918 except ChildProcessError:
   1919     # This happens if SIGCLD is set to be ignored or waiting
   1920     # for child processes has otherwise been disabled for our
   1921     # process.  This child is dead, we can't get the status.
   1922     pid = self.pid

KeyboardInterrupt:`

### Environment

- Ultralytics YOLOv8.0.140 🚀 Python-3.10.12 torch-2.0.0 CUDA:0 (Tesla T4, 15110MiB)
                                                       CUDA:1 (Tesla T4, 15110MiB)

- Python 3.10.12
- Kaggle Notebook

### Minimal Reproducible Example

```
from ultralytics import YOLO
model = YOLO('yolov8m.pt')
results = model.train(data=data_yaml, epochs=100,batch=8,imgsz=1280, device=[0, 1])
```

### Additional

It seems the issue has something to do with the Notebook display output. Some extension is to be loaded but is not available. I have looked up the name 'bq_stats' but have not found anything. It might be an issue with Kaggle only. 
I tried uninstalling wandb which is installed by default on Kaggle notebooks but nothing changed.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@YaserAlOsh hello,

Thank you for providing a detailed description of the issue. The problem you are experiencing might be related to the interaction between specific processes and the Kaggle environment. 

The display output error you're seeing is an issue unrelated to YOLOv8 itself. 'bq_stats' is actually related to some Jupyter notebook extensions for interactiveness, it wouldn't affect the training process of YOLOv8.

The issue of hanging during multi-GPU training might stem from complications with subprocesses and context in a Jupyter Notebook environment. It's possible that the process intended to run the training is encountering difficulty starting or is being blocked when YOLOv8 attempts to utilize multiprocessing for the GPUs.

As for the wandb, it is not related to this issue. Wandb is a tool for visualization and tracking experiments, but uninstalling it won't affect the multi-gpu training.

An alternative solution (although not feasible on Kaggle) would be to try running the script directly from a command line interface if you have access to one, and observe if the multi-GPU training proceeds correctly.

Please note that it would be best to ensure that your Kaggle environment is set up correctly for Multi-GPU usage. Please let us know if your problem persists or you observe new issues.

**Comment by YaserAlOsh** [comment]
Hello Glenn, 
Thank you for the prompt reply.

The environment is set up correctly, as the two GPUs are discoverable. I have just tried your suggestion of running the training from command line. It is possible in Kaggle to use the command line and it worked.

That's the command I have ran:
`!yolo detect train data=/kaggle/working/dataset.yaml model=yolov8m.pt epochs=100 imgsz=1280 device=0,1`

Thank you! 
I think I should mark this as closed now.

The only little problem remaining is that I no longer get a nice visual while training. It is hard to track it as you can see here:
![image](https://github.com/ultralytics/ultralytics/assets/25433731/69b06796-576f-4d5c-b092-afcf5e9039eb)

**Comment by YaserAlOsh** [comment]
Many thanks @glenn-jocher for the extra details.

**Comment by glenn-jocher** [comment]
@YaserAlOsh,

You're very welcome! I'm glad I could assist you. If you have any additional questions or face any more challenges with YOLOv8 in the future, don't hesitate to reach out. We're always here to help you navigate any obstacles you may encounter. Happy coding and best of luck with your project!
