### ISSUE TITLE
Memory is constantly increasing while running prediction even if I set stream=True when run "model(inputs)"

### ISSUE THREAD

**Issue by y200504040u** [ultralytics/ultralytics#3983]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/57352939/5fdb7b35-bd28-4062-a173-94ff56cff5b5)

### Environment

Python  3.8(ubuntu20.04)
PyTorch  1.9.0
Cuda  11.1 
V100-SXM2-32GB(32GB)

### Minimal Reproducible Example

    def is_image_file(filename):
        return any(
        filename.endswith(extension) for extension in ['.bmp', '.png', '.jpg', '.jpeg', '.PNG', '.JPG', '.JPEG'])

    batch_size = 1024
    filenames_img = [os.path.join(path_dir_input, x) \
                     for x in os.listdir(path_dir_input) if is_image_file(x)]
    inputs = []
    outputs = []
    list_path_img_rgb = []
    for idx, path_img_rgb in enumerate(filenames_img):
        path_r = path_img_rgb.replace("test2017", "infer2017")
        if os.path.exists(path_r):
            continue
        list_path_img_rgb.append(path_img_rgb)
        
    for idx, path_img_rgb in enumerate(list_path_img_rgb):
        inputs.append(path_img_rgb)
        if len(inputs) == batch_size:
            print("*" * 20 + " ", idx + 1, " " + "*" * 20)
            results = model(inputs, stream=True)
            outputs.extend(list(results))
            inputs.clear()
        elif len(list_path_img_rgb) - idx == 1:
            results = model(inputs, stream=True)
            outputs.extend(list(results))

### Additional

I ran segmentation prediction based on my test dateset.
I split my test dataset(total 10000+) into 10 batches, and set batchsize to 1024. 
My gpu memory was constantly increasing while running prediction even if I set stream=True when run "model(inputs)".
After ran 3 batches, it crashed and reported "Cuda out of memory".

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Chewbathra** [comment]
Hello,

I got similar bug. When predicting a video (using stream=True, device=GPU), first ~200 predictions are really fast (< 5ms using yolov8n model) but then the inference time increase significantly, passing to more than 12ms until the end of the video.

It's not a GPU problem, i have a Nvidia NVIDIA GeForce RTX 3080 Laptop GPU with 16GB of memory and the model is using only 1800MB when running.

It doesnt depend of number of bounding boxes discovered as well in my case nor, since i dont have more discovered bounding boxes when inference time increase.

**Comment by Laughing-q** [comment]
@y200504040u `stream=True` would return a python generator and it's for cases when you inference with long-time videos and streams.
In your batch inference case, actually it's equivalent to `model.predict(source, stream=False)`, and 1024 is a big size for segment models since the model could return many predicted masks and it'll occupy memory. I suggest you to reduce the inference batch-size. :)

**Comment by Laughing-q** [comment]
@Chewbathra It'd be helpful if you can provide us a reproducible example. :)

**Comment by y200504040u** [comment]
> @y200504040u `stream=True` would return a python generator and it's for cases when you inference with long-time videos and streams. In your batch inference case, actually it's equivalent to `model.predict(source, stream=False)`, and 1024 is a big size for segment models since the model could return many predicted masks and it'll occupy memory. I suggest you to reduce the inference batch-size. :)

I tryed smallest batchsize to 128, memory is still constantly increasing. Just collapsed a little slower...

**Comment by Laughing-q** [comment]
@y200504040u even 128 is still a high value to me, since there're a lot predicted masks with high resolution which could occupy memory a lot.

**Comment by y200504040u** [comment]
> @y200504040u even 128 is still a high value to me, since there're a lot predicted masks with high resolution which could occupy memory a lot.


Thanks for your reply. 
Actually, I hope to obtain a method that can predict test datasets in batches and fully utilize gpu memory.
Anyway, as I mentioned, running a program with constantly increasing gpu memory is not very appropriate.

**Comment by Laughing-q** [comment]
@y200504040u oh I see, that's because the program is keeping all the predicted masks of your 10000+ images in gpu, you can transfer each batches to cpu before appending it to the `outputs`.
```python
outputs.extend(list(results.cpu()))
```

**Comment by y200504040u** [comment]
> @y200504040u oh I see, that's because the program is keeping all the predicted masks of your 10000+ images in gpu, you can transfer each batch of results to cpu before appending it to the `outputs`.
> 
> ```python
> outputs.extend(list(results.cpu()))
> ```

results = model(inputs, stream=True)
'results' is a generator when stream=True，'generator' object has no attribute 'cpu'
I tried 'with torch.no_grad():' at the beginning, and 'torch.cuda.empty_cache()' at end of each batch, the gpu memory usage had wave-like uplift.

**Comment by glenn-jocher** [comment]
@Chewbathra the issue you're facing seems like it's due to accumulating your results tensor on the GPU. When using `model(inputs, stream=True)`, it returns a generator, which doesn't have the `cpu()` attribute to move the tensor from GPU to CPU.

Regarding the utilization of `torch.no_grad()` and `torch.cuda.empty_cache()`, they may not be enough to clear the GPU memory as expected in every case due to how PyTorch manages its memory. As PyTorch retains computational graphs for backward pass (gradient calculation), numerous tensors generated can build up over time and take up considerable memory.

To resolve this, I suggest you transfer the results to CPU for each prediction before storing them. This will ensure that GPU memory space is not occupied when not performing inference. To achieve this, convert the result to a list or NumPy array before storing it in your `outputs` list. This will move the result from the GPU memory to CPU. After this, you can then safely append to `outputs` as normal. 

Remember to delete unneeded tensors and variables then call `torch.cuda.empty_cache()` to free up GPU space, after you're done with each batch. Following this approach should help manage the GPU memory in an optimal way while still performing batch predictions.

**Comment by y200504040u** [comment]
> Thanks for your reply.


Thanks for your reply. I will try that.

**Comment by y200504040u** [comment]
> @Chewbathra the issue you're facing seems like it's due to accumulating your results tensor on the GPU. When using `model(inputs, stream=True)`, it returns a generator, which doesn't have the `cpu()` attribute to move the tensor from GPU to CPU.
> 
> Regarding the utilization of `torch.no_grad()` and `torch.cuda.empty_cache()`, they may not be enough to clear the GPU memory as expected in every case due to how PyTorch manages its memory. As PyTorch retains computational graphs for backward pass (gradient calculation), numerous tensors generated can build up over time and take up considerable memory.
> 
> To resolve this, I suggest you transfer the results to CPU for each prediction before storing them. This will ensure that GPU memory space is not occupied when not performing inference. To achieve this, convert the result to a list or NumPy array before storing it in your `outputs` list. This will move the result from the GPU memory to CPU. After this, you can then safely append to `outputs` as normal.
> 
> Remember to delete unneeded tensors and variables then call `torch.cuda.empty_cache()` to free up GPU space, after you're done with each batch. Following this approach should help manage the GPU memory in an optimal way while still performing batch predictions.


Thanks for your reply. I will try that.

**Comment by Laughing-q** [comment]
@y200504040u oh sorry I forgot it's a list, please try:
```python
results = model(inputs)
outputs.extend([result.cpu() for result in results])
```

**Comment by y200504040u** [comment]
> @y200504040u oh sorry I forgot it's a list, please try:
> 
> ```python
> results = model(inputs)
> outputs.extend([result.cpu() for result in results])
> ```


This seems to have solved the problem.
Thanks a lot.

**Comment by glenn-jocher** [comment]
@y200504040u you're welcome! I'm glad to hear that the issue has been resolved. Please don't hesitate to reach out if you encounter further problems. Happy coding!

**Comment by Franpper** [comment]
楼主你好，请问你是怎么解决的这个问题？我在对视频进行分割与追踪时GPU内存一直上升，导致out of memory。

**Comment by glenn-jocher** [comment]
@Franpper 您好，这个问题可能是因为结果张量在GPU上累积造成的。当使用 `model(inputs, stream=True)` 时，它会返回一个生成器，该生成器没有 `cpu()` 属性来将张量从GPU移动到CPU。使用 `torch.no_grad()` 和 `torch.cuda.empty_cache()` 可能无法如预期般清楚GPU内存，因为PyTorch如何管理其内存。为了解决这个问题，我建议在储存之前将每次预测的结果转移到CPU。这样，当不进行推理时，就不会占用GPU内存空间。您可以将结果转换为列表或 NumPy 数组，然后像往常一样将其放到 `outputs` 列表中。这样可以将结果从GPU内存移动到CPU。当您处理完每个批次后，记得删除不需要的张量和变量，然后调用 `torch.cuda.empty_cache()` 释放GPU空间。遵循这种方法应该可以在执行批次预测时以最佳方式管理GPU内存。
