### ISSUE TITLE
yolov8 model not able to access CUDA device 

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#4144]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hey @glenn-jocher i recently tried utilizing gpu of my jetson nano (4.6.1) by passing argument as device=0
but the following error showed up
torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
but ive pulled the latest image from docker and installed all dependencies why am i facing this error

i tried the same thing outside the container by installing the compatible versions of torch and torch vision i even checked the version CUDA  was available 
but i tried running the model on gpu and the same error popped up

![WhatsApp Image 2023-08-03 at 6 59 26 PM](https://github.com/ultralytics/ultralytics/assets/128675058/c31caf98-647a-47b2-af36-512a87f483dc)

**Comment by glenn-jocher** [comment]
@coder-glitche hi there,

Thanks for reaching out with this issue regarding CUDA device access when using YOLOv8 on your Jetson Nano.

Based on the information shared, the issue arises from the Docker container not having access to the GPU of your Jetson Nano, which is why `torch.cuda.is_available(): False` and `torch.cuda.device_count(): 0` are being returned.

With Docker, it's important to note that it doesn't automatically provide containers access to the host's GPUs. For NVIDIA GPUs like one in Jetson Nano, you'll have to use NVIDIA's Docker plugin, commonly referred to as `nvidia-docker`. When running your docker container, ensure you are using the `--gpus all` flag which should allow access to the GPU for the Docker container.

You mentioned that CUDA was available when checking outside the container, this is expected as your native environment should have full access to your Jetson Nano's GPU. 

If you continue to face challenges even after ensuring correct Docker container initiation, do get back to us. We'd be more than willing to assist you in resolving this issue.

Best regards,
Glenn

**Comment by coder-glitche** [comment]
Hey @glenn-jocher i had 2 ultralytics distribution one inside a docker container and the other in host machine see ive verified the whether CUDA is present locally and  ran my model locally but when model is loading the above issue appeared check the image above ive run the model locally and im getting the error why is the model not able to access the GPU within the system
Lets assume maybe ive not installed a version not compatible with my jetson nano  so i ran it on docker to check and the same error is popping up in docker and gpu is still not accessible even with ultralytics present on container
Can you please provide a modified docker file which grants access to gpu or anything i should try locally im stuck with this error please and thanks
But one thing that i tried was i checked cv2.get.cudaenabled.devices it returns 0 but i dont know what it means

**Comment by glenn-jocher** [comment]
@coder-glitche hi there,

Thank you for providing more details about your issue.

Starting with your local machine, the CUDA tool, and its associated libraries need to be installed and correctly configured for the CUDA device to function properly. This involves ensuring the correct version of CUDA is installed that is compatible with both your GPU and the installed versions of PyTorch and torchvision. Remember to also specify the CUDA device when running your script by setting the device index, i.e., `device = 0` if you're using a single GPU.

As for the issue in Docker, this most likely arises because Docker containers don't automatically have access to the host machine's GPU resources. Nvidia provides a Docker plugin, known as `nvidia-docker`, which needs to be installed on the host machine. This plugin gives Docker containers access to the GPU resources. When starting your Docker container, include the `--gpus all` flag. This grants your Docker container access to the GPU.

The response of `cv2.get.cudaenabled.devices = 0` indicates that no CUDA-enabled devices (GPUs) were found. This verifies that the issue you're experiencing relates to accessing the GPU.

Finally, regarding providing a Dockerfile modification or other local changes, my best advice is to ensure your CUDA toolkit and drivers are correctly installed and the `nvidia-docker` plugin is correctly set up. 

Keep me posted on your progress, and if you need further assistance, don't hesitate to ask.

Best regards,
Glenn

**Comment by coder-glitche** [comment]
hey @glenn-jocher i was able to access my gpu after following cuda enabed torch build .thanks alot.i have a doubt how do i train my classification model pretrained with custom dataset i want to train the same classes with fresh dataset not forgetting the dataset previously trained wit how do i achieve this through CLI
 i tried 
yolo classify train data=model=yolov8n-cls.yaml pretrained=yolov8n-cls.pt epochs=100 imgsz=64
but faced a issue with YAML file like
ValueError: nc not specified. Must specify nc in model.yaml or function arguments.
so i tried specifying number of classes as 72
which led to other error
KeyError: 'backbone'
how should my yaml file be created?? whats the CLI command i need to pass
is the approach im following correct
thanks alot!!!

**Comment by typsport** [comment]
> torch.cuda.device_count()

What was the solution

**Comment by glenn-jocher** [comment]
@typsport the solution was to use a CUDA-enabled PyTorch build that is compatible with your GPU. This allowed your system to recognize and utilize the GPU for PyTorch operations.
