### ISSUE TITLE
classify the 2-class dataset but encountered the error: Assertion `t >= 0 && t < n_classes` failed.

### ISSUE THREAD

**Issue by Aria-Leo** [ultralytics/ultralytics#4518]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I have maded a 2-class dataset, and installed ultralytics on centos with pip as described in docs:

```
conda create -n pytyorch_v3 python=3.10
pip install -r requirements.txt
pip install ultralytics
```

When I run this command:
`yolo classify train data=DATAPATH/human_other_cls model=yolov8s-cls.pt epochs=10 batch=64 imgsz=288 optimizer=AdamW lr0=0.001 label_smoothing=0.1 weight_decay=0.00005`

Getting this error:
```
train: DATAPATH/human_other_cls/train... found 68628 images in 2 classes ✅ 
val: DATAPATH/human_other_cls/val... found 8580 images in 2 classes ✅ 
test: None
Overriding model.yaml nc=1000 with nc=2

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]           
  9                  -1  1    660482  ultralytics.nn.modules.head.Classify         [512, 2]                      
YOLOv8s-cls summary: 99 layers, 5083298 parameters, 5083298 gradients
Transferred 156/158 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning DATAPATH/human_other_cls/train... 68628 images, 0 corrupt: 100%|██████████| 68628/68628 [00:42<00:00, 1613.69it/s]
train: New cache created: DATAPATH/human_other_cls/train.cache
val: Scanning DATAPATH/human_other_cls/val... 8580 images, 0 corrupt: 100%|██████████| 8580/8580 [00:04<00:00, 1973.75it/s]
val: New cache created: DATAPATH/human_other_cls/val.cache
optimizer: AdamW(lr=0.001, momentum=0.937) with parameter groups 26 weight(decay=0.0), 27 weight(decay=5e-05), 27 bias(decay=0.0)
Image sizes 288 train, 288 val
Using 8 dataloader workers
Logging results to runs/classify/human_yolov8
Starting training for 10 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem       loss  Instances       Size
  0%|          | 0/1073 [00:00<?, ?it/s]../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [16,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [17,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [18,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [21,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [22,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [23,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [24,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [25,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [26,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [29,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.
  0%|          | 0/1073 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "anaconda3/envs/pytorch_v3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "anaconda3/envs/pytorch_v3/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 432, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "anaconda3/envs/pytorch_v3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 377, in train
    self.trainer.train()
  File "anaconda3/envs/pytorch_v3/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 193, in train
    self._do_train(world_size)
  File "anaconda3/envs/pytorch_v3/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 358, in _do_train
    self.scaler.scale(self.loss).backward()
  File "anaconda3/envs/pytorch_v3/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "anaconda3/envs/pytorch_v3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

So I try to git clone the ultralytics and debug to locate the issue, and I find something.
When I insert print info at this location:
```
"File ultralytics/ultralytics/data/dataset.py", line 225: 
220         super().__init__(root=root)
221         if augment and args.fraction < 1.0:  # reduce training fraction
222             self.samples = self.samples[:round(len(self.samples) * args.fraction)]
223         self.prefix = colorstr(f'{prefix}: ') if prefix else ''
224         self.cache_ram = cache is True or cache == 'ram'
225         self.cache_disk = cache == 'disk'
226         print('Before verification:')
227         for i in range(10):
228             print(self.samples[i])
229         print('..................')
230         self.samples = self.verify_images()  # filter out bad images
231         print('After:')
232         for i in range(10):
233             print(self.samples[i])
```

And run ultralytics/ultralytics/tests/test_engine.py:

```
(Update the data path to my own in the "test_classify" function)
def test_classify():
    overrides = {'data': 'DATAPATH/human_other_cls', 'model': CFG_CLS, 'imgsz': 32, 'epochs': 1, 'save': False}
    CFG.data = 'DATAPATH/human_other_cls'
    CFG.imgsz = 32
    # YOLO(CFG_SEG).train(**overrides)  # works

    # Trainer
    trainer = classify.ClassificationTrainer(overrides=overrides)
    trainer.add_callback('on_train_start', test_func)
    assert test_func in trainer.callbacks['on_train_start'], 'callback test failed'
    trainer.train()

    # Validator
    val = classify.ClassificationValidator(args=CFG)
    val.add_callback('on_val_start', test_func)
    assert test_func in val.callbacks['on_val_start'], 'callback test failed'
    val(model=trainer.best)

    # Predictor
    pred = classify.ClassificationPredictor(overrides={'imgsz': [64, 64]})
    pred.add_callback('on_predict_start', test_func)
    assert test_func in pred.callbacks['on_predict_start'], 'callback test failed'
    result = pred(source=ASSETS, model=trainer.best)
    assert len(result), 'predictor test failed'


if __name__ == '__main__':
    test_classify()

Running results:
...
YOLOv8n-cls summary: 99 layers, 1440850 parameters, 1440850 gradients
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
Before verification:
('DATAPATH/human_other_cls/train/other/n01443537_10007.JPEG', 0)
('DATAPATH/human_other_cls/train/other/n01443537_10014.JPEG', 0)
('DATAPATH/human_other_cls/train/other/n01443537_10025.JPEG', 0)
('DATAPATH/human_other_cls/train/other/n01443537_10034.JPEG', 0)
('DATAPATH/human_other_cls/train/other/n01443537_10035.JPEG', 0)
('DATAPATH/human_other_cls/train/other/n01443537_10078.JPEG', 0)
('DATAPATH/human_other_cls/train/other/n01443537_10083.JPEG', 0)
('DATAPATH/human_other_cls/train/other/n01443537_10086.JPEG', 0)
('DATAPATH/human_other_cls/train/other/n01443537_10087.JPEG', 0)
('DATAPATH/human_other_cls/train/other/n01443537_10092.JPEG', 0)
..................
train: Scanning /mnt/sdb/dataset/human_other_cls/train... 68628 images, 0 corrupt: 100%|██████████| 68628/68628 [00:00<?, ?it/s]
After:
('DATAPATH/human_other_cls/train/other/n01443537_10007.JPEG', 0)
('DATAPATH/human_other_cls/train/other/n01443537_10014.JPEG', 1)
('DATAPATH/human_other_cls/train/other/n01443537_10025.JPEG', 2)
('DATAPATH/human_other_cls/train/other/n01443537_10034.JPEG', 3)
('DATAPATH/human_other_cls/train/other/n01443537_10035.JPEG', 4)
('DATAPATH/human_other_cls/train/other/n01443537_10078.JPEG', 5)
('DATAPATH/human_other_cls/train/other/n01443537_10083.JPEG', 6)
('DATAPATH/human_other_cls/train/other/n01443537_10086.JPEG', 7)
('DATAPATH/human_other_cls/train/other/n01443537_10087.JPEG', 8)
('DATAPATH/human_other_cls/train/other/n01443537_10092.JPEG', 9)
...
```
After the 'self.verify_images()' function, the labels are changed, causing them to go out of range.

### Environment

- YOLO: Ultralytics YOLOv8.0.160 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA RTX A4000, 16109MiB)
- OS: CentOS Linux release 8.3.2011

### Minimal Reproducible Example

`yolo classify train data=DATAPATH/human_other_cls model=yolov8s-cls.pt epochs=10 batch=64 imgsz=288 optimizer=AdamW lr0=0.001 label_smoothing=0.1 weight_decay=0.00005`

Since the dataset is large, I'm sampling only a portion of it to create a smaller one,  the error situation remains the same.
[human_other_cls.zip](https://github.com/ultralytics/ultralytics/files/12419381/human_other_cls.zip)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by whn09** [comment]
I think the latest version has bug, and I reverted to 8.0.159, the error disappeared.

**Comment by glenn-jocher** [comment]
@Aria-Leo yes I was about to say 8.0.160 has a Classify training bug first reported in #4514, please update to 8.0.161 to resolve this issue.

**Comment by Aria-Leo** [comment]
> @Aria-Leo yes 8.0.160 has a Classify training bug first reported in #4514, please update to 8.0.161 to resolve this issue.

Ok, thanks!

**Comment by glenn-jocher** [comment]
@confident-luchu you're welcome! If you have any more questions or issues in the future, don't hesitate to ask. Happy coding!
