### ISSUE TITLE
How to train model on small images? "index out of bounds"` failed

### ISSUE THREAD

**Issue by fridary** [ultralytics/ultralytics#5051]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

* Python: 3.9.17
* ultralytics: 8.0.171
* OS: Ubuntu 20.04

I have an app where users need to send small images to detect icons. The size of image is 119x19. Everything is okey if I train on other higher images, but with this size I get errors below. How can I fix it?

```python
model = YOLO("yolov8m.yaml")
model.train(data='data.yaml', batch=8, imgsz=119, epochs=600, verbose=True)
```

If I change 119 to smaller or bigger (128), or don't set `imgsz` param, error is equal.

### Additional

```
$ python train.py

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]                 
 22        [15, 18, 21]  1   3822016  ultralytics.nn.modules.head.Detect           [80, [192, 384, 576]]         
YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients

New https://pypi.org/project/ultralytics/8.0.184 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.171 🚀 Python-3.9.17 torch-2.0.1 CUDA:0 (Tesla K80, 12207MiB)
engine/trainer: task=detect, mode=train, model=yolov8m.yaml, data=data.yaml, epochs=600, patience=50, batch=8, imgsz=119, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train8
Overriding model.yaml nc=80 with nc=42

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]                 
 22        [15, 18, 21]  1   3800014  ultralytics.nn.modules.head.Detect           [42, [192, 384, 576]]         
YOLOv8m summary: 295 layers, 25880638 parameters, 25880622 gradients

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
WARNING ⚠️ imgsz=[119] must be multiple of max stride 32, updating to [128]
train: Scanning /home/fridary/python/yolo/datasets_classif_Screen_test/train/labels.cache... 98 images, 0 backgrounds, 0 corrupt: 100%|██████████| 98/98 [00:00<?,
val: Scanning /home/fridary/python/yolo/datasets_classif_Screen_test/valid/labels.cache... 21 images, 0 backgrounds, 0 corrupt: 100%|██████████| 21/21 [00:00<?, ?
Plotting labels to runs/detect/train8/labels.jpg... 
optimizer: AdamW(lr=0.000217, momentum=0.9) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 128 train, 128 val
Using 8 dataloader workers
Logging results to runs/detect/train8
Starting training for 600 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/600      1.06G     0.8528       3.11     0.5316         16        128: 100%|██████████| 13/13 [00:05<00:00,  2.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  8.91it/s]
                   all         21         84          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/600      1.06G      1.186      3.435     0.7049         62        128:  85%|████████▍ | 11/13 [00:03<00:00,  3.48it/s]/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [65,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [66,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [72,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [73,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [74,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [76,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [77,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [78,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [80,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [81,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [82,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [84,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [85,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [86,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [88,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [89,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [90,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [96,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [97,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [98,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [100,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [101,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [102,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [104,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [105,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [106,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [108,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [109,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [110,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [112,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [113,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [114,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [116,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [117,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [118,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [120,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [121,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [122,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [124,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [4,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [5,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [6,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [8,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: 

... cropped ...

[55,0,0], thread: [90,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [96,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [97,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [98,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [100,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [101,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [102,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [104,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [105,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [106,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [108,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [109,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [110,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [112,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [113,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [114,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [116,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [117,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [118,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [120,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [121,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [122,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [124,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343964576/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [55,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
      2/600      1.06G      1.186      3.435     0.7049         62        128:  85%|████████▍ | 11/13 [00:03<00:00,  3.30it/s]
Traceback (most recent call last):
  File "/home/fridary/python/yolo/train.py", line 21, in <module>
    model.train(data='data_c.yaml', batch=8, imgsz=119, epochs=600, verbose=True) # classif
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 348, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 44, in forward
    return self.loss(x, *args, **kwargs)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 215, in loss
    return self.criterion(preds, batch)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/utils/loss.py", line 181, in __call__
    _, target_bboxes, target_scores, fg_mask, _ = self.assigner(
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/utils/tal.py", line 115, in forward
    mask_pos, align_metric, overlaps = self.get_pos_mask(pd_scores, pd_bboxes, gt_labels, gt_bboxes, anc_points,
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/utils/tal.py", line 136, in get_pos_mask
    align_metric, overlaps = self.get_box_metrics(pd_scores, pd_bboxes, gt_labels, gt_bboxes, mask_in_gts * mask_gt)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/utils/tal.py", line 155, in get_box_metrics
    bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*w
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

**Comment by RizwanMunawar** [comment]
Hello @fridary, I appreciate the information you've provided! Would it be possible for you to share a few images from the dataset? This would greatly assist in gaining a more comprehensive understanding of your issue. I'd like to conduct some testing. 

Thanks

**Comment by fridary** [comment]
@RizwanMunawar sure, thank you very much.

[dataset_with_small_images.zip](https://github.com/ultralytics/ultralytics/files/12705528/dataset_with_small_images.zip)

**Comment by RizwanMunawar** [comment]
Hi @fridary! Thanks for sharing the dataset. After conducting some testing, it appears that there's an issue with the dataset itself, not the model. In the training data, there were originally 99 images, but it turns out that 13 of them were unusable and were causing errors. I've relocated these problematic images to the `train/corrupted img-labels` folder.

The remaining data is working well for training purposes. You can utilize the dataset I've provided for any further testing you'd like to perform. 

You can download the attached file, extract its contents, and initiate the training process by using the provided command below.

```CLI
python train.py
```

### Modified Dataset Link

[modified_dataset_with_small_images.zip](https://github.com/ultralytics/ultralytics/files/12705577/modified_dataset_with_small_images.zip)

**Comment by fridary** [comment]
@RizwanMunawar thank you very much, but how did you figure out what images are corrupted? They have the same width, height, file size and look the same

**Comment by fridary** [comment]
@RizwanMunawar ? Need your help again

**Comment by glenn-jocher** [comment]
Hi @fridary, sorry to hear that you're still seeing errors with the updated dataset. From your description and the logs, it seems that the issue could still be related to the images, even if they appear to be alright visually or based on their metadata.

Sometimes images can be corrupted in ways that are not immediately obvious. They might appear normal when opened with an image viewer, but may have underlying issues that cause problems when they are read by an image processing algorithm. 

The error you're seeing might not be due to the size or aspect ratio of the images, but could be due to other factors like the color space, image format, or metadata in the images.

To find the damaged images, you could try opening and processing each image individually with the same library that is used by the training code (such as OpenCV or PIL), and see if any of them cause errors.
 
Alternatively, it is also possible that there is an issue with how the image files are being read, or how the data is being loaded or preprocessed before training. You could check if the training code is correctly loading and preprocessing the images, or if there could be any issues with the file paths, file permissions, or memory usage.

Finally, if the training works with a different dataset, this suggests that the issue is related to the particular images in your dataset. It might be worthwhile to carefully inspect the troubled dataset and run some checks or cleaning procedures to ensure the quality and integrity of the data.

I hope this helps, and don't hesitate to reach out if you have further questions or need more assistance!

**Comment by RizwanMunawar** [comment]
@fridary, I'm glad to hear that your problem has been resolved, and it appears to be unrelated to the model.

As for addressing image corruption, I performed a manual examination by executing the training command after every set of ten images. Regrettably, there isn't a straightforward solution for this issue. I'm not well-versed in how image manipulation works in Photoshop, but occasionally, the image format can significantly impact the outcome.

**Comment by laogonggong847** [comment]
hello @glenn-jocher ， @RizwanMunawar Ri
I encountered the same error while training my own dataset using YOLO V8. In order to verify if it's the same as what you guys are saying that it might be caused by an error in the meta-images themselves, so I checked these images with opencv and found no problem. I will provide my dataset below and hopefully I can get some help from you guys.

I'm using the YOLO V8 segmentation model.
[YOLODogCat.zip](https://github.com/ultralytics/ultralytics/files/12843175/YOLODogCat.zip)


thank you very much

**Comment by glenn-jocher** [comment]
@laogonggong847 hello, 

Thank you for providing the dataset and for verifying your images with OpenCV. In cases like this, even though images may appear fine with a certain library or image viewer, there could still be underlying challenges that affect the compatibility with the YOLOv8 model.

The error could be caused by various factors such as the format, color space, or specific metadata of the images. Apart from this, the way the image files are being read or how the data is being preprocessed before training could also impact. 

A method to isolate the problematic image(s) could be to attempt training the model with a limited number of images and gradually add more to the training set. Identifying a pattern in the images causing the error will help find a solution more effectively.

I hope this helps! Please don't hesitate to reach out if you have further questions or if you encounter more challenges.

**Comment by glenn-jocher** [comment]
@fridary, I agree that manually checking each image when dealing with large datasets isn't practical. It's more of a last resort when other methods fail. 

Corrupted images can sometimes be tricky to identify because they might appear normal, but may have issues with their underlying data. The nature of the errors you're seeing suggests there may be issues with certain images in your dataset.

To deal with this programmatically, one option might be to write a script that attempts to open and process each image individually using the same libraries as your training code. If there's an issue with an image, you should catch an exception when trying to process it. 

Another strategy could use some sort of data sanitisation or cleaning process before training. You could run some routine checks on each image to make sure there are no glaring issues. For example, you could check if the images are in the correct format, if they have the right color space, if their metadata is correctly formatted, etc. 

It's also possible that the issue isn't with the images themselves, but how they're being loaded or preprocessed in your code. So it would be helpful to carefully review your data loading and preprocessing steps to make sure everything is working correctly.

I realize this isn't a perfect solution. Debugging issues like this can often involve a bit of trial and error. But hopefully this gives you a good starting point.

**Comment by stillfighter2** [comment]
@glenn-jocher Hello sir, my code is currently experiencing similar issues. Can you help me check if this is the case? Could you please tell me your experience in finding the wrong image? Below, I have provided some of my datasets, and perhaps you can help me directly solve this problem. This dataset is not complete because only 25MB files can be uploaded on GitHub.
[dataset2.zip](https://github.com/ultralytics/ultralytics/files/13332845/dataset2.zip)

**Comment by glenn-jocher** [comment]
@stillfighter2 hello,

I understand that troubleshooting dataset issues can be frustrating, especially with large numbers of images. It is important to ensure that the dataset is clean and that the images are compatible with the model's expected input.

Since I am unable to directly inspect or download the provided dataset, I recommend conducting a systematic review of the images using a script, as previously mentioned. The script should attempt to load, decode, and process each image and its corresponding annotation using the same libraries and methods that the training script utilizes.

An example approach would be to write a Python script that iterates over every image file in your dataset, attempting to load the image and parse the associated annotation file. If the script encounters an error or exception with a particular image or annotation, it should log the problematic file for further inspection.

To ensure that your images and annotations are being correctly processed, consider the following checks and procedures:
- Verify image sizes and formats are consistent with what your model expects.
- Check for anomalies in the annotations and if they align with the images.
- Make sure that there are no issues related to the file paths, file names, or permissions.
- Inspect for any corrupted files that might not be processed correctly by image handling libraries.

Once you've cleaned your dataset and confirmed that there are no underlying issues with the images and annotations, you can try retraining your model. If problems persist, review your data loading and augmentation code for potential sources of error.

Remember that any data inspection and handling scripts that you develop can become part of your dataset validation process, helping to prevent similar issues in the future.

Considering the complexity of machine learning workflows, sometimes debugging might require a few iterations to isolate and fix the problem. Keep refining the process, and you'll find a solution. Good luck with your model training.
