### ISSUE TITLE
NaN in all results when training

### ISSUE THREAD

**Issue by codingpigeon007** [ultralytics/ultralytics#5294]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug
Hi! 
I get "NaN" in all results when training on NVIDIA GeForce GTX 1660 SUPER, 6144MiB (Python-3.9.16 torch-2.0.1+cu118 CUDA:0). This only happens when I train on GPU. On CPU training works as usual, but it just takes way too much time. When I start the training, I get AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n... AMP: checks passed. So AMP is not an issue here.

Also, what I noticed on Task Manager, is that it uses 46% CPU, 87% Memory and only 8% GPU when training. I use batch size 16 and when I try to increase batch size, I get "CUDA out of memory", so that is the optimal batch size. 

I trained the YOLOv8 using the same settings before and it worked just fine. But now no matter what I do - it is always NaN.

Are there any suggestions how to deal with this problem? 
Thank you in advance!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@codingpigeon007 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by codingpigeon007** [comment]
Hi, thank you for such a fast response! I have the latest ultralytics version and I did not do any changes in the code. I mentioned all the parameters in the previous message. The command I use is "yolo task=detect mode=train epochs=2000 data=data.yaml model=yolov8n.pt imgsz=640 batch=16". And I noticed that people are having issues with GPU 16xx when trying to train YOLOv5 and YOLOv8. I tried training and fine-tuning and both have the same "NaN" result. Are there any solutions that come to mind for this issue that could be a fast fix?

**Comment by glenn-jocher** [comment]
@codingpigeon007 it's quite possible that the issue is linked to your GPU or specific setup considering you're experiencing NaN results only with GPU. However, to better diagnose your problem, you should analyze the training data along with the respective labels for accuracy and integrity.

Check your data.yaml file and ensure the correct format for train and val paths. You'll also want to handle any potential overfitting, which could be causing the NaN values in your loss function. You can try lower learning rates or simply using a smaller model.

Regarding the GPU, the GeForce GTX 16xx series is quite capable and should work fine with YOLOv8. A potential issue could be the limited GPU memory. And keep in mind that allocating large batch sizes uses a lot of GPU memory.

Recall that CUDA erros such as an "out of memory" issue can also lead to NaN outcomes. Ensure the correct CUDA drivers are installed to compliment the GPU. Consider easing the load on your GPU by reducing your batch size to a value that your GPU memory can handle.

Lastly, try disabling Automatic Mixed Precision (AMP) and see it it makes any difference. This can be done by setting "--amp" command to False.

Hope this can help you identify the issue! Let us know if you need any further assistance.

**Comment by codingpigeon007** [comment]
Hi,
Thank you for your suggestions. I set amp to False and it fixed the issue.

**Comment by codingpigeon007** [comment]
Hi, thank you for your suggestions! Setting amp to False fixed the training issue. But now I sometimes get no graphs in val/box_loss; val/clc_loss; val/dfl_loss. I don't change the dataset, and the training overall looks good except the part for not having val graphs sometimes. Are there any suggestions why this is happening? And what can I do to fix it?

**Comment by glenn-jocher** [comment]
Hello @codingpigeon007, 

I'm glad to hear that setting AMP to False has helped you navigate the training issues. When it comes to missing or inconsistent validation graphs, there are a few potential explanations which we can look into. 

One possibility could be that there are some intermittent issues in reading or processing your data during the validation steps. This can occur due to issues with your validation dataset or how its paths are mapped in the config files.

Another reason might be linked to how and when the losses are logged during the validation step. If the model doesn't run any iterations for validation or if it isn't logging losses properly, this could potentially explain the absence of these graphs. 

As a starting point, ensure that your validation dataset is properly formatted and its paths are correctly set in your data.yaml file. You may also want to look into the logging and visualization parameters in your training settings.

Without the specifics, it's a bit challenging to give more explicit guidance, but I hope these initial pointers help you start to identify the issue. 
Let me know how it goes!

**Comment by glenn-jocher** [comment]
@s907461903 hello,

Yes, if a training image doesn't have any associated labels then it can cause problems during the training process. During training, the model learns to identify objects in an image by associating the image with its labels. Without these labels, the model doesn't have a reference to learn from, which can result in bad training performance or unexpected results.

Moreover, it can also cause issues if these unlabeled images make up a significant portion of your training data. The model will learn from whatever data you feed it, so if a lot of your images are unlabeled, it might learn to not identify objects effectively.

Therefore, it's generally a good idea to make sure that all your training data is labeled accurately. Without labels, the training process can be hindered, and the quality of the model's predictions can be impacted. I hope this clarifies your query!

**Comment by AUTUMN1124** [comment]
Yesterday, YOLOv8 training was running normally, but today it has been training for over two hours without any results. What could be the reason?

**Comment by AUTUMN1124** [comment]
Hello, I'd like to ask why YOLOv8 training was normal yesterday, but today, it has been training for over two hours without any results.

**Comment by Akuva2001** [comment]
Exactly same problem with same GPU (also tried in docker)

**Comment by glenn-jocher** [comment]
Hello again @Akuva2001,

It's intriguing that you're experiencing the same issue with your GPU and within a Docker container. If the problem persists across different environments, it hints at a more systemic issue, which might not be directly related to the environment or the hardware.

Here are a few general steps you could take to troubleshoot this matter:

1. **Data Validation:** Ensure all images in your dataset have corresponding label files, even if some images have no objects (and thus would have empty label files). Eliminating images without labels from the training set could improve stability during training.

2. **Hyperparameters Adjustment:** If NaNs appear, consider adjusting training hyperparameters. This could include lowering the learning rate, changing the optimizer, or adjusting other hyperparameters that might influence training stability.

3. **Check Point Loading:** When using pre-trained weights, make sure they're compatible with your model architecture and the version of the codebase you're working with.

4. **System Monitoring:** Observe your system's resource usage to ensure it's not running into hardware limitations, such as insufficient GPU memory, which might be impacting the training process.

If adjusting `--amp` to False has rectified NaNs during training but you still encounter issues with missing validation graphs, you might want to review how validation losses are logged and visualized in your setup. Ensuring consistency in validation can often come down to how the data is processed and interpreted by the training script during each epoch.

Remember to also check that your environment, including all dependencies and libraries, are properly installed and up-to-date within the Docker container. Discrepancies in library versions or corrupted installations can sometimes cause unexpected behavior.

If these steps don't resolve your issue, you may want to isolate whether this is a systemic issue with all training or specific to particular datasets or model configurations. This can help narrow down the root cause. If necessary, you can always revisit the documentation for further insights or consider sharing a minimum reproducible example to seek more tailored support.

Good luck, and keep us posted on your progress!
