### ISSUE TITLE
Error with CUDA on object detections

### ISSUE THREAD

**Issue by diegudc** [ultralytics/ultralytics#6410]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Other

### Bug

Hi @glenn-jocher 
I'm researching some information about my problem but i haven't solutions. 

I have trying some detections with the webcam and i have these **errors**:

> _Traceback (most recent call last):
>   File "c:/Users/diegodc/Desktop/prueba/detect.py", line 5, in <module>
>     results=model(source=0,show=True,conf=0.7,save=False)
>   File "C:\Users\diegodc\anaconda3\envs\yolo8\lib\site-packages\ultralytics\engine\model.py", line 98, in __call__        
>     return self.predict(source, stream, **kwargs)
>   File "C:\Users\diegodc\anaconda3\envs\yolo8\lib\site-packages\ultralytics\engine\model.py", line 232, in predict        
>     self.predictor.setup_model(model=self.model, verbose=is_cli)
> ontext                                                                                                              _model
>     return func(*args, **kwargs)
>   File "C:\Users\diegodc\anaconda3\envs\yolo8\lib\site-packages\ultralytics\nn\autobackend.py", line 115, in __init_ontext_
>     model = model.fuse(verbose=verbose) if fuse else model                                                          _
>   File "C:\Users\diegodc\anaconda3\envs\yolo8\lib\site-packages\ultralytics\nn\tasks.py", line 129, in fuse
>     m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
>   File "C:\Users\diegodc\anaconda3\envs\yolo8\lib\site-packages\ultralytics\utils\torch_utils.py", line 171, in fuse_conv_and_bn                                                                                                        _conv_and_bn     
>     w_bn = torch.diag(bn.weight.div(torch.sqrt(bn.eps + bn.running_var)))
> RuntimeError: CUDA error: no kernel image is available for execution on the device_
> 

The **code** is one of your examples from youtbe:
```
from ultralytics import YOLO
model = YOLO( 'yolov8n.pt')
results=model(source=0,show=True,conf=0.7,save=False)
```

I am currently using an Nvidia Tesla K40c GPU, with PyTorch version 1.8.0 and CUDA 11.1. The GPU is compatible, and I have no issues as I have run the following code to verify the functionality of PyTorch and have obtained optimal results.
          **CODE:**
 ```
  import torch
  import sys
  print('A',sys.version)
  print('B',torch.__version__)
  print('C',torch.cuda.is_available())
  print('D',torch.backends.cudnn.enabled)
  device=torch.device('cuda')
  print('E',torch.cuda.get_device_properties(device))
  print('F',torch.tensor([1.0+i,2.0]))
```
**RESULTS**

> A 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]
> B 1.8.0+cu111
> C True
> D True
> E _CudaDeviceProperties(name='Tesla K40c', major=3, minor=5, total_memory=11448MB, multi_processor_count=15)        
> F tensor([1., 2.])
> 

Thank you for your time and consideration! 

### Environment

I'm using a SO of Windows 10, which a GPU of NVIDIA TeslaK40c wich CUDA 11.1 and version of YOLOV8 by Ultralytics 8.0.211 with python 3.8.

Another libraries i'm using for this proyect are>
```
Package             Version
------------------- --------------------
certifi             2023.7.22
charset-normalizer  3.3.2
colorama            0.4.6
contourpy           1.1.1
cycler              0.12.1
filelock            3.13.1
fonttools           4.44.3
fsspec              2023.10.0
idna                3.4
importlib-resources 6.1.1
Jinja2              3.1.2
kiwisolver          1.4.5
MarkupSafe          2.1.3
matplotlib          3.7.3
mpmath              1.3.0
networkx            3.1
numpy               1.24.4
opencv-python       4.8.1.78
packaging           23.2
pandas              2.0.3
Pillow              10.1.0
pip                 23.3
psutil              5.9.6
py-cpuinfo          9.0.0
pyparsing           3.1.1
python-dateutil     2.8.2
pytz                2023.3.post1
PyYAML              6.0.1
requests            2.31.0
scipy               1.10.1
seaborn             0.13.0
setuptools          68.0.0
six                 1.16.0
sympy               1.12
thop                0.1.1.post2209072238
torch               1.8.0+cu111
torchaudio          0.8.0
torchvision         0.9.0+cu111
tqdm                4.66.1
typing_extensions   4.8.0
tzdata              2023.3
ultralytics         8.0.211
urllib3             2.1.0
wheel               0.41.2
zipp                3.17.0
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@diegudc hola, y gracias por reportar este problema con YOLOv8 y tu con la NVIDIA Tesla K40c. 😊

El mensaje de error que has recibido indica que hay un problema con la compatibilidad de CUDA con tu dispositivo. Esto generalmente sucede cuando la versión de PyTorch que estás utilizando no está correctamente compilada para la arquitectura específica de tu tarjeta gráfica, o cuando falta el soporte adecuado para la versión de CUDA que estás usando.

Como utilizas una Tesla K40c, es importante saber que esta tiene una capacidad de cómputo 3.5 (Kepler), lo que significa que debes asegurarte de que la versión de PyTorch que instalas tiene soporte para esta arquitectura. Desde PyTorch 1.9 en adelante, el soporte para arquitecturas de cómputo menores a 5.0 (Maxwell) ha sido descontinuado.

Considerando que PyTorch 1.8 debería funcionar, tu problema puede ser causado por una de las siguientes razones:

1. La versión de PyTorch instalada no es compatible con la capacidad de cómputo 3.5 de tu tarjeta gráfica. Normalmente, las versiones precompiladas de PyTorch vienen con soporte para múltiples arquitecturas, pero puede haber ocasiones en las que se necesite una compilación específica.

2. Tu instalación de CUDA o cuDNN podría no estar configurada correctamente, o las versiones de CUDA y cuDNN de PyTorch podrían no coincidir con las que están instaladas en tu sistema.

Para resolver el problema, te recomiendo que tomes los siguientes pasos:

1. Verifica la capacidad de cómputo de tu GPU y compara esto con los binarios de PyTorch disponibles. Si tu capacidad de cómputo no es soportada, requerirás compilar PyTorch desde el código fuente con soporte para tu arquitectura.

2. Asegúrate de que la versión de CUDA Toolkit instalada en tu sistema coincida con la versión usada para compilar PyTorch. 

3. Si ya tienes instaladas la versión correcta de CUDA y cuDNN, prueba reinstalando PyTorch y torchvision usando los comandos de instalación que correspondan a tu CUDA específica desde el sitio web de PyTorch.

Si después de seguir estos pasos el problema persiste, te recomendaría buscar ayuda en los foros de PyTorch, donde pueden haber usuarios con problemas similares que ya hayan encontrado una solución.

Espero que esta información te sea útil para solucionar el problema. Si tienes otras preguntas o requieres más asistencia con YOLOv8, no dudes en escribirnos nuevamente. ¡Mucho éxito! 🚀

**Comment by diegudc** [comment]
Hello @glenn-jocher !!! I'm still having issues...

Previously thank you so much for your previous advice!!. I managed to configure the GPU with CUDA 10.2 and pytorch 1.8.0, and it recognizes it with the following characteristics:

> CUDA disponible: True
> Número de GPUs disponibles: 1        
> GPU actual: Tesla K40c
> Versión de CUDA: 10.2
> Versión de cuDNN: 7605
> Versión de PyTorch: 1.8.0
> Opciones de configuración de PyTorch:
> PyTorch built with:
>   - C++ Version: 199711
>   - MSVC 192829337
>   - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications  
>   - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
>   - OpenMP 2019
>   - CPU capability usage: AVX2
>   - CUDA Runtime 10.2
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
>   - CuDNN 7.6.5
>   - Magma 2.5.4
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

However, when running the code from before (shown on the YouTube channel for real-time detection):
```
from ultralytics import YOLO
model = YOLO( 'yolov8n.pt')
results=model(source=0,show=True,conf=0.7,save=False)
```
I encounter the following error when importing YOLO:

> 
>   File "c:/Users/diegodc/Desktop/prueba/detect.py", line 3, in <module>
>     from ultralytics import YOLO
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\ultralytics\__init__.py", line 5, in <module>    
>     from ultralytics.models import RTDETR, SAM, YOLO
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
>     from .rtdetr import RTDETR
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
>     from .model import RTDETR
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in 
> <module>
>     from ultralytics.engine.model import Model
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\ultralytics\engine\model.py", line 8, in <module>    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
>     from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\ultralytics\utils\__init__.py", line 19, in <module>
>     import matplotlib.pyplot as plt
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\matplotlib\__init__.py", line 156, in <module>   
>     from . import _api, _version, cbook, _docstring, rcsetup
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>     
>     from matplotlib.colors import Colormap, is_color_like
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\matplotlib\colors.py", line 51, in <module>      
>     from PIL import Image
>   File "C:\Users\diegodc\anaconda3\envs\torch102\lib\site-packages\PIL\Image.py", line 100, in <module>
>     from . import _imaging as core
> ImportError: DLL load failed while importing _imaging: No se puede encontrar el módulo especificado.

I believe this doesn't make sense since I'm trying to visualize with the actual camera, and it's giving me an error in the DLL while importing images. Additionally, I've tried with OpenCV using the following code that I insert to you to get another point of view and I get the same error.

```
# Import libraries
from ultralytics import YOLO
import cv2

# Read model
#model = YOLO("yolov8n.pt")

# Inicialited videocapture
cap = cv2.VideoCapture(0)

while True:
    # Read frames
    ret, frame = cap.read()

    #Read results
    #resultados = model.predict(frame, imgsz = 640, conf = 0.98)

    # Show results
    #anotaciones = resultados[0].plot()

    # Show segmentation
    cv2.imshow("Img", frame)

    # Do until...
    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()
```

I can't find documentation or similar errors... 
I appreciate your concern and thanks in advance.

Best regards!!!

**Comment by diegudc** [comment]
Thank you for your help @glenn-jocher .

I had to change the versions of CUDA, cuDNN, and Torch to the following ones, which I leave below in case someone else has the same issue:

> GPU actual: Tesla K40c
> Versión de CUDA: 10.2
> Versión de cuDNN: 7605
> Versión de PyTorch: 1.8.0

Additionally, it's worth noting that you need to adjust the versions of Pyyaml and Pillow to avoid problems with DLLs.

Best regards!!!

**Comment by diegudc** [comment]
Thank you for your help @glenn-jocher .

I had to change the versions of CUDA, cuDNN, and Torch to the following ones, which I leave below in case someone else has the same issue:

> GPU actual: Tesla K40c
> Versión de CUDA: 10.2
> Versión de cuDNN: 7605
> Versión de PyTorch: 1.8.0
> 

Additionally, it's worth noting that you need to adjust the versions of Pyyaml and Pillow to avoid problems with DLLs.

Best regards!!!

**Comment by diegudc** [comment]
Hello @glenn-jocher,

I thought the problem was finally solved, but it seems I'm still dealing with it. Thank you very much for your earlier advice; I've gathered and reinstalled with new versions the CUDA 10.2, cuDNN 7.6.05, and Torch 1.8.0  

When running the code you show in the YouTube video or another code I've written using OpenCV, I still encounter the same errors. 

Below, I provide an example code to show that PyTorch recognizes my GPU, and it works in other applications. 

```
CUDA disponible: True
Número de GPUs disponibles: 1
GPU actual: Tesla K40c
Versión de CUDA: 10.2
Versión de cuDNN: 7605
Versión de PyTorch: 1.8.0
Opciones de configuración de PyTorch:
PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications  
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,
```

Do you know why it might be causing me problems in YOLO?

Best regards!!!

**Comment by glenn-jocher** [comment]
@diegudc hola de nuevo,

Entiendo que la situación puede ser frustrante. El error se relaciona con la compatibilidad de la versión de CUDA que tienes con la arquitectura de tu GPU y la versión de PyTorch. Aunque has cambiado a CUDA 10.2 y tienes PyTorch 1.8.0, que deberían ser compatibles con la arquitectura Kepler (capacidad de cómputo 3.7) de la Tesla K40c, aún enfrentas el mismo problema.

Sin embargo, puedo ofrecerte algunas recomendaciones adicionales:

1. **Verifica la Instalación de CUDA y cuDNN:** Asegúrate que todas las rutas de CUDA y cuDNN están correctamente establecidas en las variables de entorno y que no existen conflictos con versiones previamente instaladas. A veces, restos de antiguas instalaciones pueden generar conflictos.

2. **Instalación Consistente de PyTorch:** Recomiendo usar una conda environment (si no estás usando ya una) para asegurarte de que la instalación de PyTorch y todos los paquetes relacionados se encuentran aislados y no se ven afectados por otros paquetes en tu sistema.

3. **Uso de Wheel Personalizado:** Una opción podría ser buscar o compilar una wheel de PyTorch que esté específicamente diseñada para cuDNN 7.6.5 y CUDA 10.2, asegurando que esté alineada con tu entorno. A veces hay wheels personalizados disponibles que podrían ser más compatibles con tu configuración que los paquetes estándar.

4. **Utilización de Docker:** Si es factible para tu entorno de trabajo, utilizar contenedores de Docker con imágenes que tengan preinstaladas las versiones correctas de CUDA, cuDNN y PyTorch podría ser una solución para asegurar un entorno controlado y consistente.

5. **Búsqueda de Compatibilidad en Foros Específicos:** Como ha habido muchos cambios y desfasajes en torno a la compatibilidad de las GPU más antiguas con nuevas versiones de software, puede ser útil investigar en foros de PyTorch o incluso foros de NVIDIA si otros han tenido problemas similares y cómo los han solucionado.

6. **Contacto con el Soporte de Ultralytics:** Si consideras que el problema puede estar relacionado específicamente con la implementación en YOLOv8, sería adecuado plantear el problema detalladamente en el soporte de Ultralytics a través de un issue, proporcionando toda la información pertinente y los pasos que has tomado, para que el equipo pueda brindarte asistencia más específica.

La interacción entre CUDA, cuDNN y PyTorch es a menudo compleja y muy dependiente de la configuración del sistema. Sabemos que estas situaciones pueden ser complicadas, y estamos aquí para ayudarte en lo que podamos para llegar a una solución. ¡Ánimo y no dudes en volver a contactarnos si necesitas más ayuda!

**Comment by jackbench** [comment]
已收到。

**Comment by glenn-jocher** [comment]
@jackbench 如果您有其他问题或需要进一步的帮助，请随时回复此GitHub issue。祝您好运！🌟
