### ISSUE TITLE
yolov8 not running on gpu?

### ISSUE THREAD

**Issue by MaxS3552284** [ultralytics/ultralytics#664]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have the following issue/question:
I have installed the requirements in my empty anaconda env (python3.9.16) and yolov8 started training,
just as describet.
But uses the cpu instead of the gpu

torch.cuda.is_available() returned false

cuda 11 etc. are installed on the pc
but "pip install ultralytics" did not install any cuda packages 
what packages do i have to add for the model to train on the gpu?

**Comment by suryan-s** [comment]
Could you make sure that you have installed the CUDA toolkit? If not download it and add them to your path. Restart and run torch.cuda.is_available(). 
If this doesn't help look at this which might help you : https://github.com/ultralytics/yolov5/issues/7277

**Comment by MaxS3552284** [comment]
as said, cuda toolkit is installed (the .exe from nvidia)

i installed "pip install cuda-python" into the "pip install ultralytics" env , and still returns false after reload

i have now also installed the packages from the requirements.txt with their corresponding conda commands into a new env, which did install the cuda packages along with pytorch, it returns true for  torch.cuda.is_available() (but i dont get the code to run there, "No module named 'sentry_sdk'")

**Comment by suryan-s** [comment]
For your second working case, tried pip3 install sentry-sdk ?

**Comment by MaxS3552284** [comment]
i used "conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia" for the torches
and "conda install -c conda-forge sentry-sdk", <-- with this the code does ... something now ...
it says the training started, printed out a bunch of text/code with a list of layers and now i am waiting, if something is going to happen

**Comment by MaxS3552284** [comment]
after runing the code with the proper directory, the text came out properly formated, with this at the end

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by suryan-s** [comment]
> after runing the code with the proper directory, the text came out properly formated, with this at the end
> 
> RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase.
> 
> ```
>     This probably means that you are not using fork to start your
>     child processes and you have forgotten to use the proper idiom
>     in the main module:
> 
>         if __name__ == '__main__':
>             freeze_support()
>             ...
> 
>     The "freeze_support()" line can be omitted if the program
>     is not going to be frozen to produce an executable.
> ```

Hmmm, I have seen this error in the case of multiprocessing. Not sure though. Well i have MX450 which could barely survive the training, so mostly i run stuffs in colab and even on kaggle.
But your issue feels kinda same line here: https://stackoverflow.com/questions/75111196/yolov8-runtimeerror-an-attempt-has-been-made-to-start-a-new-process-before-th

Could u try this?

**Comment by suryan-s** [comment]
Hey! the issue was already raised. 
#348

**Comment by MaxS3552284** [comment]
jup, just slapping a "if __name__ == "__main__":" in there did the trick, thanks dude

**Comment by suryan-s** [comment]
@AyushExel hey you could close the issue

**Comment by bod9s** [comment]
I have the same issue. Can't run on gpu. Pytorch is recognizing gpu fine, but yolo doesn' work with gpu. Yolo works fine with cpu as well.

**Comment by suryan-s** [comment]
> Why my is GPU Usage Low? yolov8

Have you tried out the solutions mentioned above the thread?

**Comment by glenn-jocher** [comment]
@upda6 greetings! 

If your GPU usage is lower than expected, you may want to check if you are using a version of PyTorch that is built with the latest CUDA and cuDNN libraries. You can also try reducing the batch size or increasing the image input size. 

Another thing to consider is that the GPU usage may vary depending on your specific hardware and data. Some data may be easier or harder to process efficiently on a GPU. 

Please let us know if these suggestions were helpful or not.

**Comment by mcdonasd1212** [comment]
> @upda6 greetings!
> 
> If your GPU usage is lower than expected, you may want to check if you are using a version of PyTorch that is built with the latest CUDA and cuDNN libraries. You can also try reducing the batch size or increasing the image input size.
> 
> Another thing to consider is that the GPU usage may vary depending on your specific hardware and data. Some data may be easier or harder to process efficiently on a GPU.
> 
> Please let us know if these suggestions were helpful or not.

@glenn-jocher is there a way of testing if yoloV8 is using the GPU beside looking at GPU usage?

**Comment by glenn-jocher** [comment]
@mcdonasd1212 certainly, monitoring GPU usage might not always be the most precise way of determining if your application is utilizing the GPU. 
A more direct way is to inspect the device for which your PyTorch tensors are allocated. For instance, you can check if the model weights and input data resides on the GPU. This can be done by calling `.device` on your model or a tensor and checking if it returns 'cuda'. This ensures that the model computation is happening on the GPU.

Also, while running your training script, you can monitor the GPU utilization, memory consumption and temperature using utilities like `nvidia-smi` in your command line terminal. 

Lastly, during your model training or inference, if you see the CUDA out of memory error, it's a sure shot sign that your model is using GPU (though it's exceeding the GPU memory limit). 

Let us know if this answers your question or if you need more assistance!

**Comment by LichiV** [comment]
Hi @glenn-jocher I am currently writing my final thesis and investigating the transformability of YOLOv8 models. As part of the study, I also want to investigate whether more frozen layers enable faster training. However, I have now noticed that the GPU was utilized differently. I did not change the training parameters, only the frozen layers.
I am using an NVIDIA A100. 
One Training (here were no layers frozen)
![image](https://github.com/ultralytics/ultralytics/assets/103516806/467da238-c18a-42d0-b9d5-22910352379e)
Another Training (here were 18 layers frozen)
![image](https://github.com/ultralytics/ultralytics/assets/103516806/72c2422a-3921-4106-a62f-f286a9ae063b)
Since the utilization of the GPU differs, I'm asking myself, if the training time is comparible.

Thank you for your high response rate to problems from the community. Many questions were answered for me by your detailed answers.

**Comment by glenn-jocher** [comment]
@LichiV hi there! When you freeze layers during training, the GPU has fewer computations to perform, which can lead to lower utilization. This is expected behavior as the frozen layers do not require gradient updates, reducing the workload on the GPU. While freezing layers can reduce training time by decreasing the computational burden, the difference in GPU utilization you're observing is a direct result of the reduced number of trainable parameters. It's important to ensure that other training parameters remain constant to make a fair comparison of training times. Keep in mind that the A100 is a powerful GPU, and for smaller models or datasets, it might not be fully utilized. Good luck with your thesis! 🎓🚀

**Comment by teapro1** [comment]
hi. my laptop run rtx2060 but yolov8 not use vga. It only run with CPU

**Comment by glenn-jocher** [comment]
@teapro1 hello! To ensure YOLOv8 utilizes your RTX 2060 GPU, please verify that you have the correct version of PyTorch installed with GPU support (CUDA). You can install it from the PyTorch official website, selecting the appropriate CUDA version that matches your system's CUDA installation. Once installed, YOLOv8 should automatically detect and use your GPU. If `torch.cuda.is_available()` returns `True`, YOLOv8 is ready to run on your GPU. If you continue to face issues, please refer to our documentation for further assistance. 🚀

**Comment by Plingaas** [comment]
Hi! I have a laptop with RTX 4060 GPU. I am pretty confident it is running on the GPU as the GPU memory increases a lot when i run with device = 0 (which is what task manager says my nvidia gpu should be). Changing the batch size also changes how much of the GPU Memory is used. However, the GPU usage stays at 0%, is this normal? If so, why is it that the usage is 0% even though it is being used?
![image](https://github.com/ultralytics/ultralytics/assets/45634179/877138e4-da8d-4151-b23f-06e2221ce4ac)
![image](https://github.com/ultralytics/ultralytics/assets/45634179/c0a52db2-7b72-46b0-b857-c22ba6e1f0a0)
![image](https://github.com/ultralytics/ultralytics/assets/45634179/89fae947-548d-47e2-bc4c-c9d724e0992c)

Thank you!

**Comment by glenn-jocher** [comment]
@Plingaas hello! If your GPU memory usage increases during training with YOLOv8, but the GPU utilization remains at 0%, it could be due to the GPU not being the bottleneck in your training process. This can happen if the CPU or data loading processes are slower, causing the GPU to wait. Ensure your data pipeline is optimized and consider using SSD storage if you're not already. Additionally, GPU utilization metrics can sometimes be misleading depending on the monitoring tool used. If the memory is being allocated, your GPU is indeed being used. 🤖💡

**Comment by DavidFord1** [comment]
**Delay in video inference and not using all the GPU capacity**


Hello

I ran yolov8n on a GIGABYTE GTX 980 G1 Gaming CPU
I tested The video has a delay of 4 seconds during processing, and I noticed that the program does not use the full capacity of the GPU.
According to the program  GPU-Z only uses 30% of the GPU capacity!
This happens to some CPUs and it doesn't use its full capacity! on the laptop and PC
@glenn-jocher Glenn Jocher

**Comment by glenn-jocher** [comment]
Hi there! 👋

It looks like you're experiencing delays and not fully utilizing your GPU with YOLOv8 inference. A few quick suggestions:

- Make sure your dataset and model size align well with your hardware capabilities. Sometimes, adjusting batch sizes can help better utilize the GPU.
- Consider optimizing your data loading process. Slow data transfer between CPU and GPU often causes bottlenecks.
- Try updating your GPU drivers or PyTorch version if they're not up-to-date. Compatibility improvements can significantly affect performance.

Example for data loading optimization:
```python
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

transform = transforms.Compose([transforms.ToTensor()])
dataset = datasets.ImageFolder('path/to/your/data', transform=transform)
loader = DataLoader(dataset, batch_size=64, num_workers=4, pin_memory=True)
```

Remember, GPU utilization can also depend on the nature of the task and the efficiency of the CUDA kernels being executed. Let's know if these tips help or if there's more we can assist with! 🚀

**Comment by TTAyanlade** [comment]
Hey @Plingaas  @LichiV @teapro1. I faced this problem a while back. 

I believe the most probable reason your training is not using GPU if you have one and have done everything as recommended, is that your training images are very large, causing a bottleneck in the dataloading process. 

You can use Pillow to resize all images to (640,640) and then retrain. I am sure you'd see a significant in training speed. 

PS: You can run your Python code in the background(or different tab) and use nvidia-smi to track GPU usage before and after implementing my answer to confirm if you see full utilization of gpu
