### ISSUE TITLE
CUDA is out of memory 

### ISSUE THREAD

**Issue by osamaalschame** [ultralytics/ultralytics#669]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 

I have faced this error(CUDA out of memory) even I predict only one single image.

**Comment by yuliang2** [comment]
What is your GPU model?

**Comment by osamaalschame** [comment]
NVIDIA GeForce RTX 2060, 5924MiB

**Comment by AyushExel** [comment]
Can you provide the code to reproduce? Thanks!

**Comment by AndreiVoian** [comment]
`yolo segment predict model=last_1920.pt source=0 imgsz=1920`

GPU: Nvidia RTX 3060, 12GB

I have the same error, the prediction runs for about 30 seconds then this error occurs :

```
Traceback (most recent call last):
  File "C:\Users\Marcel Department\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Marcel Department\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Marcel Department\Desktop\yolov8\venv\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\Marcel Department\Desktop\yolov8\venv\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 266, in entrypoint
    getattr(model, mode)(**vars(cfg))
  File "C:\Users\Marcel Department\Desktop\yolov8\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Marcel Department\Desktop\yolov8\venv\lib\site-packages\ultralytics\yolo\engine\model.py", line 145, in predict
    return self.predictor(source=source, stream=stream)
  File "C:\Users\Marcel Department\Desktop\yolov8\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Marcel Department\Desktop\yolov8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 114, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "C:\Users\Marcel Department\Desktop\yolov8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 178, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "C:\Users\Marcel Department\Desktop\yolov8\venv\lib\site-packages\ultralytics\yolo\v8\segment\predict.py", line 68, in write_results
    self.annotator.masks(
  File "C:\Users\Marcel Department\Desktop\yolov8\venv\lib\site-packages\ultralytics\yolo\utils\plotting.py", line 118, in masks
    mcs = (masks_color * inv_alph_masks).sum(0) * 2  # mask color summand shape(n,h,w,3)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 254.00 MiB (GPU 0; 12.00 GiB total capacity; 10.69 GiB already allocated; 0 bytes free; 11.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
```

**Comment by AyushExel** [comment]
Your image size will be 1920x1920 which is too high. That is causing OOM error. For reference, the full HD resolution is 1920x1080 and yours is even higher than that

**Comment by AndreiVoian** [comment]
Same error for this:

`yolo segment predict model=last_640_l.pt source=0 imgsz=640 show=True`

Extra info:
            Ultralytics YOLOv8.0.24  Python-3.9.13 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
            YOLOv8l-seg summary (fused): 295 layers, 45917285 parameters, 0 gradients, 220.2 GFLOPs

**Comment by AyushExel** [comment]
CUDA OOM error is related to your hardware and not ultralytics repo. This problem can be solved by using a smaller model or smaller image size or both

**Comment by AndreiVoian** [comment]
With yolov5 or yolov7 I have no problem using the same commands.

**Comment by Laughing-q** [comment]
@AyushExel @AndreiVoian actually I think this is a bug from us.
Because now the command line mode entrypoint is not `segment/predict.py` since we removed hydra, now the entrypoint is using `YOLO.predict()` which means `predict_cli` is not working. 
[https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/cfg/__init__.py#L243](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/cfg/__init__.py#L243)

@glenn-jocher

**Comment by AyushExel** [comment]
@Laughing-q Ohh I see. Then we need to fix this

**Comment by Laughing-q** [comment]
@AndreiVoian We'll fix this soon, but before fixing the issue I suggest you use python interface:
```python
from ultralytics import YOLO
model = YOLO("last_1920.pt")
for result in model.predict(source=0, save=True, stream=True):
    pass
```
which should work as you expected but without cuda OOM. :)

**Comment by AndreiVoian** [comment]
Thanks it works!

**Comment by Laughing-q** [comment]
@AndreiVoian hi the issue has been solved in this PR #723. :)

**Comment by Laughing-q** [comment]
@AndreiVoian closing it. Feel free to reopen it if you have related issues. :)
