### ISSUE TITLE
CUDA OUT OF MEMORY

### ISSUE THREAD

**Issue by zixuxu000** [ultralytics/ultralytics#7030]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I try to train  custome dataset with batchsize 16, In the first epoch, after finish training, Val occupies so much cuda meomory that rasing the problem 'cuda out of memory'. when I set val = False, it works. So I guess that the gradient is preserved during the evaluation. IS there any solution to solve this?

**Comment by glenn-jocher** [comment]
@zixuxu000 hello there! It appears you're encountering a CUDA out-of-memory (OOM) error during validation. This problem generally occurs because your GPU lacks sufficient memory to handle the allocated batch size during training and validation simultaneously. 

A few potential solutions are:
1. **Reduce the batch size**: Lowering the batch size for both training and validation can help fit the process within your GPU's memory.
   
2. **Utilize `--cache`**: If not already doing so, utilize the caching feature, which can reduce memory usage at the expense of initial load time.

3. **Adjust `--workers`**: Decrease the number of workers to reduce memory consumption. 

4. **Stage training and validation**: Consider performing validation after the training epochs have completed if possible.

5. **Gradient checkpointing**: Implement gradient checkpointing to trade compute for memory, although this feature might need manual implementation.

Remember, it's often a balancing act between GPU resources and training efficiency. For detailed guidance, please refer to our [docs on Training](https://docs.ultralytics.com/modes/train) which provides more insights into efficient resource management. 

Hope this helps! Keep us posted on your progress. 😊

**Comment by zixuxu000** [comment]
> @zixuxu000 hello there! It appears you're encountering a CUDA out-of-memory (OOM) error during validation. This problem generally occurs because your GPU lacks sufficient memory to handle the allocated batch size during training and validation simultaneously.
> 
> A few potential solutions are:
> 
> 1. **Reduce the batch size**: Lowering the batch size for both training and validation can help fit the process within your GPU's memory.
> 2. **Utilize `--cache`**: If not already doing so, utilize the caching feature, which can reduce memory usage at the expense of initial load time.
> 3. **Adjust `--workers`**: Decrease the number of workers to reduce memory consumption.
> 4. **Stage training and validation**: Consider performing validation after the training epochs have completed if possible.
> 5. **Gradient checkpointing**: Implement gradient checkpointing to trade compute for memory, although this feature might need manual implementation.
> 
> Remember, it's often a balancing act between GPU resources and training efficiency. For detailed guidance, please refer to our [docs on Training](https://docs.ultralytics.com/modes/train) which provides more insights into efficient resource management.
> 
> Hope this helps! Keep us posted on your progress. 😊

Thamks for your suggestion！But maybe you misunderstand my question.  During traing, It takes  about half of the GPU memory,but when validing, the cuda meomory suddenly increase.  I donnot encounter this problem using **yolov5**.
![image](https://github.com/ultralytics/ultralytics/assets/71247352/9ce0020f-5317-45f6-8343-0201f274066e)

**Comment by glenn-jocher** [comment]
Hello @zixuxu000! CUDA OOM during validation despite ample memory during training suggests that memory isn't being released properly before validation begins. Here's what you can try:

1. **Reduce Validation Batch Size**: Validation typically requires less memory than training; reducing the validation batch size further can prevent OOM errors.

2. **Clear Cache**: Ensure that CUDA memory is cleared after training and before validation starts.

3. **Sequential Execution**: Train and validate sequentially rather than in parallel, to minimize concurrent GPU memory usage.

Remember that differences between YOLOv8 and YOLOv5 could affect memory usage. For more guidance, check out our [docs on Validation](https://docs.ultralytics.com/modes/val). Let us know how these suggestions work out.

**Comment by chandra-ps612** [comment]
I'm facing the similar issue but just after triggering model training.
Please refer these details for your convenience-
**BS:32, image size:416, model:yolov8n (Training from the scratch), workers:8 (Have changed workers from 8 to 4 but still getting the same error with BS:32)
Package details:
Ultralytics == 8.0.232
torch == 2.1.2+cu118             
Training data : 16K
Validation data: 4K**
P.S. Albeit, I'm able to train model with BS:24 along with above settings!
Any suggestions will be helpful!

**Comment by zixuxu000** [comment]
> I'm facing the similar issue but just after triggering model training. Please refer these details for your convenience- **BS:32, image size:416, model:yolov8n (Training from the scratch), workers:8 (Have changed workers from 8 to 4 but still getting the same error with BS:32), with or without Cache:True Package details: Ultralytics == 8.0.232 torch == 2.1.2+cu118** P.S. Albeit, I'm able to train model with BS:24 along with above settings! Any suggestions will be helpful!
Hello, I have found the reason, Do you use multi GPUs when training?
After model training, Validing process is runed on one GPU which results in CUDA out of memory.

**Comment by zixuxu000** [comment]
> I'm facing the similar issue but just after triggering model training. Please refer these details for your convenience- **BS:32, image size:416, model:yolov8n (Training from the scratch), workers:8 (Have changed workers from 8 to 4 but still getting the same error with BS:32), with or without Cache:True Package details: Ultralytics == 8.0.232 torch == 2.1.2+cu118** P.S. Albeit, I'm able to train model with BS:24 along with above settings! Any suggestions will be helpful!

Hello, I have found the reason, Do you use multi GPUs when training?
After model training, Validing process is runed on one GPU which results in CUDA out of memory.

**Comment by chandra-ps612** [comment]
Single GPU for model training

**Comment by chandra-ps612** [comment]
> > I'm facing the similar issue but just after triggering model training. Please refer these details for your convenience- **BS:32, image size:416, model:yolov8n (Training from the scratch), workers:8 (Have changed workers from 8 to 4 but still getting the same error with BS:32), with or without Cache:True Package details: Ultralytics == 8.0.232 torch == 2.1.2+cu118** P.S. Albeit, I'm able to train model with BS:24 along with above settings! Any suggestions will be helpful!
> 
> Hello, I have found the reason, Do you use multi GPUs when training? After model training, Validing process is runed on one GPU which results in CUDA out of memory.

Single GPU

**Comment by glenn-jocher** [comment]
@chandra-ps612 hello! If you're experiencing CUDA OOM errors with a batch size of 32 but not with 24, it's likely that your GPU doesn't have enough memory to handle the larger batch size. Training with a single GPU and a high batch size can be very memory-intensive. Here are a few suggestions:

1. **Further Reduce Batch Size**: Continue to use a batch size that fits within your GPU's memory, like 24, which you've found to work.

2. **Gradual Batch Increase**: Start with a smaller batch size and gradually increase it if possible, monitoring memory usage.

3. **Optimize Memory Usage**: Ensure that you're not running other memory-intensive processes on the GPU during training.

4. **Model Complexity**: Consider using a less complex model variant if reducing the batch size is not an option.

Training with the resources available while maintaining efficiency is key. For more details on managing memory and training configurations, please refer to our [docs on Training](https://docs.ultralytics.com/modes/train). Keep an eye on memory usage, and adjust your settings accordingly. Good luck!

**Comment by nelfy** [comment]
Same issue on 4xRTX4090, the training uses 22G GPU memory, but the validation gives CUDA out of memory.
I've modified the validation code in yolov561 to use CPU, it worked.
But now for yolov8, any better solution?

**Comment by glenn-jocher** [comment]
@nelfy hello! For multi-GPU setups like yours with 4xRTX4090, encountering OOM during validation suggests that the validation might not be distributing across GPUs as expected. Here are a few concise suggestions:

1. **Reduce Validation Batch Size**: Try lowering the batch size specifically for validation to fit within the memory constraints.

2. **Distribute Validation**: Ensure that validation is set to run on all GPUs, similar to training, to utilize the full memory capacity.

3. **Sequential Validation**: If parallel validation is problematic, consider validating sequentially on each GPU.

4. **CPU Offloading**: As a last resort, offloading to CPU is a valid workaround, although it's slower.

For more details on multi-GPU training and validation, please refer to our [docs on Training](https://docs.ultralytics.com/modes/train). Adjusting these settings should help you utilize your GPUs more effectively during validation.

**Comment by nelfy** [comment]
> @nelfy hello! For multi-GPU setups like yours with 4xRTX4090, encountering OOM during validation suggests that the validation might not be distributing across GPUs as expected. Here are a few concise suggestions:
> 
> 1. **Reduce Validation Batch Size**: Try lowering the batch size specifically for validation to fit within the memory constraints.
> 2. **Distribute Validation**: Ensure that validation is set to run on all GPUs, similar to training, to utilize the full memory capacity.
> 3. **Sequential Validation**: If parallel validation is problematic, consider validating sequentially on each GPU.
> 4. **CPU Offloading**: As a last resort, offloading to CPU is a valid workaround, although it's slower.
> 
> For more details on multi-GPU training and validation, please refer to our [docs on Training](https://docs.ultralytics.com/modes/train). Adjusting these settings should help you utilize your GPUs more effectively during validation.

Thank you for your reply. I reviewed the 'Training' documentation, but I couldn't find a direct answer on how to implement what you mentioned, other than modifying the source code. 

1. I am using a batch size of 1024; it trains successfully in the first epoch, but fails due to memory issues during validation. 
When I reduced the batch size to 512, it utilized 12GB of memory for training and about 17GB for validation, and then proceeded to the second epoch. At that point, I observed that the memory usage of the first GPU rose to 24GB, almost reaching its full capacity. Why isn't the memory being released after validation?
4. Regarding CPU offloading, it appears that the only option is to modify 'engine/validator.py' by setting 'self.device' to 'cpu'. I haven’t tested this yet.

**Comment by glenn-jocher** [comment]
@nelfy, it seems like the memory isn't being released after validation due to the way PyTorch handles caching. Here's a concise action plan:

1. **Manually Clear Cache**: After validation, manually clear the CUDA cache using PyTorch commands to free up memory before the next epoch.
2. **Review Source Code**: Check the validation loop for any tensors that might not be getting released or operations accumulating memory.
3. **CPU Offloading**: Modifying `engine/validator.py` to set `self.device` to `cpu` is indeed a way to offload to CPU, but it's a workaround and may slow down the process.

For the memory not being released, it's often related to PyTorch's caching mechanism, which is designed to speed up memory allocation. However, it can lead to situations where memory isn't freed promptly. If you're comfortable with it, modifying the source code to ensure tensors are deleted and the cache is cleared after validation can help.

For further assistance, please refer to our [docs on Validation](https://docs.ultralytics.com/modes/val). If the issue persists, consider opening an issue on the GitHub repository for more specific guidance.

**Comment by Rasoul77** [comment]
I have the same problem and found out that in the Ultralytics implementation, they keep the last training batch data into GPU memory and then try to allocate the same amount of GPU memory for the validation batch! It has a very simple solution, just remove/deallocate the last training batch from the GPU memory.

**Comment by glenn-jocher** [comment]
Thank you for your insight. To address this, you can manually clear the CUDA cache after training and before validation using `torch.cuda.empty_cache()`. This should help free up GPU memory.

**Comment by Rasoul77** [comment]
@glenn-jocher : Thanks for your quick reply! :+1: 
I believe that this simple solution has to be implemented officially in the Ultralytics training code and not to be done by the user.

**Comment by glenn-jocher** [comment]
@Rasoul77 thank you for your feedback. We appreciate your suggestion and will consider it for future updates to improve the training process.

**Comment by Petros626** [comment]
@wmuron

**Comment by SudhanshuBlaze** [comment]
I am getting the same error, I am on python 3.12.1:

`OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 23.67 GiB of which 1.12 MiB is free. Process 4009449 has 22.37 GiB memory in use. Including non-PyTorch memory, this process has 1.29 GiB memory in use. Of the allocated memory 977.30 MiB is allocated by PyTorch, and 10.70 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
`

I tried these solutions, I also tried it with different smaller batch sizes, but I keep getting the error:

```python
import torch
torch.cuda.empty_cache()
torch.cuda.ipc_collect()
!export CUDA_VISIBLE_DEVICES=1
!export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
!echo $CUDA_VISIBLE_DEVICES
```


Source Code:
```python

import cv2
from ultralytics import YOLO

# Load the YOLO11 model
model = YOLO("models/best_v7_yolov9e_visdrone_hi_res.pt")

# Open the video file
video_path = "resources/DJI_0634.MP4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    success, frame = cap.read()

    if success:
        # Run YOLO11 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True, show=True, classes=[0,1], batch=-1, device=1)

        # Visualize the results on the frame w)ith smaller font size
        annotated_frame = results[0].plot(line_width=2, font_size=11, conf=False)

        # Display the annotated frame
        cv2.imshow("YOLO11 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
```

**Dependencies:**
ultralytics==8.3.78
opencv-python==4.9.0.80
torch==2.3.0
torchvision==0.18
shapely==2.0.1

Could it be because of version mismatch? I also tried it with latest version of torch which is 2.6.0 but still the same issue.

**Comment by Petros626** [comment]
try to split the process on both cards `device=[0,1]`. On the other hand all the mentioned tips worked for me.

**Comment by glenn-jocher** [comment]
@SudhanshuBlaze to resolve device selection, set `CUDA_VISIBLE_DEVICES=1` before executing your script. This forces GPU 1 to appear as `device=0` to PyTorch. For Ultralytics YOLO, you can then use `device=0` in your code. This approach avoids conflicts with the occupied GPU 0 while maintaining proper device allocation. For details, see the [select_device documentation](https://docs.ultralytics.com/reference/utils/torch_utils/#ultralytics.utils.torch_utils.select_device).

**Comment by tonyreina** [comment]
I'm using `model.train` and everything works great on the GPU for the training section. However, when it then tries to do a validation at the end of every training epoch, then about halfway through the validation it gives CUDA OOM. Once the next training epoch starts, it goes right back to using the GPU. 

This behavior doesn't make sense to me. Why would the training run fit into memory, but the validation run won't? Again, this is just using the `model.train` so training and validation are combined.

**Comment by tonyreina** [comment]
`stream_buffer=True`

I set this in `model.train` and it seems to work now without going OOM.

**Comment by Petros626** [comment]
Set Amp and half False,if Fp16 precision is not required.

**Comment by glenn-jocher** [comment]
@tonyreina great find! Setting `stream_buffer=True` helps reduce memory usage during validation by streaming data more efficiently. This parameter enables streaming validation which can significantly reduce memory consumption. For others experiencing similar issues, this is a valuable configuration option to try alongside the other memory management techniques discussed in this thread.
