### ISSUE TITLE
OBB huge memory spike on Validation only - CUDA OOM 

### ISSUE THREAD

**Issue by kikefdezl** [ultralytics/ultralytics#7636]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I am trying to train `yolov8n-obb` on a custom dataset. It all goes smoothly until validation, where there's a huge memory usage spike and a CUDA memory error is raised.

Here's a screenshot that shows the GPU memory usage spike on validation:
![Screenshot_20240117_105934](https://github.com/ultralytics/ultralytics/assets/75074147/fee27f2f-e497-4af5-ae77-1a5c9e291eaa)

Is there a way to force CPU for validation? I think this would solve my issue for the time being.

### Environment

```bash
Ultralytics YOLOv8.1.2 🚀 Python-3.11.6 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce RTX 3070, 7971MiB)
Setup complete ✅ (16 CPUs, 15.4 GB RAM, 1065.7/1832.2 GB disk)

OS                  Linux-6.7.0-arch3-1-x86_64-with-glibc2.38
Environment         Linux
Python              3.11.6
Install             git
RAM                 15.37 GB
CPU                 12th Gen Intel Core(TM) i5-12600K
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.26.2>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.2>=1.8.0
torchvision         ✅ 0.16.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
```

### Minimal Reproducible Example

```python
from ultralytics import YOLO

model = YOLO('yolov8n-obb.yaml')
results = model.train(data="custom_dataset.yaml", epochs=25, imgsz=640, batch=1)
```

### Additional

About the dataset (`custom_dataset.yaml`):
The dataset does contain a large amount of objects per image in some cases (+1k oriented bboxes), so I'm guessing this is the root of the issue, happening when calculating `nms_rotated()`. Unfortunately I cannot share the dataset, but you could debug by adding 1-2k objects on a couple of images of a custom dataset. 

### Are you willing to submit a PR?

- [X] Yes I'm willing to submit a PR if I get pointed in the right direction.

**Comment by glenn-jocher** [comment]
@kikefdezl hello! Thanks for the detailed report. It seems you're encountering an out-of-memory (OOM) issue during validation with `yolov8n-obb`. The large number of objects per image could indeed be contributing to the spike in GPU memory usage.

Currently, YOLOv8 does not support CPU-only validation as a built-in feature. However, you can reduce GPU memory usage by lowering the batch size during validation or by reducing the number of workers. Additionally, you might consider validating on a subset of your dataset to see if the issue persists.

If you're willing to submit a PR, a potential direction could be to implement a CPU fallback mechanism for validation when CUDA OOM errors are detected. This would involve catching CUDA OOM exceptions during validation and retrying the validation step on the CPU.

For further guidance, please refer to the documentation on the Train mode and feel free to continue the discussion in the issues section if you need more specific pointers. Your contributions are much appreciated by the community! 🚀

**Comment by kikefdezl** [comment]
Sadly I don't think i'll have the time to try to solve this in the near future.

**Comment by glenn-jocher** [comment]
@kikefdezl no worries at all! If you find the time later on or if someone else in the community can pick this up, that would be great. In the meantime, consider trying the workarounds I mentioned earlier, and keep an eye on the repo for any updates that might address this issue. Your input is valuable, and we appreciate you bringing this to our attention. Good luck! 🍀

**Comment by bobwen-dev** [comment]
I'm also having this issue when running a training task.

CLI:
```sh
yolo obb train model=yolov9e-obb.yaml data=~/dataset/dataset.yaml imgsz=1024 batch=1 max_det=192 epochs=400 degrees=180 translate=0 fliplr=0
```

Bug:
```
Starting training for 400 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/400      9.55G      3.818      5.531      4.164         25       1024: 100%|██████████| 291/291 [01:52<00:00,  2.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  11%|█         | 31/291 [00:04<00:37,  6.95it/s]
Traceback (most recent call last):
  File "/usr/local/share/virtualenvs/yolo/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 830, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 815, in train
    self.trainer.train()
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 434, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 586, in validate
    metrics = self.validator(self)
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 185, in __call__
    preds = self.postprocess(preds)
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/models/yolo/obb/val.py", line 41, in postprocess
    return ops.non_max_suppression(
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/utils/ops.py", line 289, in non_max_suppression
    i = nms_rotated(boxes, scores, iou_thres)
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/utils/ops.py", line 158, in nms_rotated
    ious = batch_probiou(boxes, boxes).triu_(diagonal=1)
  File "/usr/local/share/virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/utils/metrics.py", line 260, in batch_probiou
    ((a1 + a2) * (y1 - y2).pow(2) + (b1 + b2) * (x1 - x2).pow(2)) / ((a1 + a2) * (b1 + b2) - (c1 + c2).pow(2) + eps)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.35 GiB. GPU 0 has a total capacity of 10.57 GiB of which 2.10 GiB is free. Including non-PyTorch memory, this process has 8.46 GiB memory in use. Of the allocated memory 7.75 GiB is allocated by PyTorch, and 435.37 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

Environment:
```
Ultralytics YOLOv8.2.90 🚀 Python-3.10.12 torch-2.2.2+cu121 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 10826MiB)
Setup complete ✅ (12 CPUs, 31.3 GB RAM, 55.2/97.9 GB disk)

OS                  Linux-5.15.0-112-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 31.28 GB
CPU                 Intel Core(TM) i7-8700K 3.70GHz
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.8.4>=3.3.0
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.2.2>=1.8.0
torchvision         ✅ 0.17.2>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
torch               ✅ 2.2.2!=2.4.0,>=1.8.0; sys_platform == "win32"
```

I have the feeling that the non_max_suppression function is running out of control -- too many boxes causing CUDA to overflow, but I'm not familiar with the code for this and don't know how to fix it.

**Comment by glenn-jocher** [comment]
It looks like you've identified the issue with the `non_max_suppression` function causing a CUDA out-of-memory error due to too many boxes. Your modification to limit `max_nms` seems to be a practical workaround. For a more permanent solution, consider adjusting the batch size or image size to reduce memory usage. If you need further assistance, feel free to continue the discussion here.

**Comment by paulivii** [comment]
@bobwen-dev, thanks for your help pointing out that problem source. I recently replaced ultralytics nms implementation with an own implementation that does not require torch/torchvision similarly to [this implementation](https://github.com/Harly-1506/Faster-Inference-yolov8/blob/main/utils/ops_faster.py)

I found that this also reduces the memory spikes. Keep in mind that it does not leverage torch and hence is not that fast as the original implementation.

**Comment by tildekarthik** [comment]
The above patch worked for me too but the function has moved to ultralytics/utils/ops.py (Changed 30000 to 1920 as described above)
def non_max_suppression(
    prediction,
    conf_thres=0.25,
    iou_thres=0.45,
    classes=None,
    agnostic=False,
    multi_label=False,
    labels=(),
    max_det=300,
    nc=0,  # number of classes (optional)
    max_time_img=0.05,
    max_nms=1920,
    max_wh=7680,
    in_place=True,
    rotated=False,
    end2end=False,
):

**Comment by glenn-jocher** [comment]
Thanks for sharing your solution! Adjusting the `max_nms` parameter in `ops.non_max_suppression()` can indeed help mitigate CUDA OOM issues during validation by limiting the maximum number of boxes considered for NMS. For those facing similar memory spikes, this parameter is documented in our [ops.non_max_suppression reference](https://docs.ultralytics.com/reference/utils/ops/#ultralytics.utils.ops.non_max_suppression). If you'd like to contribute this improvement via PR, we'd welcome it! 🛠️
