### ISSUE TITLE
RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by xiaobaixuejava** [ultralytics/ultralytics#7716]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

File "ultralytics\engine\model.py", line 257, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "ultralytics\engine\predictor.py", line 198, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "ultralytics\engine\predictor.py", line 287, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "ultralytics\engine\predictor.py", line 168, in write_results
    log_string += result.verbose()
  File "ultralytics\engine\results.py", line 270, in verbose
    log_string += f"{', '.join(f'{self.names[j]} {probs.data[j]:.2f}' for j in probs.top5)}, "
  File "ultralytics\engine\results.py", line 561, in top5
    return (-self.data).argsort(0)[:5].tolist()  # this way works with both torch and numpy.
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

打包的程序在进行预测的时候偶尔会爆出这个错误，请问一下这个是啥原因

### Environment

python 3.8   ultralytics  8.0.230

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@xiaobaixuejava hello! The "unspecified launch failure" CUDA error you're encountering is often related to issues with the GPU, such as an out-of-memory condition, an unsupported operation, or a hardware malfunction. Here are a few steps you can take to troubleshoot the problem:

1. **Check GPU Memory**: Ensure that your GPU has enough memory available to perform the prediction task. You can monitor GPU usage with tools like `nvidia-smi`.

2. **Update Drivers and PyTorch**: Make sure that your NVIDIA drivers and PyTorch installation are up to date, as compatibility issues might cause such errors.

3. **CUDA_LAUNCH_BLOCKING**: Temporarily set the environment variable `CUDA_LAUNCH_BLOCKING=1` to get a more precise error location. This will slow down your code but can help pinpoint the issue.

4. **Hardware Check**: If the error persists, there might be a hardware issue with your GPU. Try running the code on a different machine if possible.

5. **Review Code**: Ensure that the input data is correctly formatted and that there are no issues with the model or the data pipeline.

If none of these steps resolve the issue, please consider providing more details about your environment and a minimal reproducible example if possible. This will help us better understand and address the problem. Thanks for using YOLOv8, and we appreciate your contribution to the community! 🚀

**Comment by xiaobaixuejava** [comment]
Ok, thank you for your reply

**Comment by glenn-jocher** [comment]
@xiaobaixuejava you're welcome! If you encounter any further issues or have more questions, feel free to reach out. Happy coding! 🌟

**Comment by luchinoprince** [comment]
Got the same problem after interrupting a code from a notebook,  and then trying to save the model output. Then I got an ERR when typing into terminal `nvidia-smi`, while about a minute later `nvidia-smi` would just hang. Any idea? The code was going without any problem, any idea of the potential cause? Should I be concerned if I reboot the system?

**Comment by glenn-jocher** [comment]
@luchinoprince it sounds like your GPU may have entered an unstable state, possibly due to the interrupted process. Here's what you can do:

1. **Reboot**: Start by rebooting your system to reset the GPU state.

2. **Monitor**: After reboot, use `nvidia-smi` to check if the GPU is recognized and monitor its status as you rerun your code.

3. **Investigate**: If the problem recurs, investigate any patterns in the code execution that could lead to the issue, such as memory leaks or excessive resource allocation.

Rebooting is a common first step in resolving such issues and is unlikely to cause harm. If the problem persists after a reboot, further investigation will be necessary.

**Comment by luchinoprince** [comment]
Dear @glenn-jocher thanks for the information, I rebooted it(as it usually the best solution) but then did not want to ruin my night so just decided to see the outcome tomorrow. 

I doubt it could be the code, as it was a very light code; I have an RTX 3090, and memory consumption was bout 6GBs/24Gbs during the code. Again, the code was working super well, I just had to interrupt it because I was leaving and was running on ssh notebook, so it would have died anyhow. 

Do you think I should be concerned with the behaviour? Especially, it is a common practice for me to run GPU code in notebook, and if something is going wrong I tend to kill them from within the VsCode cell; To your knowledge(maybe it is not a well posed questions), is such a behaviour dangerous in any way? 

Could you give me a little insight on what does it mean for the GPU to be in unstable state? I want to try to make this situation as much as possible a learning experience other than (hopefully) a big scare.

**Comment by glenn-jocher** [comment]
@luchinoprince, it's not uncommon for GPUs to become unresponsive after abrupt interruptions, especially during intensive tasks. Given the RTX 3090's robust memory, your 6GB usage shouldn't be a concern. Interrupting processes in a notebook environment is generally safe and shouldn't harm your GPU. An "unstable state" typically means the GPU is stuck in an operation or waiting for a response that's not coming, which can happen after forced stops. Rebooting usually clears this state. If this behavior becomes frequent without clear cause, it might be worth investigating further, but occasional occurrences are often part of the normal operation. Keep an eye on patterns, and if issues persist, consider a deeper dive into system logs or hardware diagnostics. Enjoy your learning journey! 🌟

**Comment by AbdoTW** [comment]
If I restart my machine, the problem is solved, but if i suspend my mahcine the error backed again !

i think this problem occurs with many  AMD processor users, while i was using my ubuntu machine and faced the same error (after suspended my machine) i just swtiched to windows os (i have both operating systems installed as dual boot) and then switched back to ubuntu, the problem was solved

Before switching from Linux to Windows:
If you run the command "sudo prime-select query" and the output is intel, you need to switch it to nvidia by using "sudo prime-select nvidia", and then switch to Windows. 
you can also using "sudo prime-select on-demand"

**Comment by glenn-jocher** [comment]
@AbdoTW thanks for sharing this valuable insight! Your observation about suspend/resume cycles causing the CUDA error recurrence is particularly helpful. The `prime-select` commands you mentioned are indeed useful for systems with hybrid graphics (typically Intel integrated + NVIDIA discrete GPU setups). For others experiencing similar issues, setting `sudo prime-select nvidia` or `sudo prime-select on-demand` before system suspend might help maintain proper GPU state. Your dual-boot switching workaround, while unconventional, demonstrates how a full hardware reset can resolve persistent GPU state issues when a simple reboot isn't sufficient.

**Comment by AbdoTW** [comment]
@glenn-jocher  Thanks for your reply. Unfortunately, the error has returned — you can find the full error message below.

I'm using YOLOv12, and when I run nvidia-smi, it works fine — the GPU is detected and appears to be functioning properly. However, the issue persists, and I’m looking for a way to fix it without rebooting my device.

Any ideas or suggestions would be greatly appreciated!


RuntimeError                              Traceback (most recent call last)
Cell In[3], [line 277](vscode-notebook-cell:?execution_count=3&line=277)
    274 frame_count += 1
    276 # Run YOLO inference on the frame
--> [277](vscode-notebook-cell:?execution_count=3&line=277) results = model(frame, conf=0.25)
    279 # Create a copy of the original frame for custom annotation
    280 annotated_frame = frame.copy()

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/ultralytics/engine/model.py:185, in Model.__call__(self, source, stream, **kwargs)
    156 def __call__(
    157     self,
    158     source: Union[str, Path, int, Image.Image, list, tuple, np.ndarray, torch.Tensor] = None,
    159     stream: bool = False,
    160     **kwargs: Any,
    161 ) -> list:
    162     """
    163     Alias for the predict method, enabling the model instance to be callable for predictions.
    164 
   (...)
    183         ...     print(f"Detected {len(r)} objects in image")
    184     """
--> [185](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/ultralytics/engine/model.py:185)     return self.predict(source, stream, **kwargs)

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/ultralytics/engine/model.py:548, in Model.predict(self, source, stream, predictor, **kwargs)
    546 if not self.predictor:
    547     self.predictor = (predictor or self._smart_load("predictor"))(overrides=args, _callbacks=self.callbacks)
--> [548](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/ultralytics/engine/model.py:548)     self.predictor.setup_model(model=self.model, verbose=is_cli)
    549 else:  # only update args if predictor is already setup
    550     self.predictor.args = get_cfg(self.predictor.args, args)

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/ultralytics/engine/predictor.py:391, in BasePredictor.setup_model(self, model, verbose)
    383 def setup_model(self, model, verbose: bool = True):
    384     """
    385     Initialize YOLO model with given parameters and set it to evaluation mode.
    386 
   (...)
    389         verbose (bool): Whether to print verbose output.
    390     """
--> [391](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/ultralytics/engine/predictor.py:391)     self.model = AutoBackend(
    392         weights=model or self.args.model,
    393         device=select_device(self.args.device, verbose=verbose),
    394         dnn=self.args.dnn,
    395         data=self.args.data,
    396         fp16=self.args.half,
    397         batch=self.args.batch,
    398         fuse=True,
    399         verbose=verbose,
    400     )
    402     self.device = self.model.device  # update device
    403     self.args.half = self.model.fp16  # update half

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/utils/_contextlib.py:116, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    113 @functools.wraps(func)
    114 def decorate_context(*args, **kwargs):
    115     with ctx_factory():
--> [116](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/utils/_contextlib.py:116)         return func(*args, **kwargs)

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/ultralytics/nn/autobackend.py:199, in AutoBackend.__init__(self, weights, device, dnn, data, fp16, batch, fuse, verbose)
    197 # In-memory PyTorch model
    198 if nn_module:
--> [199](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/ultralytics/nn/autobackend.py:199)     model = weights.to(device)
    200     if fuse:
    201         model = model.fuse(verbose=verbose)

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:1340, in Module.to(self, *args, **kwargs)
   1337         else:
   1338             raise
-> [1340](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:1340) return self._apply(convert)

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/ultralytics/nn/tasks.py:292, in BaseModel._apply(self, fn)
    282 def _apply(self, fn):
    283     """
    284     Apply a function to all tensors in the model that are not parameters or registered buffers.
    285 
   (...)
    290         (BaseModel): An updated BaseModel object.
    291     """
--> [292](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/ultralytics/nn/tasks.py:292)     self = super()._apply(fn)
    293     m = self.model[-1]  # Detect()
    294     if isinstance(
    295         m, Detect
    296     ):  # includes all Detect subclasses like Segment, Pose, OBB, WorldDetect, YOLOEDetect, YOLOESegment

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:900, in Module._apply(self, fn, recurse)
    898 if recurse:
    899     for module in self.children():
--> [900](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:900)         module._apply(fn)
    902 def compute_should_use_set_data(tensor, tensor_applied):
    903     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    904         # If the new tensor has compatible tensor type as the existing tensor,
    905         # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    910         # global flag to let the user control whether they want the future
    911         # behavior of overwriting the existing tensor or not.

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:900, in Module._apply(self, fn, recurse)
    898 if recurse:
    899     for module in self.children():
--> [900](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:900)         module._apply(fn)
    902 def compute_should_use_set_data(tensor, tensor_applied):
    903     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    904         # If the new tensor has compatible tensor type as the existing tensor,
    905         # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    910         # global flag to let the user control whether they want the future
    911         # behavior of overwriting the existing tensor or not.

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:900, in Module._apply(self, fn, recurse)
    898 if recurse:
    899     for module in self.children():
--> [900](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:900)         module._apply(fn)
    902 def compute_should_use_set_data(tensor, tensor_applied):
    903     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    904         # If the new tensor has compatible tensor type as the existing tensor,
    905         # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    910         # global flag to let the user control whether they want the future
    911         # behavior of overwriting the existing tensor or not.

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:927, in Module._apply(self, fn, recurse)
    923 # Tensors stored in modules are graph leaves, and we don't want to
    924 # track autograd history of `param_applied`, so we have to use
    925 # `with torch.no_grad():`
    926 with torch.no_grad():
--> [927](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:927)     param_applied = fn(param)
    928 p_should_use_set_data = compute_should_use_set_data(param, param_applied)
    930 # subclasses may have multiple child tensors so we need to use swap_tensors

File ~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:1326, in Module.to.<locals>.convert(t)
   1319     if convert_to_format is not None and t.dim() in (4, 5):
   1320         return t.to(
   1321             device,
   1322             dtype if t.is_floating_point() or t.is_complex() else None,
   1323             non_blocking,
   1324             memory_format=convert_to_format,
   1325         )
-> [1326](https://file+.vscode-resource.vscode-cdn.net/home/tawfik/git/computer_vision_projects/pizza_violation_eagle_vision/~/miniconda3/envs/computer_vision_projects/lib/python3.10/site-packages/torch/nn/modules/module.py:1326)     return t.to(
   1327         device,
   1328         dtype if t.is_floating_point() or t.is_complex() else None,
   1329         non_blocking,
   1330     )
   1331 except NotImplementedError as e:
   1332     if str(e) == "Cannot copy out of meta tensor; no data!":

RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by AbdoTW** [comment]
@glenn-jocher these commands also solve my problem instead of rebooting, so can you know the source of the problem and how can i solve it ?
the error happen if i suspend my device and try to run the script , but if i repoot my device the error solved !

sudo systemctl restart nvidia-persistenced.service
sudo rmmod nvidia_uvm
sudo modprobe nvidia_uvm
sudo systemctl restart gdm

**Comment by glenn-jocher** [comment]
@AbdoTW excellent detective work! Those commands are much more targeted than a full reboot. Here's what they accomplish:

- `sudo systemctl restart nvidia-persistenced.service` - restarts the NVIDIA persistence daemon
- `sudo rmmod nvidia_uvm` / `sudo modprobe nvidia_uvm` - reloads the Unified Virtual Memory module
- `sudo systemctl restart gdm` - restarts the display manager

This suggests the issue stems from the NVIDIA driver's state becoming corrupted during suspend/resume cycles, particularly affecting GPU memory management and display coordination. Your solution effectively resets the NVIDIA driver stack without requiring a full system restart, which is much more efficient. Consider creating a script with these commands for quick recovery when this happens again.
