### ISSUE TITLE
RuntimeError: An attempt has been made to start a new process before ... 

### ISSUE THREAD

**Issue by junyongyou** [ultralytics/ultralytics#8843]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried to run the example script in the tutorial as following:

`from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
results = model.train(data='coco128.yaml', epochs=10, imgsz=640, device=[0, 1])
# model.train(data="coco128.yaml", epochs=10, imgsz=640)  # train the model
metrics = model.val()  # evaluate model performance on the validation set
results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image
print(results) # export the model to ONNX format`

If I train the model on a single GPU, it will immediately stucks. If training on multiple GPUs, it will train for a while, and then stucks. I am running it on Windows10. It looks like to be a multi-threading issue. Any helps are highly appreciated.

The RuntimeError as following:

Results saved to ..\runs\detect\train6
Ultralytics YOLOv8.1.8 🚀 Python-3.10.5 torch-2.1.2+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
                                                          CUDA:1 (NVIDIA GeForce RTX 3090, 24576MiB)
Model summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
val: Scanning \coco128\labels\train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "\object_detection\yolo_v8.py", line 10, in <module>
    metrics = model.val()  # evaluate model performance on the validation set
  File "\venv\lib\site-packages\ultralytics\engine\model.py", line 470, in val
    validator(model=self.model)
  File "\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "\venv\lib\site-packages\ultralytics\engine\validator.py", line 152, in __call__
    self.dataloader = self.dataloader or self.get_dataloader(self.data.get(self.args.split), self.args.batch)
  File "\venv\lib\site-packages\ultralytics\models\yolo\detect\val.py", line 226, in get_dataloader
    return build_dataloader(dataset, batch_size, self.args.workers, shuffle=False, rank=-1)  # return dataloader
  File "\venv\lib\site-packages\ultralytics\data\build.py", line 114, in build_dataloader
    return InfiniteDataLoader(
  File "\venv\lib\site-packages\ultralytics\data\build.py", line 40, in __init__
    self.iterator = super().__iter__()
  File "\venv\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "\venv\lib\site-packages\torch\utils\data\dataloader.py", line 386, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1039, in __init__
    w.start()
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by glenn-jocher** [comment]
@junyongyou hey there! 👋 It looks like you're encountering a multiprocessing issue common on Windows. When using multiprocessing in Python scripts on Windows, you need to protect the entry point of your script to avoid spawning new processes before the current process is fully initialized.

Try wrapping your script's main logic with an `if __name__ == '__main__':` guard like this:

```python
from ultralytics import YOLO

if __name__ == '__main__':
    # Load a model
    model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

    # Use the model
    results = model.train(data='coco128.yaml', epochs=10, imgsz=640, device=[0, 1])
    metrics = model.val()  # evaluate model performance on the validation set
    results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image
    print(results)
```

This should resolve the RuntimeError you're experiencing. Let us know if you need further assistance! 😊

**Comment by junyongyou** [comment]
> @junyongyou hey there! 👋 It looks like you're encountering a multiprocessing issue common on Windows. When using multiprocessing in Python scripts on Windows, you need to protect the entry point of your script to avoid spawning new processes before the current process is fully initialized.
> 
> Try wrapping your script's main logic with an `if __name__ == '__main__':` guard like this:
> 
> ```python
> from ultralytics import YOLO
> 
> if __name__ == '__main__':
>     # Load a model
>     model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
> 
>     # Use the model
>     results = model.train(data='coco128.yaml', epochs=10, imgsz=640, device=[0, 1])
>     metrics = model.val()  # evaluate model performance on the validation set
>     results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image
>     print(results)
> ```
> 
> This should resolve the RuntimeError you're experiencing. Let us know if you need further assistance! 😊

Great, I just came across the same solution (https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing). I believe this solves the problem. Thanks a lot.

**Comment by glenn-jocher** [comment]
@junyongyou You're welcome! 😄 I'm glad to hear that solved the issue. If you have any more questions or run into other challenges, feel free to reach out. Happy coding with YOLOv8! 🚀
