### ISSUE TITLE
getting error when added background images with empty text files

### ISSUE THREAD

**Issue by mnoroozii** [ultralytics/ultralytics#9560]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

 runs/detect/train13/labels.jpg... Image sizes 640 train, 640 valUsing 0 dataloader workersLogging results to runs/detect/train13Starting training for 500 epochs...
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size      1/500      4.43G      1.007      1.264      1.149         60        640: 1                 Class     Images  Instances      Box(P          R      mAP50  m../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [425,0,0], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [425,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [33,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [34,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [36,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [37,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [38,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [40,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [41,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [42,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [43,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [44,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [45,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [46,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [47,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [48,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [49,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [50,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [52,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [53,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [54,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [56,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [57,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [58,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [60,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [61,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [65,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [66,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [72,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [73,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [74,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [76,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [77,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [78,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [80,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [81,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [82,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [84,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [85,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [86,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [88,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [89,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [90,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [239,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [65,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [66,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [72,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [73,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [74,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [76,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [77,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [78,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [80,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [81,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [82,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [84,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [85,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [86,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [88,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [89,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [90,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [789,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [229,0,0], thread: [58,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [229,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [229,0,0], thread: [60,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [229,0,0], thread: [61,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [229,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [229,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [65,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [66,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [72,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [73,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [74,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [76,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [77,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [78,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [80,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [81,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [82,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [84,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [85,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [86,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [88,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [89,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [90,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [799,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                 Class     Images  Instances      Box(P          R      mAP50  mTraceback (most recent call last):  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/engine/validator.py", line 163, in __call__    self.loss += trainer.criterion(preds, batch)[1]  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/v8/detect/train.py", line 77, in criterion    return self.compute_loss(preds, batch)  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/v8/detect/train.py", line 189, in __call__    _, target_bboxes, target_scores, fg_mask, _ = self.assigner(  File "/usr/local/venv-39/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl    return forward_call(*args, **kwargs)  File "/usr/local/venv-39/lib64/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context    return func(*args, **kwargs)  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/utils/tal.py", line 111, in forward    mask_pos, align_metric, overlaps = self.get_pos_mask(pd_scores, pd_bboxes, gt_labels, gt_bboxes, anc_points,  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/utils/tal.py", line 132, in get_pos_mask    align_metric, overlaps = self.get_box_metrics(pd_scores, pd_bboxes, gt_labels, gt_bboxes, mask_in_gts * mask_gt)  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/utils/tal.py", line 151, in get_box_metrics    bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*wRuntimeError: CUDA error: device-side assert triggeredCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.For debugging consider passing CUDA_LAUNCH_BLOCKING=1.Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):  File "/usr/local/venv-39/bin/yolo", line 8, in <module>    sys.exit(entrypoint())  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/cfg/__init__.py", line 391, in entrypoint    getattr(model, mode)(**overrides)  # default args from model  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 370, in train    self.trainer.train()  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 191, in train    self._do_train(world_size)  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 362, in _do_train    self.metrics, self.fitness = self.validate()  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 462, in validate    metrics = self.validator(self)  File "/usr/local/venv-39/lib64/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context    return func(*args, **kwargs)  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/engine/validator.py", line 163, in __call__    self.loss += trainer.criterion(preds, batch)[1]  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/utils/ops.py", line 44, in __exit__    self.dt = self.time() - self.start  # delta-time  File "/usr/local/venv-39/lib64/python3.9/site-packages/ultralytics/yolo/utils/ops.py", line 52, in time    torch.cuda.synchronize()  File "/usr/local/venv-39/lib64/python3.9/site-packages/torch/cuda/__init__.py", line 688, in synchronize    return torch._C._cuda_synchronize()RuntimeError: CUDA error: device-side assert triggeredCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.For debugging consider passing CUDA_LAUNCH_BLOCKING=1.Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mnoroozii hi there! 👋 It looks like you're encountering a device-side assert triggered error, which often occurs due to incorrect dataset annotations or mismatch in data dimensions. Since you've mentioned adding background images with empty text files, please ensure each of those empty text files has a newline character `\n` at the end. Sometimes, the absence of a newline can lead to unexpected behavior.

Quick tip: You can batch modify files using a simple command line script. Here's an example command to add a newline to all `.txt` files in a directory:

```bash
for f in *.txt; do echo "" >> "$f"; done
```

Please give this a try and let us know if it resolves the issue! If the problem persists, consider running your training with `CUDA_LAUNCH_BLOCKING=1` set in your environment to get a more accurate pinpoint of the error for further troubleshooting. 🛠️

Hope this helps!

**Comment by Terry-50000** [comment]
@glenn-jocher Hi, there.
I made empty text labels and also add a "/n" to all text files, but still get errors.
--------------------------------------------------------------------------
Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100       7.6G          0     0.7594          0          0        640: 100%|██████████| 9/9 [00:02<00:0
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1  
                   all          8          0          0          0          0          0
WARNING  no labels found in detect set, can not compute metrics without labels

self.nt_per_class = np.bincount(stats[-1].astype(int), minlength=self.nc)  # number of targets per class    
IndexError: list index out of range
----------------------------------------------------------------------
Could you pls help me with this?

**Comment by mnoroozii** [comment]
@glenn-jocher @Terry-50000 
I've only added the images without any text files and it worked.

**Comment by glenn-jocher** [comment]
@mnoroozii 👋 Great to hear you got it working! Skipping the empty text files and just including the images can often simplify things. If you encounter any unexpected behavior or have more questions down the road, feel free to reach out. Happy training! 🚀

**Comment by Terry-50000** [comment]
@glenn-jocher @mnoroozii  Thanks to your reply
  I also successfully trained the model with background images in the dataset. Those background images did not have a corresponding txt file. However, after the training, the model's performance seemed to have regressed, with a decreased ability to detect the target objects. Is it possible that the discrepancy between the total number of images (JPG files) and the total number of labels (TXT files) caused this result? I haven't tried yet with empty txt files, but I think that's the only choice.

**Comment by chksk** [comment]
I also have the same issue. I have already tried all the things suggested above like emptying the .txt file with the labels and even deleting the files altogether but I still get the same error after all the tries:

Traceback (most recent call last):
  File "/home/user1/train_yolov8/yolov8/train_yolo.py", line 7, in <module>
    results = model.train(data='./mockup_dataset_puzzles.yaml', epochs=150, device=2, save_period=5)
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/ultralytics/engine/model.py", line 674, in train
    self.trainer.train()
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 199, in train
    self._do_train(world_size)
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 371, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 88, in forward
    return self.loss(x, *args, **kwargs)
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 267, in loss
    return self.criterion(preds, batch)
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/ultralytics/utils/loss.py", line 222, in __call__
    _, target_bboxes, target_scores, fg_mask, _ = self.assigner(
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/ultralytics/utils/tal.py", line 72, in forward
    mask_pos, align_metric, overlaps = self.get_pos_mask(
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/ultralytics/utils/tal.py", line 94, in get_pos_mask
    align_metric, overlaps = self.get_box_metrics(pd_scores, pd_bboxes, gt_labels, gt_bboxes, mask_in_gts * mask_gt)
  File "/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/ultralytics/utils/tal.py", line 113, in get_box_metrics
    bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*w
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Do you have any sugestion on what I could do solve the issue?

**Comment by glenn-jocher** [comment]
Hey @chksk! It sounds like you've been thorough with your troubleshooting efforts. The error you're encountering suggests there might be a mismatch or an issue with the data being passed to the GPU. Here are a couple of suggestions:

1. **Ensure Data Consistency**: Double-check that all inputs to your model (like `pd_scores`, `pd_bboxes`, etc.) are on the same device (CPU or GPU) before they are used. Use `.to(device)` method to align them.

2. **Debugging Mode**: Run your training with `CUDA_LAUNCH_BLOCKING=1` set in your environment. This will make CUDA operations synchronous and can help pinpoint the exact operation causing the issue.

3. **Check Data Integrity**: Verify that your dataset does not contain any corrupt or unusual data entries. Sometimes, anomalies in the dataset can cause unexpected runtime errors.

If these steps don't resolve the issue, it might be helpful to isolate the problem further by reducing the dataset size or simplifying the model temporarily to see if the problem persists. This can help determine if the issue is data-specific or model-specific.

**Comment by chksk** [comment]
Hello @glenn-jocher. Thanks for your quick reply.

However, I already have tried the given siggestions. More specifically, the error is located in: 

_/lib/python3.10/site-packages/ultralytics/utils/tal.py", line 113, in get_box_metrics
bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt] # b, max_num_obj, hw_

as indicated by the error message I received.

As for the inputs concerning the given formula I have already forced them to be on the same device as I pointed out initially. 

Finally, all images and labels are not corrupted according to yolo's own checking methods.

Given this information could you explain in a bit more detail what you meant with your last suggestion? It is unclear to me what else could be wrong.

Thanks a lot

**Comment by glenn-jocher** [comment]
Hey there! 👋

Thanks for providing more details. It seems like the issue might be related to the indexing operation with `ind`. Even if `ind` and `pd_scores` are on the same device, the indices in `ind` might be referencing out-of-bounds locations in `pd_scores`.

Here's a quick check you can do:
- Ensure that the values in `ind` are within the valid range for the dimensions of `pd_scores`. You can add a print statement right before the error line to check the maximum values in `ind` compared to the dimensions of `pd_scores`.

```python
print("Max index:", ind.max().item(), "pd_scores shape:", pd_scores.shape)
```

If `ind` contains indices that are out of bounds for `pd_scores`, you'll need to trace back to where `ind` is being set and ensure the calculations there are correct.

Hope this helps! Let me know if there's anything else you'd like to explore. 😊

**Comment by chksk** [comment]
Hello,

Once again great advice! I was however able to fix the issue by adjusting the _single_cls=True_ parameter when starting the training as the pretrained model and the one I wanted to train had a mismatch on the number of classes.

While trying to figure out the issue I went through many parts of code and I found that in:

_/home/user1/.conda/envs/VAE_anomaly/lib/python3.10/site-packages/ultralytics/utils/torch_utils.py_ and line 158:

you permanently put the `arg="cuda:0"` statement which then only uses the gpu device with index 0 and not necessarily the one chosen by the user, the way I understand it.

Just something you could probably have a look into.

Thanks again for the help.

**Comment by glenn-jocher** [comment]
Hello!

Fantastic to hear you resolved the issue by adjusting the `single_cls=True` parameter! 🎉 It's great that you're diving deep into the code and catching such nuances.

Regarding the `arg="cuda:0"` statement you mentioned, that's an insightful observation. We aim for flexibility in device selection, so your feedback is invaluable. I'll pass this along to our development team to review and possibly enhance in future updates.

Thanks for your contribution to improving YOLOv8, and don't hesitate to reach out if you have more insights or need further assistance! Happy coding! 😊
