### ISSUE TITLE
Issue with model training that suddenly appeared despite running fine previously

### ISSUE THREAD

**Issue by MeedocTheMedic** [ultralytics/ultralytics#9856]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I was attempting to train a YOLOv8 segmentation model using custom data on Kaggle and previously I was creating models with no issues. Recently I tried running the code again to get another version of the model but suddenly it produced an error:

`AttributeError                            Traceback (most recent call last)
Cell In[18], line 1
----> 1 model.train(data="coco128-seg.yaml", epochs=128, imgsz=640)  # train the model
      2 # model.train(data="lane-seg.yaml", epochs=16, imgsz=640)  # train the model
      3 metrics = model.val()  # evaluate model performance on the validation set

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py:668, in Model.train(self, trainer, **kwargs)
    665             pass
    667 self.trainer.hub_session = self.session  # attach optional HUB session
--> 668 self.trainer.train()
    669 # Update model and cfg after training
    670 if RANK in {-1, 0}:

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py:198, in BaseTrainer.train(self)
    195         ddp_cleanup(self, str(file))
    197 else:
--> 198     self._do_train(world_size)

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py:439, in BaseTrainer._do_train(self, world_size)
    437     self.scheduler.last_epoch = self.epoch  # do not move
    438     self.stop |= epoch >= self.epochs  # stop if exceeded epochs
--> 439 self.run_callbacks("on_fit_epoch_end")
    440 torch.cuda.empty_cache()  # clear GPU memory at end of epoch, may help reduce CUDA out of memory errors
    442 # Early Stopping

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py:161, in BaseTrainer.run_callbacks(self, event)
    159 """Run all existing callbacks associated with a particular event."""
    160 for callback in self.callbacks.get(event, []):
--> 161     callback(self)

File /opt/conda/lib/python3.10/site-packages/ultralytics/utils/callbacks/raytune.py:17, in on_fit_epoch_end(trainer)
     15 def on_fit_epoch_end(trainer):
     16     """Sends training metrics to Ray Tune at end of each epoch."""
---> 17     if ray.train._internal.session._get_session():  # replacement for deprecated ray.tune.is_session_enabled()
     18         metrics = trainer.metrics
     19         metrics["epoch"] = trainer.epoch

AttributeError: module 'ray.train._internal.session' has no attribute '_get_session'`

I've even tried using the default coco dataset and it still comes up with this error. I've tried importing ray.train manually but it didn't seem to do anything and I couldn't find this issue online. Along with the fact that it only started happening recently, I can't tell if it's happening because something got updated or if something else went wrong.

### Environment

Using Kaggle, Output of ultralytics.checks():
Ultralytics YOLOv8.1.45 🚀 Python-3.10.12 torch-2.0.0 CUDA:0 (Tesla P100-PCIE-16GB, 16276MiB)
Setup complete ✅ (4 CPUs, 31.4 GB RAM, 5519.7/8062.4 GB disk)

### Minimal Reproducible Example

The code is generally the same as the kaggle notebook from Glenn just using custom data instead where the code cell that went wrong is:
`model = YOLO("yolov8s-seg.pt")  # load a pretrained model (recommended for training)

model.train(data="coco128-seg.yaml", epochs=128, imgsz=640)  # train the model

metrics = model.val()  # evaluate model performance on the validation set`

### Additional

This error only recently popped up and did not occur previously.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MeedocTheMedic please update `ray[tune]` and this should be fixed:

```
pip install -U ray[tune]
```

**Comment by MeedocTheMedic** [comment]
Thank you, that worked perfectly! I was wondering if there is a way to automatically check for necessary updates because I just originally assumed that running pip install ultralytics would download everything required.

**Comment by glenn-jocher** [comment]
I'm glad to hear that the solution worked for you! 😊 To ensure you automatically check for necessary updates, you might consider using the `pip list --outdated` command, which shows all outdated packages, including `ultralytics` and related dependencies. Then, you can update a specific package using `pip install --upgrade [package_name]`. This way, you keep your environment fresh and up-to-date! 

Unfortunately, `pip install ultralytics` does not automatically update dependencies; manual checks are beneficial. Keep experimenting and reach out if you have more questions!

**Comment by MeedocTheMedic** [comment]
Ah, I'll do that then. I generally try to keep my packages with the original version because I've messed up a few environments by updating and then code that originally worked suddenly broke, but if it's already got issues then that'll probably help. Thanks for the advice!

**Comment by glenn-jocher** [comment]
You're welcome! Yes, it can be a delicate balance between keeping things stable and updating for the latest features or fixes. A good practice is to regularly backup your environment or use virtual environments for each project, allowing for safer updates. And indeed, updating can often resolve unexpected issues. Keep exploring, and don't hesitate to ask for help if needed! 😊

**Comment by ambigi** [comment]
updating the ray[tune] does not work for me, it's showing the same error as before.

**Comment by glenn-jocher** [comment]
@ambigi i'm sorry to hear you're still experiencing issues even after updating `ray[tune]`. Could you try reinstalling the `ray[tune]` package with the following command to ensure you have the latest compatible version?

```bash
pip install --force-reinstall ray[tune]
```

Sometimes, forcing a reinstall can help clear any mismatches. If the problem persists, please check your `ray` package version and share it with us, so we can dive deeper into the issue. Thank you for your patience! 😊

**Comment by ambigi** [comment]
Thank you, that worked perfectly(while raising another unrelated exception)

**Comment by glenn-jocher** [comment]
@ambigi i'm glad to hear the initial solution helped, though it sounds like a bit of a rollercoaster with those exceptions! 🎢 For the recurring issue and considering your `ray` version is 2.3.1, this should be compatible. However, it's possible there might be an underlying conflict or a newer fix available.

Could you try updating your `ultralytics` package to the latest version? Sometimes certain fixes are pushed that might resolve these tricky situations:

```bash
pip install --upgrade ultralytics
```

If the issue persists, it might be helpful to reinstall both `ray` and `ultralytics`:

```bash
pip install --force-reinstall ray[tune] ultralytics
```

Let's cross our fingers 🤞 that does the trick! If not, we're here to dig deeper into the issue with you.

**Comment by khushijoshi30** [comment]
I tried all of this but its not working. my version of ray is 2.6.3

**Comment by khushijoshi30** [comment]
I tried all of this but its not working. my version of ray is 2.6.3

**Comment by glenn-jocher** [comment]
Hey there! It seems like you've been through quite a journey trying to resolve this 🔄. Given your `ray` version is 2.6.3, let's attempt two things:

1. **Compatibility Check**: Ensure `ultralytics` is fully compatible with `ray` 2.6.3. Sometimes, a quick check on GitHub issues or release notes can shed light on any known issues.

2. **Clean Reinstallation**: If the issue persists, consider creating a fresh virtual environment and reinstalling both packages. This helps to rule out any conflicts:

```bash
python -m venv venv
source venv/bin/activate # On Windows, use `venv\Scripts\activate`
pip install ray[tune]==2.6.3 ultralytics
```

If these steps don't help, could you provide more details about the error message or behavior you're observing? This way, we can offer more tailored assistance. Thanks for your patience and cooperation! 🛠️

**Comment by Petros626** [comment]
@khushijoshi30 where you able to solve this? I encountered the same error during validation when training.

**Comment by glenn-jocher** [comment]
This issue stems from a mismatch between the `ray` version and the method being used in the callback. The `ray` API has undergone changes, and the method `ray.train._internal.session._get_session()` has been renamed to `ray.train.get_session()` in newer versions.

To resolve this:

1. Downgrade `ray` to version `2.3.1`, as it is stable with the current Ultralytics implementation:
   ```bash
   pip install ray[tune]==2.3.1
   ```
2. Alternatively, modify the callback to use the updated API if you're managing a forked or local repository. Replace `_get_session()` with `get_session()` in `ultralytics/utils/callbacks/raytune.py`.

For a permanent fix, ensure you're using compatible versions or watch for updates in the repository addressing this change. Let us know if you need further assistance!

**Comment by Petros626** [comment]
The 2. approach did it for me!

**Comment by glenn-jocher** [comment]
Great to hear that the second approach resolved your issue! If you encounter any further challenges, feel free to reach out.

**Comment by 14790897** [comment]
The 2. approach doesn't works
```
/usr/local/lib/python3.10/dist-packages/ultralytics/utils/callbacks/raytune.py in on_fit_epoch_end(trainer)
     15 def on_fit_epoch_end(trainer):
     16     """Sends training metrics to Ray Tune at end of each epoch."""
---> 17     if ray.train._internal.session.get_session():  # replacement for deprecated ray.tune.is_session_enabled()
     18         metrics = trainer.metrics
     19         session.report({**metrics, **{"epoch": trainer.epoch + 1}})

AttributeError: module 'ray.train._internal.session' has no attribute '_get_session
```

**Comment by houdaa90** [comment]
@glenn-jocher 

I've the sane problem here, and i tried all of the above solutions. last option was `pip install ray[tune]==2.3.1`

here's my training snippet on kaggle
!yolo task=segment mode=train model=yolo11n-seg.pt data={dataset.location}/data.yaml epochs=100 imgsz=640 batch=-1

and here's the resulting error
`Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      1/100      4.25G      1.201      1.956      2.073      1.228         19   
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        806       1062      0.559      0.647      0.543      0.303      0.455      0.505      0.377      0.105
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 986, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 808, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 453, in _do_train
    self.run_callbacks("on_fit_epoch_end")
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 168, in run_callbacks
    callback(self)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/utils/callbacks/raytune.py", line 17, in on_fit_epoch_end
    if ray.train._internal.session._get_session():  # replacement for deprecated ray.tune.is_session_enabled()
AttributeError: module 'ray.train._internal.session' has no attribute '_get_session'. Did you mean: 'get_session'?`

**Comment by Petros626** [comment]
@houdaa90 solution is already there https://github.com/ultralytics/ultralytics/issues/9856#issuecomment-2612785800

**Comment by houdaa90** [comment]
@Petros626 
already tried it and didn't work for me

**Comment by Petros626** [comment]
if you got the latest version of `Ray` you can verify that `get_session` is used, look at the image I posted.

**Comment by houdaa90** [comment]
it worked fine now using this script in kaggle 

`import os
import shutil

# File paths
source_path = "/usr/local/lib/python3.10/dist-packages/ultralytics/utils/callbacks/raytune.py"
temp_path = "./raytune_temp.py"

try:
    # Step 1: Copy the original file to a temporary location
    shutil.copy(source_path, temp_path)
    print("File copied to temporary location.")

    # Step 2: Modify the file content
    with open(temp_path, 'r') as file:
        content = file.read()

    # Replace _get_session() with get_session()
    modified_content = content.replace('_get_session()', 'get_session()')

    with open(temp_path, 'w') as file:
        file.write(modified_content)
    print("File modified successfully.")

    # Step 3: Replace the original file with the modified file
    shutil.copy(temp_path, source_path)
    print("Original file replaced with the modified version.")

    # Step 4: Restart the kernel to apply changes
    print("Restarting kernel...")
    os._exit(0)

except Exception as e:
    print(f"An error occurred: {e}")`

**Comment by Petros626** [comment]
normally it should work with downgrading or replacing the old function name, but okay.

**Comment by houdaa90** [comment]
now training is finished and validation is taking more than 6 hours without even starting. it's just loading like this

![Image](https://github.com/user-attachments/assets/677e36b3-57ba-4e12-b041-7f7438f4b62b)

**Comment by Brahmajit-Ray** [comment]
Neither approach working for me...getting the same error

**Comment by glenn-jocher** [comment]
@Brahmajit-Ray to resolve the `AttributeError` with Ray Tune, manually update the callback file as shown in [this solution](https://github.com/ultralytics/ultralytics/issues/9856#issuecomment-2612785800). For slow validation, ensure your dataset is correctly formatted and paths are valid. If issues persist, share a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) for further debugging.

**Comment by UltralyticsAssistant** [comment]
Great news! A potential fix for this issue has been merged in [PR #19144](https://github.com/ultralytics/ultralytics/pull/19144). 🎉 

### Key Changes from the PR:
This PR updates the Ray Tune integration to ensure compatibility with the latest Ray versions by replacing deprecated methods:
- Updated the internal Ray Tune session call from `ray.tune.is_session_enabled()` to `ray.train._internal.session.get_session()`.
- Bumped the Ultralytics version from `8.3.73` to `8.3.74`.

These changes aim to reduce runtime errors and improve stability for users incorporating Ray Tune into their workflows.

### Testing the Fix:
To try out the updated code and confirm if it resolves the issue:
1. Install the latest changes directly from the `main` branch:
   ```bash
   pip install git+https://github.com/ultralytics/ultralytics.git@main
   ```
2. Or, wait for the next official PyPI release.

### Thanks and Feedback:
A huge thank you to @Y-T-G for authoring the PR, with valuable contributions from @glenn-jocher and @ppraneth. 🙌 Your efforts are greatly appreciated!

If this fix resolves the issue, it would be wonderful to hear back. On the other hand, if the issue persists, any additional details would help ensure it is fully addressed. Thanks again for reporting this, and happy testing! 🚀
