### ISSUE TITLE
Error using Multi-GPU

### ISSUE THREAD

**Issue by BluDvD** [ultralytics/ultralytics#9919]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Hey 

So i'am trying to train a model with multiple gpu using the command on CLI `device=0,1,2,3` but gives me this error:

(venv8) tei20293@rolf:~/RSP/yolov8$ yolo task=detect mode=train epochs=200 data=data.yaml model=yolov8n.pt imgsz=760 device=[0,1,2,3]
Ultralytics YOLOv8.1.45 🚀 Python-3.10.12 torch-2.2.2+cu121 CUDA:0 (NVIDIA A100-SXM4-80GB, 81038MiB)
                                                            CUDA:1 (NVIDIA A100-SXM4-80GB, 81038MiB)
                                                            CUDA:2 (NVIDIA A100-SXM4-80GB, 81038MiB)
                                                            CUDA:3 (NVIDIA A100-SXM4-80GB, 81038MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=data.yaml, epochs=200, time=None, patience=100, batch=16, imgsz=760, save=True, save_period=-1, cache=False, device=[0, 1, 2, 3], workers=8, project=None, name=train16, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train16
Overriding model.yaml nc=80 with nc=10

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1    753262  ultralytics.nn.modules.head.Detect           [10, [64, 128, 256]]          
Model summary: 225 layers, 3012798 parameters, 3012782 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
DDP: debug command /home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/bin/python -m torch.distributed.run --nproc_per_node 4 --master_port 57491 /home/alunos/tei/2024/tei20293/.config/Ultralytics/DDP/_temp_l8gi717g140671354290480.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Ultralytics YOLOv8.1.45 🚀 Python-3.10.12 torch-2.2.2+cu121 CUDA:0 (NVIDIA A100-SXM4-80GB, 81038MiB)
                                                            CUDA:1 (NVIDIA A100-SXM4-80GB, 81038MiB)
                                                            CUDA:2 (NVIDIA A100-SXM4-80GB, 81038MiB)
                                                            CUDA:3 (NVIDIA A100-SXM4-80GB, 81038MiB)
Overriding model.yaml nc=80 with nc=10
Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
Traceback (most recent call last):
  File "/home/alunos/tei/2024/tei20293/.config/Ultralytics/DDP/_temp_l8gi717g140671354290480.py", line 12, in <module>
    results = trainer.train()
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 198, in train
    self._do_train(world_size)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 312, in _do_train
    self._setup_train(world_size)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 259, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1910, in broadcast
    work = default_pg.broadcast([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1691, internal error - please report this issue to the NCCL developers, NCCL version 2.19.3
ncclInternalError: Internal check failed.
Last error:
Attribute busid of node nic not found
Traceback (most recent call last):
  File "/home/alunos/tei/2024/tei20293/.config/Ultralytics/DDP/_temp_l8gi717g140671354290480.py", line 12, in <module>
    results = trainer.train()
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 198, in train
    self._do_train(world_size)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 312, in _do_train
Traceback (most recent call last):
  File "/home/alunos/tei/2024/tei20293/.config/Ultralytics/DDP/_temp_l8gi717g140671354290480.py", line 12, in <module>
    self._setup_train(world_size)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 259, in _setup_train
    results = trainer.train()
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 198, in train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    self._do_train(world_size)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 312, in _do_train
    return func(*args, **kwargs)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1910, in broadcast
    self._setup_train(world_size)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 259, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    work = default_pg.broadcast([tensor], opts)
    return func(*args, **kwargs)
torch.distributed  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1910, in broadcast
.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1691, internal error - please report this issue to the NCCL developers, NCCL version 2.19.3
ncclInternalError: Internal check failed.
Last error:
Attribute busid of node nic not found
    work = default_pg.broadcast([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1691, internal error - please report this issue to the NCCL developers, NCCL version 2.19.3
ncclInternalError: Internal check failed.
Last error:
Attribute busid of node nic not found
Traceback (most recent call last):
  File "/home/alunos/tei/2024/tei20293/.config/Ultralytics/DDP/_temp_l8gi717g140671354290480.py", line 12, in <module>
    results = trainer.train()
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 198, in train
    self._do_train(world_size)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 312, in _do_train
    self._setup_train(world_size)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 259, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1910, in broadcast
    work = default_pg.broadcast([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1691, internal error - please report this issue to the NCCL developers, NCCL version 2.19.3
ncclInternalError: Internal check failed.
Last error:
Attribute busid of node nic not found
[2024-04-09 19:43:34,514] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2693739) of binary: /home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/run.py", line 816, in <module>
    main()
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/alunos/tei/2024/tei20293/.config/Ultralytics/DDP/_temp_l8gi717g140671354290480.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-04-09_19:43:34
  host      : rolf
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2693740)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-04-09_19:43:34
  host      : rolf
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2693741)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-04-09_19:43:34
  host      : rolf
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 2693742)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-09_19:43:34
  host      : rolf
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2693739)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 582, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/model.py", line 668, in train
    self.trainer.train()
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 193, in train
    raise e
  File "/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 191, in train
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/alunos/tei/2024/tei20293/RSP/yolov8/venv8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '57491', '/home/alunos/tei/2024/tei20293/.config/Ultralytics/DDP/_temp_l8gi717g140671354290480.py']' returned non-zero exit status 1.

I already uninstall everything, and reinstall and the error is the same, but if i don't use the de command `device=0,1,2,3` it works, but i want to be sure that i'am using all of the GPU

### Environment

Ultralytics YOLOv8.1.45 🚀 Python-3.10.12 torch-2.2.2+cu121 CUDA:0 (NVIDIA A100-SXM4-80GB, 81038MiB)
Setup complete ✅ (112 CPUs, 2003.9 GB RAM, 526.4/876.6 GB disk)

OS                  Linux-5.15.0-100-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 2003.91 GB
CPU                 AMD EPYC 7453 28-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.4>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.2.2>=1.8.0
torchvision         ✅ 0.17.2>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
The error you're encountering when trying to train your YOLOv8 model on multiple GPUs with `device=[0,1,2,3]` appears to stem from a distributed computing issue with NCCL (NVIDIA Collective Communications Library), specifically related to the `busid` attribute of a node. This error typically indicates that there might be a misconfiguration or compatibility issue between the GPUs or the way CUDA/NCCL are set up or being accessed.

Here are a few steps you can take to troubleshoot and potentially resolve this issue:

1. **Check CUDA and NCCL Compatibility**: Ensure that your installed versions of CUDA and NCCL are compatible with each other and with the version of PyTorch you are using.

2. **Update Drivers and Libraries**: Sometimes, simply updating your GPU drivers, CUDA, and NCCL to the latest versions can resolve these types of issues.

3. **Environment Variables**: Ensure that your environment variables are correctly set for multi-GPU training. Particularly, you might want to set or check:
   ```bash
   export NCCL_DEBUG=INFO
   export NCCL_SOCKET_IFNAME=^docker0,lo
   ```
   This will not only provide more detailed logs if the issue persists but also ensure NCCL isn't trying to communicate over unintended network interfaces.

4. **Testing NCCL**: Run the NCCL tests (available from the official NCCL GitHub repository) to ensure that NCCL is properly configured and that all GPUs are communicating correctly.

5. **Simplified Command**: Try simplifying your command or adjusting how you specify the GPUs. In some cases, the way devices are parsed could lead to issues. Instead of using `device=[0,1,2,3]` try using `device=0,1,2,3` without brackets or `CUDA_VISIBLE_DEVICES=0,1,2,3`.

6. **PyTorch Distributed Setup**: Since the error mentions broadcasting issues, make sure that your script is set up correctly for PyTorch's distributed training:
   - Use `torch.distributed.launch` with the correct `--nproc_per_node` matching the number of GPUs.
   - Ensure that your script initializes the process group correctly with `torch.distributed.init_process_group`.

7. **Minimal Training Script**: Try running a minimal training script with distributed setup to isolate the problem from any potential issues in your main training script.

If these steps do not resolve the issue, please provide the NCCL logs by setting `NCCL_DEBUG=INFO` or consider opening an issue in the NCCL GitHub repository with these logs for further assistance. Additionally, checking the PyTorch forums or the Ultralytics GitHub issues for similar problems might provide more insights or solutions from other users who have faced similar issues.

**Comment by BluDvD** [comment]
Hey there
I resolved my problem by simply invert the number, instead of device = [0,1,2,3] it goes device = [3,2,1,0] (in Python), and it worked

**Comment by glenn-jocher** [comment]
Hey! That's fantastic news 🎉! We're thrilled to hear you found a solution to your problem by inverting the device order. It's a neat trick that might help others facing similar issues. Thanks for sharing your workaround!

Just for further clarity, here's how one might specify the device order in a Python snippet:

```python
yolo.detect.train(data='data.yaml', model='yolov8n.pt', imgsz=640, device=[3, 2, 1, 0])
```

Happy training! Feel free to reach out if you have any more questions or insights. Keep up the great work!

**Comment by TomZhongJie** [comment]
when i use single GPU,it has no error.but using two GPUs,it occured 'Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.'

**Comment by BluDvD** [comment]
> Hey! That's fantastic news 🎉! We're thrilled to hear you found a solution to your problem by inverting the device order. It's a neat trick that might help others facing similar issues. Thanks for sharing your workaround!
> 
> Just for further clarity, here's how one might specify the device order in a Python snippet:
> 
> ```python
> yolo.detect.train(data='data.yaml', model='yolov8n.pt', imgsz=640, device=[3, 2, 1, 0])
> ```
> 
> Happy training! Feel free to reach out if you have any more questions or insights. Keep up the great work!

 Actually, for my case, it went ,device =[2,0,1,3]
And it makes sense because, 0 and 1 are a pair and 2 and 3 are another pair.

I use the command, nvidia smi, to see the usage

**Comment by glenn-jocher** [comment]
Awesome! Tweaking the device order to `[2, 0, 1, 3]` based on your GPU pairing and observing the usage with `nvidia-smi` sounds like a smart approach. 🧠💡 It's great to explore and share these insights as they can indeed vary depending on the system configuration. It can provide valuable guidance for others in similar setups. Thanks for sharing this update, and happy continued training! 🚀 Let us know if you stumble upon more interesting findings.
